### PR TITLE
[GCI-260] Add private constructors to hide public defaults in utility c…

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/GCI-260

### CODE REVIEW

**Comment by BartlomiejRasztabiga** [comment]
@gayanW Sorry, I missed that. Fixed already 😊

**Comment by dkayiwa** [comment]
@gayanW was it mentioned among the classes to be changed?

**Comment by gayanW** [comment]
@dkayiwa yep. It was listed in the issue.

**Comment by dkayiwa** [comment]
@BartlomiejRasztabiga did you just forget the Daemon  class?

**Comment by BartlomiejRasztabiga** [comment]
I didn't make Daemon class constructor private because other class already used it's public constructor

**Comment by dkayiwa** [comment]
Like which one?

**Comment by BartlomiejRasztabiga** [comment]
src/main/java/org/openmrs/web/WebDaemon.java:[25,7] error: Daemon() has private access in Daemon

**Pull request merged**
