### PR TITLE
TRUNK-4830: Backporting liquibase-schema-only-2.3.x.xml + liquibase-core-data-2.3.x.xml to Core 2.3.x.

### PR DESCRIPTION
**Pull request by Ruhanga**
## Description of what I changed

Backporting `liquibase-schema-only-2.3.x.xml` and `liquibase-core-data-2.3.x.xml` so they are available for use elsewhere, i.e. with Initializer Validator.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-4830

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] All new and existing **tests passed**.
- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Ruhanga this functionality was implemented in openmrs platform 2.4.0
Is there any reason why you want to do this in 2.3?

**Comment by Ruhanga** [comment]
We will upgrade to 2.4.0 in later version of iniz. For now, OpenMRS Core 2.4.0 comes with a bunch of library upgrades which come with backward compatibilities that need a little more time to carefully upgrade to. The iniz validator would also support configuration validations for the OpenMRS Core 2.3.x versions.

**Comment by dkayiwa** [comment]
@Ruhanga i do not understand what you are trying to do. It would be better to start with the exact problem you are facing. This was not a bug fix. It was new functionality done in platform 2.4.0 to improve the startup speed. Are you trying to back port this functionality to 2.3 such that you can have its startup speed also improved as per the sole purpose of that ticket?

**Comment by Ruhanga** [comment]
@dkayiwa, we would like to leverage the core data that comes with the liquibase scripts which otherwise is missing. Not sure whether some missing core data is brought in by some sql dump that I might be unaware of. E.g. the _Configure Visits_ privilege.

**Comment by dkayiwa** [comment]
@Ruhanga are you looking for this? https://github.com/openmrs/openmrs-core/blob/2.0.0/api/src/main/java/org/openmrs/util/PrivilegeConstants.java#L208-L209

**Comment by Ruhanga** [comment]
Yes @dkayiwa, thanks. So where do I find the initial database upon which the liquibase changesets on the 2.3.x branch are run?

**Comment by dkayiwa** [comment]
@Ruhanga the database starts when completely empty and then this liquibase file populates it with the startup data: https://github.com/openmrs/openmrs-core/blob/2.3.0/api/src/main/resources/liquibase-core-data.xml

**Comment by Ruhanga** [comment]
Thanks for the pointers @dkayiwa. From where/ how is this [liquibase-core-data.xml](https://github.com/openmrs/openmrs-core/blob/2.3.0/api/src/main/resources/liquibase-core-data.xml) loaded?

**Comment by dkayiwa** [comment]
For which openmrs platform version?

**Comment by Ruhanga** [comment]
For the OpenMRS platform 2.3.x

**Comment by dkayiwa** [comment]
https://github.com/openmrs/openmrs-core/blob/2.3.0/web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java#L1556-L1557

**Comment by Ruhanga** [comment]
Thanks for the thumbs up @dkayiwa. It turns out that I was loading the liquibases  files correctly(see iniz [PR](https://github.com/mekomsolutions/openmrs-module-initializer/pull/217)) as you pointed out but was failing to load them successfully because of a mysql-connector version that gave rise to [this famous error](https://talk.openmrs.org/t/unable-to-set-up-new-platform-2-3-4-snapshot-using-sdk/35159).

**Comment by Ruhanga** [comment]
Closing this as not necessary.

**Pull request closed without merging**
