### PR TITLE
Added test for bug report TRUNK-4831. This confirms that the bug is s…

### PR DESCRIPTION
**Pull request by winglam**
…till not fixed and should help developers locate the bug in the source code. https://issues.openmrs.org/browse/TRUNK-4831

### CODE REVIEW

**Comment by dkayiwa** [comment]
@winglam can you include the pull request url on the ticket?

**Comment by winglam** [comment]
I have included the pull request URL on the ticket. Thanks.

**Comment by dkayiwa** [comment]
@winglam so do you now want to fix the ticket? Or did you just want to create a test reproducing it? :)

**Comment by winglam** [comment]
I just wanted to create tests to reproduce the bug since it wasn't clear from the ticket whether this was still a problem. I will look into fixing this soon :)

**Comment by dkayiwa** [comment]
If you only wanted to create tests, in order to merge your changes, you can put ignore annotations on the tests and comment on the ticket that these will need to be removed once the ticket is fixed.

**Comment by winglam** [comment]
I have ensured that this pull request is consistent with #1780 and updated the ticket with information about this pull request.

**Comment by dkayiwa** [comment]
@winglam am closing because the failure of this test (org.openmrs.api.ValidationException: 'Patient#null' failed to validate with reason: Select a preferred identifier) is not caused by the reported problem.

**Pull request closed without merging**
