### PR TITLE
TRUNK-5446: Validation and error message for setting past visit before birthdate

### PR DESCRIPTION
**Pull request by nishitde**
… before birthdate

https://issues.openmrs.org/browse/TRUNK-5446?src=confmacro

### CODE REVIEW

**Comment by gitcliff** [comment]
@nishitde have you seen the travis ci failure

**Comment by HerbertYiga** [comment]
@nishitde  as per the CI logs,you have a failing test on VisitValidatorTest.validate_shouldFailValidationIfVisitDateBeforeBirthDate  .you can also use mvn clean package before pushing to remove the unnecessary code formats

**Comment by sherrif10** [comment]
@nishitde you could also remove one level of indentation

**Comment by gracepotma** [comment]
@nishitde would you like to finish this work based on the feedback above? Or should we reassign this ticket?

**Comment by nishitde** [comment]
You can go ahead and reassign the ticket.

Regards,
Nishit De

**Pull request closed without merging**
