### PR TITLE
TRUNK-5535:Upgrade org.codehaus Libraries

### PR DESCRIPTION
**Pull request by jwnasambu**
## Description of what I changed
I upgraded a sub Library org.codehaus.sonar-plugins.java:sonar-jacoco-listeners … 3.1 -> 3.2

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5535

### CODE REVIEW

**Comment by jwnasambu** [comment]
@dkayiwa kindly review my work at your own convenience.

**Comment by mozzy11** [comment]
@jwnasambu  looks fine

**Comment by mozzy11** [comment]
cc @dkayiwa

**Comment by dkayiwa** [comment]
How different is it from this? https://mvnrepository.com/artifact/org.sonarsource.java/sonar-jacoco-listeners

**Comment by jwnasambu** [comment]
@dkayiwa am sorry for taking  long to respond to this PR.  I just saw your comment today! I kindly need your clarification basing on the link you shared. The ticket requires me to upgrade JaCoCo Listeners  sub library from version 3.1 -> 3.2 which I did and the build was successful. What am not understanding is if am supposed to upgrade to the latest version which is  5.14.0.18788. Kindly help me understand your commend. Thanks

**Comment by jwnasambu** [comment]
@teleivo this is the link https://mvnrepository.com/artifact/org.sonarsource.java/sonar-jacoco-listeners

**Comment by teleivo** [comment]
@jwnasambu please compare the group I'd. the link you provides showas an artifact with a different group id  we depend on

```xml
<groupId>org.codehaus.sonar-plugins.java</groupId>
				<artifactId>sonar-jacoco-listeners</artifactId>
```

**Comment by jwnasambu** [comment]
@teleivo Thanks for the feedback! its unfortunate I didn't take a keen look at it after being refereed to the link by a reviewer.

**Comment by teleivo** [comment]
> How different is it from this? https://mvnrepository.com/artifact/org.sonarsource.java/sonar-jacoco-listeners

are you suggesting that we switch to the artifact you posted? since its not the one we are using.

**Pull request closed without merging**
