### PR TITLE
TRUNK-5861: Use Annotations  Mappings to configure DrugIngredient  Entity

### PR DESCRIPTION
**Pull request by abertnamanya**
… to Annotations

## Description of what I changed

-  Added Entity annotations to DrugIngredient model class
- Removed DrugIngredient.hbm.xml from hibernate.cfg.xml since its nolonger needed 
-  Added DrugIngredient.class to api/src/test/java/org/openmrs/api/OrderServiceTest.java  under saveOrder_shouldFailIfTheJavaTypeOfThePreviousOrderDoesNotMatch() method to be presented as one of the hibernate annotated classes for testing 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5861

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by HerbertYiga** [comment]
> see https://issues.openmrs.org/browse/TRUNK-5861

lets add a better description on this pr of what you did, though still we need its ticket id

**Comment by HerbertYiga** [comment]
otherwise the code looks fine

**Comment by abertnamanya** [comment]
> otherwise the code looks fine ,i am happy to approve as soon as we improve the description

Thank you @HerbertYiga . Let me do the needful

**Comment by abertnamanya** [comment]
> > see https://issues.openmrs.org/browse/TRUNK-5861
> 
> lets add a better description on this pr of what you did, though still we need its ticket id

Dear @HerbertYiga please checkout the changes I have made in the PR description

**Comment by tendomart** [comment]
I have approved maven build...

I think tis good enough

**Comment by HerbertYiga** [comment]
@abertnamanya   i notice the build breaks with UserServiceTest.getAllUsers_shouldNotContainsAnyDuplicateUsers:680 expected: <11> but was: <12>

**Comment by tendomart** [comment]
And he is having the same issue at https://github.com/openmrs/openmrs-core/pull/3969

@abertnamanya have you tried to do "**git pull  --rebase upstream master**"  before pushing to make sure your repo is up to date with upstream master branch ?

**Comment by abertnamanya** [comment]
> And he is having the same issue at #3969
> 
> @abertnamanya have you tried to do "**git pull --rebase upstream master**" before pushing to make sure your repo is up to date with upstream master branch ?

@kdaud Just created a ticket for this issue. https://issues.openmrs.org/browse/TRUNK-6056

**Pull request closed without merging**
