### PR TITLE
TRUNK-5535:Upgrade org.codehaus Libraries

### PR DESCRIPTION
**Pull request by hillarykimo**
## Description of what I changed
I  changed  from `<jacksonVersion>2.12.5</jacksonVersion> `to `<jacksonVersion>2.13.0</jacksonVersion>` based on this 
https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mapper-asl

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5535

### CODE REVIEW

**Comment by hillarykimo** [comment]
@dkayiwa kindly review my PR at your convenient time.

**Comment by dkayiwa** [comment]
Isn't `rc` a release candidate. If so, i would wait for the final release.

**Comment by hillarykimo** [comment]
@dkayiwa  thank you. let me wait   for the release

**Comment by HerbertYiga** [comment]
> thank you. let me wait for the release

@hillarykimo  though it looks like its arleady out https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core

**Comment by hillarykimo** [comment]
@HerbertYiga I had followed the same link but it seems there is a final release after 2.13.0-rc2  which is a candidate release

**Pull request closed without merging**
