### PR TITLE
TRUNK-4947 

### PR DESCRIPTION
**Pull request by mavrk**
## Description

Added method ConceptService.getConceptSourceByHL7Code(String)
to the appropriate classes and updated test classes to check for Null as well as valid hl7Code

## Related Issue

see https://issues.openmrs.org/browse/TRUNK-4947

## Checklist:

- [ 1] My pull request only contains one single commit.
- [ 1] My pull request is based on the latest master branch
  `git pull --rebase upstream master`.
- [ 1] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [ 1] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ 1] I have added tests to cover my changes.
- [ 1] All new and existing tests passed.

### CODE REVIEW

**Comment by mavrk** [comment]
@dkayiwa Is this fine?

**Comment by dkayiwa** [comment]
@mavrk can you also add a test which returns the expected source when given valid hl7code?

**Comment by mavrk** [comment]
@dkayiwa Sure. I will add that test. Do you want me to keep everything else 'as is'?

**Comment by mavrk** [comment]
One more thing @dkayiwa I made the method getConceptSourceByhl7Code(). Do you want me to change it to getConceptSourceByHL7Code()?

**Comment by dkayiwa** [comment]
Can you take a look at the class to see what is used elsewhere?

**Comment by mavrk** [comment]
Sure thanks :)

**Comment by mavrk** [comment]
Hey @dkayiwa Can you give me any example of an HL7Code ? I tried looking at the .frm files in the sample db but got nothing.

**Comment by dkayiwa** [comment]
Are you making changes in .frm or .java files?

**Comment by mavrk** [comment]
Where can I find a pre-existing hl7Code to get conceptSource for? Or shall I add it myself with a <concept_reference_source> dataset in the .xml files for the tests.

**Comment by dkayiwa** [comment]
Did i just misunderstand your original question? You seem to be asking something else now.

**Comment by mavrk** [comment]
Ok let me clarify. In my test class I want to add a test which gives an expected source when given a valid hl7Code. So I am thinking of passing an existing hl7Code to getConceptSourceByHl7Code() and then I'll verify if the returned ConceptSource is true. So I am asking where can I find an hl7Code which I can use for the test?

**Comment by dkayiwa** [comment]
Do you see the comment where you started with: "One more things...."

**Comment by mavrk** [comment]
I think I found what I was looking for. I'll code and run the tests. Thanks :)

**Comment by mavrk** [comment]
The test for an expected ConceptSource when given a valid hl7Code is done. Anything else I need to add?

**Pull request closed without merging**
