### PR TITLE
Apptest 57

### PR DESCRIPTION
**Pull request by hirschf2**
Increased coverage for getForm(String, String) in the FormService class. Some combinational input values were not covered (in this case, null values). A test was written to check two null inputs, 1 null input and string name, and another null input and string version. These tests pass using assertNull.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why did Travis fail?

**Comment by hirschf2** [comment]
I'm unfamiliar with Travis, but the test worked fine on my build. Any ideas?

**Comment by robbyoconnor** [comment]
did you run tests. Travis CI is just for running tests. If it fails, it means something is wrong.

**Comment by hirschf2** [comment]
Yes, when I run "mvn test" locally, I get a build success. I have also individually tested the class I modified and still returned a success. Could it be a specific version of my maven that is causing a failure?

**Comment by robbyoconnor** [comment]
If you click Close and then click reopen on your PR -- you'll trigger travis to rebuild -- it likely stalled based on what I can see from the logs

**Comment by robbyoconnor** [comment]
OK it's passing now...sometimes Travis CI hangs

**Comment by dkayiwa** [comment]
@hirschf2 can you squash these commits into one? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@hirschf2 did you see my comment above?

**Comment by dkayiwa** [comment]
@hirschf2 i will reopen this after you have responded to the comments above. :)

**Pull request closed without merging**
