### PR TITLE
TRUNK-6192: Fix bug related to continuous listener additions

### PR DESCRIPTION
**Pull request by Ruhanga**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-6192

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Review by mogoodrich — CHANGES_REQUESTED** [review]
Instead of this hack, I think all we need to do it move line 67 (initialized = true) outside of the if/then block, to confirm that the init method is only run once.  The "globalPropertyChanged" method should handle updated in the template if the global property changes.

**Comment by Ruhanga** [comment]
Sorry I missed the notification here @mogoodrich. The challenge in that approach is, since the `NameSupport.java` is a Spring bean that's instantiated once, it would then miss an initialisation involving the custom configured template if one existed. This mean that the custom configured template would only come into effect only after its global property has been added/updated which, 99% won't happen. 

An alternative approach was to make the list of listeners a Set.

**Comment by mogoodrich** [comment]
Interesting @Ruhanga , you mean because the Name Support bean could be initialized before the Admin Service is ready?  What makes this different from the AddressSupport template that appears to do the same thing?

**Comment by Ruhanga** [comment]
The AddressSupport template is not a Spring bean actually. It gets instantiated if not at the first call to getInstance().

**Comment by ibacher** [comment]
@Ruhanga If the issue is that it's a Spring bean, couldn't we take advantage of that to have it call `init()` as either a Spring initializer or `@PostConstruct` or similar and skip having to call `init()` in every call to `getInstance()`?

**Review by Ruhanga — COMMENTED** [review]
Hi @ibacher, sorry I got overtaken by some other tasks and forgot to respond to your comment above. Hope we are good now...

**Comment by Ruhanga** [comment]
Closing this in favour of this commit here:

https://github.com/openmrs/openmrs-core/commit/e878c6389843cb052b4d158afac2582112312939

**Pull request closed without merging**
