### PR TITLE
TRUNK-5553:Upgrade postgresql:postgresql

### PR DESCRIPTION
**Pull request by jwnasambu**
## Description of what I changed
Upgrade library postgresql:postgresql from 9.0-801.jdbc4 to 9.1-901-1.jdbc4

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5553

### CODE REVIEW

**Comment by jwnasambu** [comment]
@dkayiwa kindly review my work at your convenience time.

**Comment by mozzy11** [comment]
looks fine @jwnasambu  

cc @dkayiwa

**Comment by dkayiwa** [comment]
Did you evaluate where this was moved? https://mvnrepository.com/artifact/org.postgresql/postgresql

**Comment by jwnasambu** [comment]
@dkayiwa I have tried to update to the latest release which is 42.2.5 but it fails to build locally

**Comment by dkayiwa** [comment]
Can you share the failure log?

**Comment by jwnasambu** [comment]
@dkayiwa this is the error log https://pastebin.com/LmGNZC65 after trying out versions 42.2.5,42.2.4 and 42.2.3

**Comment by Am-Coder** [comment]
I think this error is because you also need to change the dependency in web/pom.xml and api/pom.xml apart from adding the dependency in parent pom.
to :
```
		<dependency>
		    <groupId>org.postgresql</groupId>
		    <artifactId>postgresql</artifactId>
	   	</dependency>
```
https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.8 . 
I am also trying to run openmrs on PostgreSQL and am not facing this issue.

**Comment by jwnasambu** [comment]
@Am-Coder  thanks so much for your submission however, for this case  the changes are only made in the  pom.xml (openmrs) file which is placed under root folder of the project. This file contains information about the project and its configuration details used by Maven to build the project e.g. sourcecode location, project dependencies etc . When executing a task or goal, maven reads the pom.xml, gets the needed configuration information, then executes the goal.  In addition, pom.xml files maintain a parent-child relationship between them. A child POM e.g test, webapp,web pom file inherits all the configuration elements from its parent POM file. This is how Maven sticks to its design philosophy, which is convention over configuration that supports a reason why I don't need to change the dependency in web/pom.xml and api/pom.xml.

**Comment by Am-Coder** [comment]
Thanks for enlightening me @jwnasambu . It was really informative. I have one last doubt. Shouldn't we change the groupId in child pom according to that of parent otherwise there might be conflict in inheritting the settings from parent and thus child pom might use an artifact different from that of parent and thus a different dependency. Here the group id of child pom( postgresql )will be different if we make use of postgresql version 42.2.x (org.postgresql).

https://github.com/openmrs/openmrs-core/blob/9345129fdfb38242baa3241230f84622f3fc10e6/web/pom.xml#L78-L81

**Comment by gitcliff** [comment]
@jwnasambu  kindly look in to the merge conflicts and may @dkayiwa can make final reviews

**Comment by jwnasambu** [comment]
@cliff the conflict is due to the updates made on the ticket which are already merged and I have no control over it. The only option is to close this PR. Thanks

**Pull request closed without merging**
