### PR TITLE
Resolve 3.3.2

### PR DESCRIPTION
**Pull request by slubwama**
## Issue I worked on

**Issue: 3.3.2**

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by rkorytkowski** [comment]
Have you tested it locally? It is very likely that it won't work if you are not using https to access the web server, which is typical for localhost (development) and also may be for some simple implementations that run in LAN and didn't setup https.

**Comment by slubwama** [comment]
@

> Have you tested it locally? It is very likely that it won't work if you are not using https to access the web server, which is typical for localhost (development) and also may be for some simple implementations that run in LAN and didn't setup https.

@rkorytkowski I tested in an HTTP environment and it seemed fine

**Comment by ibacher** [comment]
So, I actually think this PR might be causing an issue described [here](https://talk.openmrs.org/t/failure-to-login-after-database-initialization-no-error-shown-at-frontend/43766). The problem is that the RFC leaves it up to the user-agent (browser) to determine what "Secure" means. Most browsers simply define "localhost" as being a secure context, so this means that this would work for HTTP requests run locally, but not for HTTP requests served over the network.

It's actually hard, given the nature of web proxies, to detect whether a request is made via HTTPS. For example, our infra serves everything from behind nginx proxies, which is also where we terminate SSL. This means that even if, e.g., a request to https://dev3.openmrs.org/openmrs/ uses "HTTPS", by the time it hits Tomcat, its just a plain HTTP request. However, this issue itself is probably better resolved at the nginx reverse proxy level rather than here.

**Comment by ynurmahomed** [comment]
We are facing issues with our implementations that run in LAN, likely due to this change. Can it be made configurable?

**Pull request merged**
