### PR TITLE
APPTEST-55: Add unit tests in PersonNameValidatorTest.java for RA-543

### PR DESCRIPTION
**Pull request by hank205**
In PersonNameValidatorTest.java,
add unit tests that fail due to the bug reported in
https://issues.openmrs.org/browse/RA-543?filter=10068

### CODE REVIEW

**Comment by dkayiwa** [comment]
@hank205 can you include the pull request url on the ticket?

**Comment by hank205** [comment]
I thought I did! The url for the ticket:
https://issues.openmrs.org/browse/APPTEST-55

**Comment by dkayiwa** [comment]
@hank205 i do not see the pull request url on the ticket. Did you take a look at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by hank205** [comment]
@dkayiwa I pasted the url for this page to the end of description at: https://issues.openmrs.org/browse/APPTEST-55
Is it what I supposed to do?

**Comment by dkayiwa** [comment]
@hank205 that is correct. Do you now want to go ahead and fix the ticket? Or did you just want to create tests reproducing the reported problem? If you only wanted to create tests, in order to merge your changes, can you put ignore annotations on the tests and comment on the ticket that these will need to be removed once the ticket is fixed?

**Comment by hank205** [comment]
@dkayiwa sorry I accidentally deleted the branch. I have restored the branch, and added the ignore annotations. Could you open it again?
Or should I create a new pull request?

**Comment by dkayiwa** [comment]
@hank205 i cannot reopen because the branch was either force pushed or recreated.

**Comment by hank205** [comment]
@dkayiwa Appreciate for your patience, here's my new pull request #1780

**Pull request closed without merging**
