### PR TITLE
Core changes to extract owa

### PR DESCRIPTION
**Pull request by SandeepRaparthi1**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 do you notice that your pull request has merge conflicts? Did you pull the latest changes from upstream?

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 did you also create a ticket with details as to why we need this pull request?

**Comment by SandeepRaparthi1** [comment]
@dkayiwa I do not intend to merge this PR as of now.I will keep trying to intercept the method i made changes to in this PR from my module and try best to avoid core changes.
This PR was just to get the ball rolling if i am not successful in intercepting the method.Apologies for not informing in prior.Shall i close this ?

**Comment by dkayiwa** [comment]
Yes close it for now!

On Wed, Jul 29, 2015 at 5:34 AM, Sandeep Raparthi <notifications@github.com>
wrote:

> @dkayiwa <https://github.com/dkayiwa> I do not intend to merge this PR as
> of now.I will keep trying to intercept the method i made changes to in this
> PR from my module and try best to avoid core changes.
> This PR was just to get the ball rolling if i am not successful in
> intercepting the method.Apologies for not informing in prior.Shall i close
> this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1531#issuecomment-125814197>
> .
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by SandeepRaparthi1** [comment]
@dkayiwa Okay

**Pull request closed without merging**
