### PR TITLE
TRUNK-381: Support for alternate authentication schemes.

### PR DESCRIPTION
**Pull request by mks-d**
## Issue I worked on

This is the backport to 2.1.x of TRUNK-381.
see https://issues.openmrs.org/browse/TRUNK-381

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the 2.1.x branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mks-d is there any reason why you would want to back port a new feature?

**Comment by mks-d** [comment]
@dkayiwa ok so this is because we are following the Ref App releases. Currently 2.9.0 is still based on 2.1.x hence this PR.

Would it be ok to "backport" this to 2.2.x though, since it has not been fully released yet? And we would commit to run on 2.2.x since @mogoodrich has posted reassuring feedback about it (see [here](https://talk.openmrs.org/t/platform-2-2-0-beta-testing/21871/12?u=mksd)).

**Comment by dkayiwa** [comment]
2.2.0 is already released. Would you do a maintenance release of 2.2.1?

**Comment by mks-d** [comment]
@dkayiwa, damn, yes sure. First I need to backport the feature...

**Pull request closed without merging**
