### PR TITLE
TRUNK-4653 "Dodgy - Dead store to local variable"

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by tomaszmueller** [comment]
Fixed in file PatientServiceImpl.java.
In ModuleClassLoader.java local variable seems to be needed. How to suppress sonar reports?

**Comment by dkayiwa** [comment]
@tomaszmueller where is it needed (used)?

**Comment by tomaszmueller** [comment]
Fixed ModuleClassLoader.java too

**Comment by dkayiwa** [comment]
@tomaszmueller can you squash these commits into one?

**Comment by tomaszmueller** [comment]
@dkayiwa done

**Pull request merged**
