### PR TITLE
TRUNK-5193 - Upgrade Spring to latest 4.3.18

### PR DESCRIPTION
**Pull request by wluyima**
Added media types

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5193

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@wluyima i tried running the web application with these changes and this link stopped working in the sense that when i click the "send" button, nothing happens: http://localhost:8080/openmrs/module/webservices/rest/test.htm

**Comment by dkayiwa** [comment]
/openmrs/ws/rest/v1/patient/495b10c4-56bd-11df-a35e-0027136865c4

And just in case, am running from eclipse using jetty

**Comment by wluyima** [comment]
Of course that's invalid because no patient exists with that uuid, plus the default request is method GET yet there there is a request body specified, the default values are bogus, we need to fix it, possibly replace it to GET a resource that ships as core data e.g unknown location, care settings or the patient identifier types.

**Comment by dkayiwa** [comment]
Without your changes, i get the expected error message of object not found. With your changes, i click and nothing happens. I even tried putting a uuid of an existing patient and it works without your changes. With your changes, clicking does not do anything.

**Comment by wluyima** [comment]
On demo.openmrs.org I get the same behavior, bad request

**Comment by wluyima** [comment]
I 'm not sure what exaclty you're doing, I get the same exact behavior in demo.openmrs.org and https://qa-refapp.openmrs.org/openmrs/ as the instance with my changes.

The behavior am getting is, if you don't clear the body content and do a GET you get back a bad request error and if you clear it you get object not found which seems correct and you get the same on our test servers, so you can't go by default values on that page for the reasons I mentioned.

**Comment by dkayiwa** [comment]
With your changes, i do not get anything with bad values. I still do not get anything even with the correct values. Without your changes, i at least get bad request with bad data and correct results with correct data. May be we ask some one else to try out and tell us what they get.

**Comment by wluyima** [comment]
I think you have caching issues, please test in the test servers

**Comment by dkayiwa** [comment]
@wluyima which test servers?

**Comment by wluyima** [comment]
https://wiki.openmrs.org/display/ISM/OpenMRS+environments

**Comment by wluyima** [comment]
You can just try demo.openmrs.org

**Comment by dkayiwa** [comment]
Removed the `favorPathExtension ` and `useJaf ` properties to fix the reported problem and committed at https://github.com/openmrs/openmrs-core/commit/3a61d65d18eec3202f404aa60223ae5f44f73144

**Pull request closed without merging**
