### PR TITLE
TRUNK-4497:Hide or disable (option of selecting) a child role instead of...

### PR DESCRIPTION
**Pull request by SharonVarghese**
... throwing an error

### CODE REVIEW

**Comment by dkayiwa** [comment]
@SharonVarghese does this actually fix the problem where someone has added a child role to a role and then tries to go and make the child role a parent, creating chaos?

**Comment by SharonVarghese** [comment]
@dkayiwa  Yes because when we create a role called parent, then we create a role called child. This child inherits from the parent. Before applying the changes, the parent could also inherit from the child. After applying the changes, the parent cannot inherit from the child, because the button is disabled .

**Comment by dkayiwa** [comment]
@SharonVarghese on the ticket, can you attach a screenshot showing the effects of your changes to confirm that what you are saying is so?

**Comment by SharonVarghese** [comment]
@dkayiwa  I have attached screenshots of the changes , and while reproducing the error, if in the parent's role edit page, the child option was ticked, it would give an error, but now, the child option checkbox is disabled

**Pull request closed without merging**
