### PR TITLE
Trunk 4747

### PR DESCRIPTION
**Pull request by jdegraft**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@jdegraft can you squash these commits into one?

**Comment by jdegraft** [comment]
dkayiwa: hang on, I did not actually push the squashed commit and now I have conflicts. I will update when the new commit is ready for review.

**Comment by jdegraft** [comment]
dkayiwa: I have two commits, one on Oct 1 (yesterday) which was the changes, and one today which fixes conflicts. This commits have have all the changes squahed into one commit.

**Comment by jdegraft** [comment]
dkayiwa: last commit broke CI build, let me fix, hang on!

**Comment by jdegraft** [comment]
dkayiwa: here are the changes with no conflicts.

**Comment by dkayiwa** [comment]
@jdegraft you need to squash the commits into one as advised at http://go.openmrs.org/pull-request-tips

**Comment by jdegraft** [comment]
dkayiwa: Only the last commit is relevant and it is already squashed.

**Comment by dkayiwa** [comment]
@jdegraft squashing reduces them to one. Looks like you have not been lucky with squashing. So am closing such that you just create a new pull request.

**Pull request closed without merging**
