### PR TITLE
Fixes of Sonar critical issues

### PR DESCRIPTION
**Pull request by lluismf**
https://ci.openmrs.org/sonar/drilldown/issues/1865

### CODE REVIEW

**Comment by dkayiwa** [comment]
@lluismf looks like you need to pull the latest upstream changes to fix the merge conflicts in this pull request.

**Comment by lluismf** [comment]
Done, it seems that DrugHandler was removed while I was doing changes.

**Comment by lluismf** [comment]
Something is wrong, I used a class DbUtil to close JDBC resources that apparently is not present in the CI jars. How can that be? It's a Maven dependency (databene-commons-0.4.9)

**Comment by dkayiwa** [comment]
@lluismf did i just take long to see this until it got out of date? :)

**Comment by lluismf** [comment]
I messed up with a new commit. I need to figure out how to fix it.

**Pull request closed without merging**
