### PR TITLE
TRUNK-3933:Forgotten Password Form Leaks Valid Usernames

### PR DESCRIPTION
**Pull request by SharonVarghese**

### CODE REVIEW

**Comment by SharonVarghese** [comment]
I will work on the issues, thanks @dkayiwa

**Comment by SharonVarghese** [comment]
@dkayiwa  I am unclear about the line number 89 you had mentioned , could you explain exactly the requirement as the map is to check about valid usernames  . Thank you :)

**Comment by dkayiwa** [comment]
I was just saying that in simply keeps incrementing by 1 yet your code
assumes a maximum of 7 questions. So a bug.

On Thu, Feb 12, 2015 at 7:41 PM, SharonVarghese <notifications@github.com>
wrote:

> @dkayiwa <https://github.com/dkayiwa> I am unclear about the line number
> 89 you had mentioned , could you explain exactly the requirement as the map
> is to check about valid usernames . Thank you :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1322#issuecomment-74104444>.
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by SharonVarghese** [comment]
@dkayiwa  Now I get it , thank you :)

**Pull request closed without merging**
