### PR TITLE
TRUNK-3195: creating JUnit Test for validate behavior of HibernateFormDAO.getFormCriteria

### PR DESCRIPTION
**Pull request by Fernando-Jack**
https://issues.openmrs.org/browse/TRUNK-3195

### CODE REVIEW

**Comment by Fernando-Jack** [comment]
I created the unitTest getForms_shouldReturnFormsThatHaveAnyMatchingFormFieldsInContainingAnyFormField(). 
I placed it in FormServiceTest. I thought it would be better there. Besides this modification I basically followed the modifications done by Jakub Buczyński.

I added a new data-set FormServiceTest-multipleForms-formFields.xml. I did it because when the data-set FormServiceTest-formFields.xml contains more than one form-data it will break the UnitTest getForms_shouldReturnFormsContainingAllFormFieldsInContainingAllFormFields.
It happens because the test asserts the expect number of forms and it didn't match.
The problem is here. https://github.com/Fernando-Jack/openmrs-core/blob/master/api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java#L457-L462
The query return a wrong number of forms when the dataset has more than one form.

I used the code here "http://stackoverflow.com/questions/554481/how-to-get-sql-from-hibernate-criteria-api-not-for-logging" to extract the sql generated by the CriteriaQuery and the query created was this. 

select * from
form this_
	where ? < (
	select count(ff_.form_field_id) as y0_ from 
	  form_field ff_ 
	  where ff_.form_id=ff_.form_id and ff_.form_field_id in (?, ?)
	)

Jakub Buczyński had noticed it and He was close to fix the problem. He tried to fix this error here
 https://github.com/jbuczynski/openmrs-core/blob/c8c39b79c695e254a4ce0037c468302f1b053455/api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java#L459-464. But his modifications generated the below.  But it didn't fixed the problem.

select * from form this_ 
	where this_.form_id = all (
		select ff_.form_id as y0_ from	form_field ff_	where ff_.form_field_id in (?, ?, ?)
	)

After some time, I figured out this query :
select * from  form outerForm
where 2 <= 
       (select  count(*) from  form innerForm
                inner join
            form_field formfield ON innerForm.form_id = formfield.form_id
        where
            innerForm.form_id = outerForm.form_id and formfield.form_field_id in (2,3))

I implemented it with HibernateCriteria here. https://github.com/Fernando-Jack/openmrs-core/blob/correctingUnitTest/api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java#L457-L464

All the modifications described are in this commit: https://github.com/Fernando-Jack/openmrs-core/commit/1a99ecc23371676cc90d69da807e8d58f8fbfd74

**Comment by Fernando-Jack** [comment]
Question
 - Should I make a new pull request with this commit: https://github.com/Fernando-Jack/openmrs-core/commit/1a99ecc23371676cc90d69da807e8d58f8fbfd74 With all modifications described above? Or split it in two commits?

-Thanks

**Comment by dkayiwa** [comment]
@Fernando-Jack can you squash these commits into one?

**Comment by Fernando-Jack** [comment]
Yes, no problems.
But should I make a new pull request with this commit: https://github.com/Fernando-Jack/openmrs-core/commit/1a99ecc23371676cc90d69da807e8d58f8fbfd74 or just squash these commits and make a new pull request?

thanks

**Comment by Fernando-Jack** [comment]
Yes, no problems @dkayiwa .
But should I make a new pull request with this commit: Fernando-Jack@1a99ecc or just squash these commits and make a new pull request?

thanks

**Comment by dkayiwa** [comment]
Just squash the commits for this very pull request.

On Tue, Mar 31, 2015 at 3:58 PM, Fernando Barbosa <notifications@github.com>
wrote:

> Yes, no problems @dkayiwa <https://github.com/dkayiwa> .
> But should I make a new pull request with this commit: Fernando-Jack@
> 1a99ecc <https://github.com/Fernando-Jack/openmrs-core/commit/1a99ecc> or
> just squash these commits and make a new pull request?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1444#issuecomment-88074195>.
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by Fernando-Jack** [comment]
Hi @dkayiwa 
Is it right now?

Thanks

**Comment by Fernando-Jack** [comment]
Hi @dkayiwa
Do you think I should change something?

Thanks

**Pull request merged**
