### PR TITLE
TRUNK-4682: Replace JDBC with Hibernate native query

### PR DESCRIPTION
**Pull request by lluismf**
https://issues.openmrs.org/browse/TRUNK-4682

### CODE REVIEW

**Comment by djazayeri** [comment]
Just to verify, do we have good test coverage for the method we are changing?

**Comment by dkayiwa** [comment]
@lluismf the case of concept_numeric is handled by the unit test named: saveConcept_shouldSaveNonConceptNumericObjectAsConceptNumeric
Could we have another unit test to deal with concept_complex?

**Comment by lluismf** [comment]
I will recheck the subquery and create a new test, but take into account that the current version is already buggy (try creating a concept number and then changing to complex => throws an exception).

**Comment by dkayiwa** [comment]
@lluismf by current version, do you mean the one before you changes?
About changing a concept to complex, do you mean in the user interface?

**Comment by lluismf** [comment]
Yes, the version already running on the demo server. Please try for yourself.

**Comment by dkayiwa** [comment]
demo is not using master. Did you try on master?

On Tue, Apr 21, 2015 at 7:04 PM, Lluis Josep Martinez <
notifications@github.com> wrote:

> Yes, the version already running on the demo server. Please try for
> yourself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1479#issuecomment-94854009>.
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by lluismf** [comment]
I tested it before doing my changes so I guess it was master, but I can recheck. Are you aware of this exception by the way?

**Comment by dkayiwa** [comment]
No.

On Tue, Apr 21, 2015 at 7:12 PM, Lluis Josep Martinez <
notifications@github.com> wrote:

> I tested it before doing my changes so I guess it was master, but I can
> recheck. Are you aware of this exception by the way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1479#issuecomment-94856469>.
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by lluismf** [comment]
I ran the webapp on master and got this when changing from Numeric to Complex:

An Internal Error has Occurred
org.hibernate.NonUniqueObjectException
a different object with the same identifier value was already associated with the session: [org.openmrs.ConceptComplex#7]

Running it with my changes throws exactly the same exception, following the same steps.

**Comment by lluismf** [comment]
https://issues.openmrs.org/browse/TRUNK-835

**Comment by dkayiwa** [comment]
@lluismf i have just changed a concept from numeric to complex, both at http://int01.openmrs.org:8080/openmrs and locally. It all works well before your changes. :)

**Comment by lluismf** [comment]
Change to numeric again, then to complex again and you'll get the exception. It's the second time you change to complex. I've created a ticket :-)

**Comment by dkayiwa** [comment]
Thanks for the detailed explanation. I was able to reproduce it in the old version. :)

**Comment by dkayiwa** [comment]
FWIW, i made a followup commit with the missing test: https://github.com/openmrs/openmrs-core/commit/eb822d22a99adc1f827864078a5d12b87d3ba2f0
I also tested the user interface to confirm all is well.

**Comment by lluismf** [comment]
Thanks !

**Pull request merged**
