### PR TITLE
TRUNK-4549 Error message description while creating a user

### PR DESCRIPTION
**Pull request by LordSriyan**
Added a new error message that contains all the details for a stronger password

### CODE REVIEW

**Comment by LordSriyan** [comment]
@dkayiwa : I rebased with "git pull --rebase upstream master".
https://github.com/LordSriyan/openmrs-core/commit/cfa1c2e7d4df6d3e40afc46ea317fd07d671a2aa
is the commit that I want to be merged.

**Comment by LordSriyan** [comment]
@dkayiwa : Can you merge the changes of my last commit(https://github.com/LordSriyan/openmrs-core/commit/cfa1c2e7d4df6d3e40afc46ea317fd07d671a2aa)?
Does it have conflicts?

**Comment by dkayiwa** [comment]
@LordSriyan yes it has conflicts. Can you squash these commits into one? And also look into the conflicts after pulling from upstream?

**Comment by dkayiwa** [comment]
@LordSriyan can you just create a new pull request?

**Pull request closed without merging**
