### PR TITLE
TRUNK-4868 Setting a deathdate does not call setDead()

### PR DESCRIPTION
**Pull request by tenas97**
## Description of what I changed
I  checked for the value of DeathDate passed to the setDeathDate method and called the setDead method with a true parameter if the DeathDate value was not null. I also included the test which was found in the issue's description to make sure it passed. For the objects that called setDeathDate method with a null value, i passed a new Concept() as a parameter to the object's setCauseOfDeath method.

## Issue I worked on
TRUNK-4868 Setting a deathdate does not call setDead()

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you see the tips about squashing commits into one, on this page? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by tenas97** [comment]
@dkayiwa Yes I saw the tip on squashing, but I lost track of the exact number of commits I made during my time on the issue, and since the git  squash command involved me including the number of prior commits, I thought it will be best not to run it.

**Comment by dkayiwa** [comment]
@tenas97 this pull request has more changes than needed for the ticket. Did you commit these accidentally? 😊

**Comment by tenas97** [comment]
@dkayiwa I apologize for that. The only changes i remember making were to the person.java class to include the setDead method to true in the setDeathDate method and a test and a test in the personTest.java class to check this change. I also made changes in the PatientServiceTest.java class to handle cases where the cause of death was not set, but the death date was, as this would give errors with respect to the changes i made in Person.java. I don't remember changing 43 files as shown by the pull request.

**Comment by tenas97** [comment]
There were also some minor commits made mostly concerning issues with the codacy test. At first it involved simple WhiteSpace around errors, and when i resolved them, the codacy test would record a pass and some time later show a failed test with very different issues from the previous test results. I am relatively new to version control, so maybe there's something wrong i may have done unknowingly.

**Comment by dkayiwa** [comment]
@tenas97 can you take a look at this and see if every change here was committed intentionally? https://github.com/openmrs/openmrs-core/pull/2210/commits/b54b5fdbddce19da6f4ffbac63ed8650539d38ea

**Comment by tenas97** [comment]
@dkayiwa  There's alot of commits there that are unintentional. Some classes I don't even think i opened. If it poses a problem I couldo close this pull request, update my fork and make the changes again. Then re-submit the pull request.

**Comment by dkayiwa** [comment]
@tenas97 yes close this pull request and create a new one.

**Comment by tenas97** [comment]
@dkayiwa  Ok, will do. Thanks alot

**Pull request closed without merging**
