### PR TITLE
GCI-9 Check bad Codepractices

### PR DESCRIPTION
**Pull request by itatriev**
1) Loggers should be **private static finale** and sharing name convention
2) Avoid **commented-out** lines of code
[Task's Ticket](https://issues.openmrs.org/browse/GCI-9)
[Melange-Task](http://www.google-melange.com/gci/task/view/google/gci2014/5384971845894144)

### CODE REVIEW

**Comment by k-joseph** [comment]
This Pull request says it is from unknown repository, hense making it not so easy to pull from it! any idea how i can do this devs?

**Comment by djazayeri** [comment]
I have never seen "unknown repository" before...

**Comment by k-joseph** [comment]
I think it is because@itatriev happened to delete his own fork for core after creating this PR

**Comment by itatriev** [comment]
@k-joseph Yeah, I did, because I had some problems with git and though "it would be more easy if I will REfork repo again". I wanted to refork it

**Comment by k-joseph** [comment]
Thanks @itatriev for your reply, we are merging gci work into openmrs-core soon and we need you to fork and open up a new Pull request that can allow me to pull from it to resolve conflicts if you would love us to have your work merged, 

Regards

**Comment by k-joseph** [comment]
Any way, i have added these commits by my self since we are out of time :+1:

**Comment by itatriev** [comment]
I'm sorry, I was not at home, should I do this right now or it's to late?

**Comment by k-joseph** [comment]
Closing this PR since it is included in: https://github.com/openmrs/openmrs-core/pull/1356

**Pull request closed without merging**
