### PR TITLE
TRUNK-2431: Refactor ORUR01Handler for performance improvement

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-2431

### CODE REVIEW

**Comment by gitcliff** [comment]
@ODORA0 have you checked out the travis failure?

**Comment by ODORA0** [comment]
I noticed and am working on that @gitcliff

**Comment by gitcliff** [comment]
cool man,

**Comment by dkayiwa** [comment]
@ODORA0 how does this solve the reported problem?

**Pull request closed without merging**
