### PR TITLE
TRUNK-5980: BaseContextSensitiveTest to allow further protected overrides.

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/TRUNK-5980
cc @mks-d @dkayiwa

### CODE REVIEW

**Comment by sherrif10** [comment]
Working on failing tests brought about security synk

**Comment by sherrif10** [comment]
Thanks @mks-d  unfortunately we may ignore current security/synk

**Comment by mks-d** [comment]
@dkayiwa I actually don't have the credentials to see what's behind those 'Details' for snyk, any idea?

**Comment by dkayiwa** [comment]
@mks-d i have just sent you an invitation.

**Comment by mks-d** [comment]
@dkayiwa mmm, still seeing this at https://app.snyk.io/org/openmrs/pr-checks/87309531-f24e-4d14-9047-e770057fa540:
drawing

**Comment by sherrif10** [comment]
Am also faced same restriction

**Review by mks-d — APPROVED** [review]
@dkayiwa @teleivo I'm good with this, but I'm not sure why all checks are not successful.

**Comment by sherrif10** [comment]
Thanks @mks-d  as we had ignored sync issues, Found this suggestion to fix this https://app.snyk.io/org/sherrif10/fix/6c7148e1-fcbe-4bcd-945b-a7a4a59617f2?utm_campaign=weekly_report&utm_source=OpenFixPRl), for those who have permissions , i think this can help however when it comes to hibernate validator version in core, we haven't yet supported version 6.0.19

**Comment by teleivo** [comment]
> Thanks @mks-d as we had ignored sync issues, Found this suggestion to fix this [Here ](https://app.snyk.io/org/sherrif10/fix/6c7148e1-fcbe-4bcd-945b-a7a4a59617f2?utm_campaign=weekly_report&utm_source=OpenFixPRl),)for those who have permissions , i think this can help however when it comes to hibernate validator version in core, we haven't yet supported version 6.0.19

hibernate-validator cannot simply be updated. we currently ignore the major update to 6.x see
https://github.com/openmrs/openmrs-core/blob/master/.github/dependabot.yml#L53-L55 for details

**Comment by teleivo** [comment]
> @dkayiwa @teleivo I'm good with this, but I'm not sure why all checks are not successful.

I think this coverage failure can be ignored. This has been annoying me and interested me for some time now. I haven't had the time to investigate this but I feel the coverage fluctuates even in PRs that do not touch code. Not sure why making an existing function protected would cause such a decrease. I think coverage should stay the same in that case.

For snyk I would say these security issues existed already. They are not related to your changes. Some might be actionable others are not where there is no patch yet available.

So I would say that the PR is alright from my point of view regarding the checks. We need to address these checks independently on another occasion. See if we can configure them so that they are more stable/only relating to the changed files. As checks that get ignored when failing are just noise.

**Comment by sherrif10** [comment]
Sure thanks @teleivo alot

**Comment by dkayiwa** [comment]
> mmm, still seeing this at

@mks-d did you receive an invitation to your mekomsolutions email address?

**Pull request merged**
