### PR TITLE
TRUNK-4523 - Person attributes are not being displayed when viewing a vo...

### PR DESCRIPTION
**Pull request by jkondrat**
...ided person

### CODE REVIEW

**Comment by dkayiwa** [comment]
@jkondrat reopen this after you have attached, on the ticket, a screenshot with the effects of your changes.

**Comment by dkayiwa** [comment]
@jkondrat the contract for Person.getAttributeMap() is not to include voided ones. So that contract should not be broken as you have done in this commit.

**Comment by jkondrat** [comment]
@dkayiwa In that case, should I introduce a new method for getting pa map including voided attributes?

**Comment by dkayiwa** [comment]
@jkondrat doesn't the existing Person.getAttributes() already do so?

**Comment by jkondrat** [comment]
@dkayiwa It does, but patient form iterates through all attribute types by name, so it is convenient to have them in a map form. See editPersonInfo.jsp:107

**Comment by dkayiwa** [comment]
@jkondrat then in that case you can add the new convenient method you were proposing.

**Pull request closed without merging**
