### PR TITLE
TRUNK-5528:Upgrade org.apache.lucene sub Libraries

### PR DESCRIPTION
**Pull request by jwnasambu**
Description of what I changed

I upgraded library org.apache.lucene sub Libraries

    org.apache.lucene:lucene-queries … 4.10.4 -> 5.3.1
    org.apache.lucene:lucene-queryparser … 4.10.4 -> 5.3.1

Issue I worked on

https://issues.openmrs.org/browse/TRUNK-5528

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you take a look at the travis build failure?

**Comment by mozzy11** [comment]
@jwnasambu  you may need to read the Migration Guide to handle the backward compatibilty in hislibrary https://lucene.apache.org/core/5_0_0/MIGRATE.html

**Comment by jwnasambu** [comment]
@mozzy11 thank you am actually reading hard through it.

**Comment by jwnasambu** [comment]
@dkayiwa I saw the failure and I was researching on the cause and this is my conclusion concerning Travis CI failure.  Lucene 5  by default only read indexes created with Lucene 5. To read and upgrade Lucene 4.x (4.10.4)indexes, I must add the lucene-backward-codecs.jar to the classpath.  for it is recommended to upgrade the old indexes with the IndexUpgrader tool, so as to remove the backward-codecs module from classpath to improve performance.

**Pull request closed without merging**
