### PR TITLE
TRUNK-5793: AllergyReaction Domain - Switching from Hibernate Mappings to Annotations

### PR DESCRIPTION
**Pull request by alinmihaila99**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5793

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by alinmihaila99** [comment]
Hi @Ruhanga ! I ran mvn clean install before creating the PR and after submitting it and it was successful. Do you have any ideas why here it failed?

**Comment by anshulbh9** [comment]
Hi @alinmihaila99 you can try running the project on local and check if the migrations are successfully running, it will be easier to debug the issue

**Comment by alinmihaila99** [comment]
> Hi @alinmihaila99 you can try running the project on local and check if the migrations are successfully running, it will be easier to debug the issue

Thanks, but I already ran on local and it was sucessful.

**Review by Ruhanga — CHANGES_REQUESTED** [review]
@alinmihaila99, can you resolve the merge conflicts here?

**Review by Ruhanga — APPROVED** [review]

**Pull request closed without merging**
