### PR TITLE
TRUNK-5725: upgrading hibernate validator from 5.4.3 to 6.1.2

### PR DESCRIPTION
**Pull request by helderjosue**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5725

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you successfully compile your changes before raising the pull request?

**Comment by helderjosue** [comment]
@dkayiwa Yes I did! But I was wondering when the CI checks are triggered to run, because the PR was created days ago.
I willl check all again

**Comment by dkayiwa** [comment]
Try starting openmrs with these compiled changes by running `mvn jetty:run` to see if you do not get any errors and the application starts successfully to be accessed via the browser.

**Comment by dkayiwa** [comment]
> But seems like the checks passed again

I rerurn the GitHub actions.

**Comment by dkayiwa** [comment]
Did you try starting openmrs with these changes by running mvn jetty:run from the webapp folder to see if you do not get any errors and the application starts successfully to be accessed via the browser?

**Comment by helderjosue** [comment]
Yes, after your recommendation on both PRs, I ran it successfully and accessed it on browser (running OMRS 2.7.x).

**Comment by helderjosue** [comment]
find attached some screenshots
Screenshot from 2024-04-02 22-32-23
Screenshot from 2024-04-02 22-48-53

**Review by dkayiwa — APPROVED** [review]

**Pull request merged**
