### PR TITLE
TRUNK-4744:Add Support for Open Web Apps

### PR DESCRIPTION
**Pull request by SandeepRaparthi1**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 can you always include the ticket number in your commit and pull request messages as advised at? http://go.openmrs.org/pull-request-tips

**Comment by dkayiwa** [comment]
Do you have any reason why you did not do this on the master branch as per our convention?

**Comment by SandeepRaparthi1** [comment]
@dkayiwa sorry i have included the ticket number now.Once we previously discussed the Rest compatibility with master branch (like creating a patient was not working fine) so we thought let us support 1.11.x as of now

**Comment by dkayiwa** [comment]
Are you trying to change the default location of module files when "owa.started" is true? If yes, i do not recommend this approach. I think your OWA implementation should be able to look at default module location instead of changing the core platform to extract modules in different places. Besides, the core platform should not be dependent on any module specifics. Does this make sense?

**Comment by SandeepRaparthi1** [comment]
@dkayiwa i do not intent to extract any of the modules code into a different location except for the Open web app code which will have a manifest.webapp(a json) folder in it.i just want to take that part code and store it at a different place.

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 why don't you do that within your module? Besides, core should not be aware of any specific module.

**Comment by SandeepRaparthi1** [comment]
@dkayiwa I tried that from my module but was not successful so went this approach of making changes to core which is the direct way of doing it.

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 did you ask your mentor for advice regarding how to do it from your module?
Or did you even try asking for advice from the developer community regarding the same?
Am sure there has to be a solution that does not require you to start making core dependent (aware of) your module.

**Comment by SandeepRaparthi1** [comment]
@dkayiwa i have discussed this with my mentor after their approval i have created the ticket.if this is not acceptable then i shall get back and try again doing that from my module.

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 feel free to engage the wider developer community on talk.

**Comment by SandeepRaparthi1** [comment]
@dkayiwa Okay :)

**Comment by dkayiwa** [comment]
Because of the comments above, am closing this.

**Pull request closed without merging**
