### PR TITLE
1.11.x  TRUNK-4742 Add support for setting test database credentials externally

### PR DESCRIPTION
**Pull request by fanyui**
Backported TRUNK-4742 to branch 1.11.x 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-4742

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you squash the commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by fanyui** [comment]
I have squash  the commits into one

**Comment by fanyui** [comment]
I hava Finish squashing the commits

**Comment by dkayiwa** [comment]
@fanyui can you look into the above travis failure?

**Comment by dkayiwa** [comment]
@fanyui are you still working on this?

**Comment by fanyui** [comment]
Hi @dkayiwa  I'd love to finish it up but i've looked at the logs and am not getting a concrete understanding of what it demands. A little explanation will be appreciated.

**Comment by dkayiwa** [comment]
@fanyui when you compile locally, is it all successful?

**Comment by fanyui** [comment]
yes and all tests pass

**Comment by dkayiwa** [comment]
The ticket status shows in progress. Are you still doing more work on this?

**Comment by fanyui** [comment]
Not currently I forgot updating it.

**Comment by fanyui** [comment]
how should i get pass the travis build failure

**Comment by dkayiwa** [comment]
@fanyui do you have a reason for doing this on the 1.11.x branch instead of master?

**Comment by fanyui** [comment]
The changes were already on master and i was  charged only in backporting them to those branches. that didn't have the changes.

**Comment by dkayiwa** [comment]
@fanyui can you point me to the original commit that you are copying from?

**Comment by fanyui** [comment]
@dkayiwa  original commit for the backporting are found here. 
https://github.com/openmrs/openmrs-core/commit/d8ca28dc10f815137026755d71205620b51bf1a4
https://github.com/openmrs/openmrs-core/commit/072a4ea1fe9c04fdd998116ad9777945b5ead10a

**Comment by suthagar23** [comment]
@fanyui Can you please update your commit again to check the Travis failure here (No need any modifications, simply fast forward enough for this case?

**Comment by dkayiwa** [comment]
Closing this because the author abandoned it

**Pull request closed without merging**
