### PR TITLE
TRUNK-367: Create a German messages.properties

### PR DESCRIPTION
**Pull request by STheis**
German translation of messages.properties

### CODE REVIEW

**Comment by dkayiwa** [comment]
@STheis can you squash these commits into one?

**Comment by STheis** [comment]
I hope, I made it in the correct way. I'm new with git.

**Comment by dkayiwa** [comment]
@STheis no you have not. Did you read the link i gave above?
Did you also see? https://wiki.openmrs.org/display/docs/Using+Git

**Comment by STheis** [comment]
yes, i have read the links. But is not easy. I found my first issue. I worked with notepad++ to squash the commits and this file was sychronized to patch-1. If it dont work. I close this pull request and create a new one with the newest translation.

**Comment by dkayiwa** [comment]
@STheis if you fail, ping me on IRC.

**Comment by STheis** [comment]
I have made a new one under #1454

**Pull request closed without merging**
