### PR TITLE
TRUNK-3382 Modify provider.getName() method so that it only looks at provider.person.name

### PR DESCRIPTION
**Pull request by alexei-grigoriev**
Creating a new pull request. Please review
https://issues.openmrs.org/browse/TRUNK-3382

Sorry for that many broken PRs. Had some problems with rebasing. I hope I get rid of it finally.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@alexei-grigoriev can you squash these commits into one?
On the JIRA ticket, remember to also attach screenshots with effects of your changes. One screenshot with the list of providers and a second one with one of the providers selected.

**Comment by alexei-grigoriev** [comment]
But on provider list nothing changed. 
Should I put a full screens hot or a changed region is better?

**Comment by alexei-grigoriev** [comment]
Before squashing I've made a change to providerForm.jsp. Please review it too.

**Comment by alexei-grigoriev** [comment]
The build has failed. But I am sure it caused by some random problem not related to my changes. As mentioned in https://botbot.me/freenode/openmrs/msg/36890023/ there are some other builds failing on the ModuleActivatorTest.
I have no idea how to deal with it.

**Comment by dkayiwa** [comment]
@alexei-grigoriev since you changed the provider domain object, it may have effects on the provider list. So you need to also attach a screenshot with the list of providers. This screen show should some some providers listed to confirm that your changes did not break something. Does this make sense?

**Comment by alexei-grigoriev** [comment]
@dkayiwa Sure. The screen shot is attached to the issue.

**Pull request merged**
