### PR TITLE
GCI-190

### PR DESCRIPTION
**Pull request by sengsockhian**
https://issues.openmrs.org/browse/GCI-190

### CODE REVIEW

**Comment by sengsockhian** [comment]
@ykarim thank you! the issue referenced line 33 but i noticed line 33 is already private static

**Comment by gayanW** [comment]
@sengsockhian Yeah it is already `private static` and that's fine. As @ykarim pointed out, your branch name need to be changed.

This might help:
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by ykarim** [comment]
Also shouldn't the log variable be `final` too?

**Comment by gayanW** [comment]
@ykarim oh yeah. I missed that.

**Pull request closed without merging**
