### PR TITLE
Revert "maven(deps): bump hibernate-validator from 5.4.0.Final to 6.1.5.Final"

### PR DESCRIPTION
**Pull request by dkayiwa**
Reverts openmrs/openmrs-core#3448

### CODE REVIEW

**Comment by dkayiwa** [comment]
Reverted this for now, because it prevents the reference application from starting because of this error: `java.lang.NoClassDefFoundError: javax/el/ELManager`

**Comment by teleivo** [comment]
thank you @dkayiwa , I will exclude any updates past 5.x then for now in the dependabot yml

**Comment by teleivo** [comment]
ignored updates for now at https://github.com/openmrs/openmrs-core/commit/ef22f636f65fe429d88a823ed20c6747489393f6

**Comment by dkayiwa** [comment]
Thanks @teleivo 👍

**Pull request merged**
