### PR TITLE
TRUNK-3253: Added Junit tests for searching on voided patients

### PR DESCRIPTION
**Pull request by taher44**
## Two failures 
I believe I am expecting the correct behavior of the method, but the actual output was not as I expected. Tests that failed: 
1. getPatients_shouldNotGetPatientsWithMatchModeAnywhereAndVoidedTrueIsPassed_SignatureNo2
2. getPatients_shouldNotGetPatientsWithMatchModeStartAndVoidedTrueIsPassed_SignatureNo2

## Description of what I changed
1. Added Junit tests that test __HibernatePatientDAO#getPatients(String, boolean, Integer, Integer)__ and __HibernatePatientDAO#getCountOfPatients(String, boolean)__ methods on the following scenarios:
    1. Searching for existing voided patients by name
    2. Searching for non-existing voided patients by name
    3. Searching for existing voided patients by identifier
    4. Searching for voided patients by attributes
    5. Searching for voided patients with match mode __start__
    6. Searching for voided patients with match mode __anywhere__

2. Fixed tests that have __signatureNo2__ in their method names to make them test __HibernatePatientDAO#getPatients(String, boolean, Integer, Integer)__

## Issue I worked on
see https://issues.openmrs.org/browse/TRUNK-3253

### CODE REVIEW

**Comment by dkayiwa** [comment]
@taher44 are you still working on this?

**Comment by taher44** [comment]
@dkayiwa I believe I am expecting the correct behavior of the method, but the actual output was not as I expected. Can you check the two scenarios that failed and let me know if there is any change that needs to be made?

Tests that failed:

1. **getPatients_shouldNotGetPatientsWithMatchModeAnywhereAndVoidedTrueIsPassed_SignatureNo2**
2. **getPatients_shouldNotGetPatientsWithMatchModeStartAndVoidedTrueIsPassed_SignatureNo2**

**Comment by dkayiwa** [comment]
First of all, did you get a chance to look at the travis build failure log?

**Comment by dkayiwa** [comment]
@taher44 did you see my comment above?

**Comment by dkayiwa** [comment]
@taher44 ping me to reopen this when you resume working on it.

**Pull request closed without merging**
