### PR TITLE
Change sonar URL

### PR DESCRIPTION
**Pull request by cintiadr**
.. as it won't be on the same machine as CI
Related to ITSM-4042, migrating CI to a new server.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @cintiadr 😊

**Comment by dkayiwa** [comment]
@cintiadr is this in any way related to? https://ci.openmrs.org/download/TRUNK-MASTER-JOB1/build_logs/TRUNK-MASTER-JOB1-1735.log

**Comment by cintiadr** [comment]
It certainly is, @dkayiwa . 

```
https://ci.openmrs.org/sonar/api/server/version
```

I just thought I had actually fixed that. Will check.

**Comment by cintiadr** [comment]
Fixed: https://ci.openmrs.org/browse/TRUNK-MASTER-JOB1-1736

It was missing a fix to the bamboo agents themselves.

**Comment by dkayiwa** [comment]
Thanks @cintiadr 👍

**Pull request merged**
