### PR TITLE
TRUNK-4658 "Correctness - Possible null pointer dereference in method on...

### PR DESCRIPTION
**Pull request by tomaszmueller**
... exception path"

### CODE REVIEW

**Comment by tomaszmueller** [comment]
@rkorytkowski  https://issues.openmrs.org/browse/TRUNK-4658

**Comment by dkayiwa** [comment]
@tomaszmueller this pull request has merge conflicts. Do you mind pulling the latest changes from upstream and try again?

**Comment by tomaszmueller** [comment]
@dkayiwa I updated the pull request. Did it help?

**Comment by dkayiwa** [comment]
@tomaszmueller can you always include the sonar issue url on the ticket?

**Comment by tomaszmueller** [comment]
@dkayiwa updated

**Comment by dkayiwa** [comment]
@tomaszmueller it still did not work. Can you just create a new pull request?

**Pull request closed without merging**
