### PR TITLE
Disable validation via a global property

### PR DESCRIPTION
**Pull request by rcrichton**
See https://issues.openmrs.org/browse/TRUNK-4626

(@dkayiwa new PR due to force push to branch)

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rcrichton i see two commits in this pull request. Was that intentional? :)

**Comment by dkayiwa** [comment]
@rcrichton ping :)

**Comment by rcrichton** [comment]
The reason is that git doesn't allow me to squash merge commits.

**Comment by dkayiwa** [comment]
@rcrichton does this disable all validations? Or some of it?

**Comment by rcrichton** [comment]
I believe it stops all validation, it seems pretty much all places I could find use the admin service to validate.

**Comment by dkayiwa** [comment]
@rcrichton is the merge also part of the pull request? It seems to contain more than it should for the pull request. :)

**Comment by rcrichton** [comment]
@dkayiwa the merge does nothing more than bring my branch up to date with openmrs-core/master. If you look at the diff you will see all the effective change this PR will make: https://github.com/openmrs/openmrs-core/pull/1494/files

What would you like me to do here? Start from scratch with a new branch from the latest from master and recreate my changes so there isn't a merge commit?

**Comment by dkayiwa** [comment]
Would it take you a lot of time to do that?

On Wed, May 13, 2015 at 10:12 AM, Ryan Crichton <notifications@github.com>
wrote:

> @dkayiwa <https://github.com/dkayiwa> the merge does nothing more than
> bring my branch up to date with openmrs-core/master. If you look at the
> diff you will see all the effective change this PR will make:
> https://github.com/openmrs/openmrs-core/pull/1494/files
>
> What would you like me to do here? Start from scratch with a new branch
> from the latest from master and recreate my changes so there isn't a merge
> commit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1494#issuecomment-101543102>
> .
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by rcrichton** [comment]
It would take to long cos this is a small change. Is the merge commit that much of an issue?

**Comment by rcrichton** [comment]
Hey @dkayiwa, I'm going to recreate the PR from the latest in master...

**Comment by dkayiwa** [comment]
Closing because a new pull request was created https://github.com/openmrs/openmrs-core/pull/1503

**Pull request closed without merging**
