### PR TITLE
TRUNK-6013 - Upgrade to Liquibase 4

### PR DESCRIPTION
**Pull request by ibacher**
[TRUNK-6013 - Upgrade to Liquibase 4](https://issues.openmrs.org/browse/TRUNK-6013)

## Description of what I changed

Upgrades Core to using Liquibase 4. This should resolve the issue mentioned [here](https://talk.openmrs.org/t/typecasting-error-during-openmrs-setup/31816) and allow us to continue updating the MySQL driver.

Tested against both Jetty and Tomcat.

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ibacher wouldn't it be easier to troubleshoot possible problems if your separate these two upgrades?

**Comment by ibacher** [comment]
@dkayiwa Sure! I can reduce this to just upgrading Liquibase. I just figured I'd do the MySQL as well since this seemed to be the blocker.

**Comment by corneliouzbett** [comment]
> @ibacher wouldn't it be easier to troubleshoot possible problems if you separate these two unrelated upgrades?

To some extent, there are related. Upgrading liquibase has to happen first. Tried upgrading the MySQL connector, run into this 
```java
java.lang.ClassCastException: class java.time.LocalDateTime cannot be cast to class java.lang.String (java.time.LocalDateTime and java.lang.String are in module java.base of loader 'bootstrap')
amrs-upgrade           | 	at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:328) ~[liquibase-core-3.10.2.jar:?]
amrs-upgrade           | 	at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:66) ~[liquibase-core-3.10.2.jar:?]
amrs-upgrade           | 	at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:297) ~[liquibase-core-3.10.2.jar:?]
```
Which call for upgrading liquibase.

**Comment by dkayiwa** [comment]
The upgrade of liquibase does not require that of mysql connector. But the upgrade of mysql connector requires that of liquibase. So i believe we can do the mysql connector upgrade as a followup in its own pull request. Just like we have done for hibernate and spring. On another note, you raise a very good point that if we have already upgraded liquibase, we would not have had to revert this: https://github.com/openmrs/openmrs-core/pull/3681  😊

**Comment by ibacher** [comment]
I missed that we weren't actually loading the Liquibase extensions when doing my testing, so leaving this in draft until I can retest the changes.

**Comment by jonathandick** [comment]
@ibacher any updates on this? It seems this a locker for us at AMPATH as well.

**Comment by ibacher** [comment]
Ok self review: successfully updated from RefApp 2.12.0-SNAPSHOT on core 2.4.0 -> core 2.5.0.

**Review by corneliouzbett — APPROVED** [review]
Upgraded successfully!

**Pull request merged**
