### PR TITLE
Updated message.properties

### PR DESCRIPTION
**Pull request by Parth59**
@isears 
Added required error message for EMPT70.
Kindly refer to the following PR for all relevant details :- https://github.com/openmrs/openmrs-module-legacyui/pull/164

### CODE REVIEW

**Comment by Parth59** [comment]
I guess similar changes needs to be done for 2.3.x branch. Is my direction correct @isears  ?
@sherrif10

**Comment by HerbertYiga** [comment]
thanks @Parth59  make a single pr for these changes

**Comment by sherrif10** [comment]
Sure one single pr is fair enough

**Comment by Parth59** [comment]
Closing this issue as I have found out a local fix in legacyui itself.

**Pull request closed without merging**
