### PR TITLE
Switching from Hibernate Mappings to Annotations - Location Domain

### PR DESCRIPTION
**Pull request by mherman22**
## Description of what I changed

I changed the location domain' reliance on xml mappings to use the more understandable JPA annotations. I used annotations like @Column, @Entity @Table @OneToMany and many others as can be seen in the changes in this pull request.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5808

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mherman22 did you see the above failing build?

**Comment by mherman22** [comment]
> @mherman22 did you see the above failing build?

I am looking into it, thanks! @dkayiwa 

 Though it passes locally with the `mvn clean package`

**Comment by tendomart** [comment]
`ValidateHibernateMappingsDatabaseIT.shouldValidateHibernateMappings:74->buildSessionFactory:101 » SchemaManagement Schema-validation: missing table [location_location_attribute]`

**Comment by mherman22** [comment]
@dkayiwa kindly review

**Comment by mherman22** [comment]
@dkayiwa i believe now i have met most(if not all) of the requirements.

**Comment by dkayiwa** [comment]
Why just most instead of all?

**Comment by mherman22** [comment]
> Why just most instead of all?

You could help me point me to which one I've missed :🙂

**Comment by dkayiwa** [comment]
Did you see number 11?

**Comment by mherman22** [comment]
> Did you see number 11?

@dkayiwa I saw it and I've done the needful. Thanks

**Pull request merged**
