### PR TITLE
TRUNK-5213: @OpenmrsProfile loads Spring resources conditionally based on missing module(s)

### PR DESCRIPTION
**Pull request by mks-d**
## Description
`@OpenmrsProfile` loads Spring resources conditionally based on missing module(s)
## Related Issue

https://issues.openmrs.org/browse/TRUNK-5213

## Checklist:

- [x] My pull request only contains one single commit.
- [x] My pull request is based on the latest master branch
  `git pull --rebase upstream 1.10.x`.
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mks-d** [comment]
Hi @dkayiwa , just wondering if you had a chance to look at this PR? In particular as to why `OpenmrsProfileExcludeFilterWithModulesTest` is failing.

**Comment by dkayiwa** [comment]
@mks-d put the test in the web instead of api sub project and tell me if it passes.

**Comment by mks-d** [comment]
Thanks @dkayiwa , that worked. Here is the updated PR for TRUNK-5213 on 1.10.x.

**Comment by mks-d** [comment]
Thanks @dkayiwa for merging this in. What was going on with TravisCI though?

**Comment by dkayiwa** [comment]
Regarding which error?

**Pull request merged**
