### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by devmalik7**
PULL_REQUEST_TEMPLATE.md

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by devmalik7** [comment]
Thank you reviewers.

**Comment by devmalik7** [comment]
Thank you

**Comment by HerbertYiga** [comment]
@devmalik7  did you get a chance to look at this: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by devmalik7** [comment]
WOW its`s super helpful.
Thank you so much.

**Comment by teleivo** [comment]
@devmalik7 thank you for helping out 😄  Can you please let us know why we should change the template.

**Comment by devmalik7** [comment]
> 
> 
> @devmalik7 thank you for helping out smile Can you please let us know why we should change the template.

@teleivo well in order to get ready for this changing world.

**Comment by teleivo** [comment]
@devmalik7 I don't know what you mean by that

**Comment by devmalik7** [comment]
@teleivo Hey i have few quarries to ask. can you please share your email.

**Comment by teleivo** [comment]
> @teleivo Hey i have few quarries to ask. can you please share your email.

You are welcome to ask your questions here or at talk.openmrs.org where more people of the openmrs community are able to help

**Pull request closed without merging**
