### PR TITLE
[GCI-142] Replaced "==" and "!=" with "===" and "!==".

### PR DESCRIPTION
**Pull request by mee-kell**
## Description of what I changed

I replaced "==" and "!=" with "===" and "!==" operators throughout openmrs-core. The == and != operators do type coercion before comparing values. This is bad because it can mask type errors. It is best to always use the side-effect-less === and !== operators instead. 

I tried to address all issues of this type, as flagged by Sonar. (Most of these issues were in the openmrs-webapp module.)

## Issue I worked on

[Here](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&open=AWCS0QlIvsycEPA9_R3D&resolved=false&rules=javascript%3AEqEqEq&severities=BLOCKER%2CMAJOR&types=BUG%2CCODE_SMELL) is the list of Sonar issues that I worked on.
See https://issues.openmrs.org/browse/GCI-142

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by MrUbaidUllahZahid** [comment]
Thank you @mavrk for suggesting changes, I've resolved all the issues and squashed all the commits into 1 :)

**Comment by mee-kell** [comment]
> Thank you @mavrk for suggesting changes, I've resolved all the issues and squashed all the commits into 1 :)

@MrUbaidUllahZahid Sorry, I think you've commented on the wrong pull request by accident.

**Comment by MrUbaidUllahZahid** [comment]
yes you are write sorry also for me

**Comment by dkayiwa** [comment]
Since jquery is an external library, changes to it should go to its original source.

**Pull request closed without merging**
