### PR TITLE
TRUNK-5801: EncounterType Domain - Switching from Hibernate Mappings to Annotations

### PR DESCRIPTION
**Pull request by ibacher**
## Description of what I changed

Reopened version of #3259

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5801

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by ibacher** [comment]
@alinmihaila99 I've reverted the commit and reopened this PR to track the changes.

**Comment by alinmihaila99** [comment]
I will make some changes and I will add it here. Thanks!

**Comment by alinmihaila99** [comment]
Hi @ibacher  @dkayiwa @Ruhanga I made the changes you suggested for this PR. Can you have a look at this?

**Comment by dkayiwa** [comment]
@alinmihaila99 have you first of all tested these changes and confirmed that all problems reported on the ticket are now resolved?

**Comment by alinmihaila99** [comment]
Oh, sorry. I forgot about this, I will update it soon. Thanks for reminder @Ruhanga

**Comment by alinmihaila99** [comment]
@Ruhanga what do you think about this failure? Can you have a look?

**Review by Ruhanga — APPROVED** [review]

**Comment by tendomart** [comment]
is this still needed open ?

**Pull request closed without merging**
