### PR TITLE
TRUNK-5115-new-3:Replace use of conditional logging with slf4j parame…

### PR DESCRIPTION
**Pull request by gracebish**
…terized messages

**Pull request title** 
TRUNK-5115-new-3: Replace use of conditional logging with slf4j parameterized messages
TRUNK-JiraIssueNumber: JiraIssueTitle
TRUNK-5115: Replace use of conditional logging with slf4j parameterized messages
**Description of what I changed**
Replace use of conditionals which are aimed at preventing to construct the debug message with slf4js parametrized messages
 **Issue I worked on**
https://issues.openmrs.org/browse/TRUNK-5115

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by gracebish** [comment]
@dkayiwa There are more changes for review. Would you feel comfortable to advise on how to deal with the unfinished files? I have been making commits for 5 files each time and there is still some more work on the following link. https://github.com/openmrs/openmrs-core/search?q=log.isDebugEnabled%28%29&unscoped_q=log.isDebugEnabled%28%29%20TRUNK-5115

**Comment by dkayiwa** [comment]
For each pull request that you create, add a link to it on the jira ticket.

**Comment by gracebish** [comment]
@dkayiwa, the java 11 test failed to build. Kindly advise on the way forward.

**Comment by dkayiwa** [comment]
That is a flaky test that randomly fails. I have just rerun the travis build.

**Pull request merged**
