### PR TITLE
Trunk-5651:Add previous order group to order group

### PR DESCRIPTION
**Pull request by gitcliff**
link:https://issues.openmrs.org/browse/TRUNK-5651
Added previous order group to order group

### CODE REVIEW

**Comment by dkayiwa** [comment]
@gitcliff are you still working on this?

**Comment by gitcliff** [comment]
YES @dkayiwa, am working on this, resolving the merge conflicts that seem to come from the api/src/main/resources/liquibase-update-to-2.3.xml file, though still trying to get around what @samuelmale meant by what changes he requested of the test coverage?

**Comment by mozzy11** [comment]
@gitcliff  have u seen the merge comflicts ?

**Comment by mozzy11** [comment]
can you also write test units?

**Comment by gitcliff** [comment]
@mozzy11 see your comments and would love to respond on them but am still blocked by the unit test failure which is preventing me from having a successful build

**Comment by mozzy11** [comment]
@gitcliff  , the error is a windows enviroment specific problem. Before we adress it , just ignore that that test for now

**Comment by gitcliff** [comment]
@mozzy11 @samuelmale @dkayiwa i resolved the conflicts and also added unit tests

**Comment by dkayiwa** [comment]
@gitcliff did you see the merge conflicts?

**Comment by gitcliff** [comment]
@dkayiwa I fixed the merge conflicts

**Comment by gitcliff** [comment]
am closing this pr for a new one because of the branch conflicts during the conflicts resolving

**Pull request closed without merging**
