### PR TITLE
TRUNK-5704 Deleted the ShouldTaglet class in openmrs-tools and removed the reference to it from the main POM.

### PR DESCRIPTION
**Pull request by kangbreder**
TRUNK-5704
Deleted the ShouldTaglet class in openmrs-tools and removed the reference to it from the main POM.

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5704

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by CaptainDaVinci** [comment]
The issue tracker shows this ticket as unassigned, can you please claim the issue to let others know about the status of this ticket.

**Comment by ibacher** [comment]
@kangbreder Have you seen our [pull request tips](https://wiki.openmrs.org/display/docs/Pull+Request+Tips)? Please make sure to name this PR and your commit accordingly.

**Comment by Wandji69** [comment]
@kangbreder please update the ticket page with the link of this PR. All so the issues say for all modules since the is another issue that directs the removal of the same instance from the openmrs-tool please look in to as well.

**Comment by varung-31** [comment]
Please give a small description of the issue in the PR name.

**Comment by kangbreder** [comment]
> @kangbreder Please give a small description of the issue in the PR name.

I have done that @varung-31

**Comment by kangbreder** [comment]
> @kangbreder please update the ticket page with the link of this PR. All so the issues say for all modules since the is another issue that directs the removal of the same instance from the openmrs-tool please look in to as well.

@Wandji69 Please can i have a link to the other issues. Is openmrs-core thesame as openmrs tools? I

> @kangbreder Have you seen our [pull request tips](https://wiki.openmrs.org/display/docs/Pull+Request+Tips)? Please make sure to name this PR and your commit accordingly.

I have done that @ibacher

**Comment by ibacher** [comment]
@kangbreder One last thing: can you change the text of the commit itself to have the ticket number in it? This should be as easy as (from the directory containing your branch):

```
git commit --amend -m "TRUNK-5704: Deleted the ShouldTaglet class"
git push --force
```

Once that's done, this is good to go!

**Comment by kangbreder** [comment]
@ibacher I have done that.

**Comment by ibacher** [comment]
@kangbreder Thanks! I've merged this into the tracking branch for this ticket!

**Comment by kangbreder** [comment]
Thank you @ibacher

**Pull request merged**
