### PR TITLE
TRUNK-4935: Removed TODO line at Line 459 of ProgramWorkflowService.java

### PR DESCRIPTION
**Pull request by tendomatGitHub**
https://issues.openmrs.org/browse/TRUNK-4935

TRUNK-4935: Removed TODO line at Line 459 of ProgramWorkflowService.java

I removed the  TODO line at Line 459 of ProgramWorkflowService.java.Please review my work and get back to me thanks

### CODE REVIEW

**Comment by dkayiwa** [comment]
@tendomatGitHub the only line to be removed was the one having the TODO.

**Comment by tendomatGitHub** [comment]
aah what a mess so ill do it again from the master branch

**Comment by tendomatGitHub** [comment]
aah trouble ill try  to change again

**Comment by dkayiwa** [comment]
Can you squash these commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by tendomatGitHub** [comment]
Alright let me see how to do that shortly

**Comment by tendomatGitHub** [comment]
let me go for my next challenge

**Comment by dkayiwa** [comment]
@tendomatGitHub congs for your first pull request merged. 👍 
Yes the more you will go is the more fun! 💯

**Pull request merged**
