### PR TITLE
GSoC Project 2019: Patient Search Criteria (Index of Person class is added) 

### PR DESCRIPTION
**Pull request by Reyano132**
This PR is part of my GSOC 2019 project.
https://wiki.openmrs.org/display/projects/Patient+Search+Criteria
I made this PR, so my mentor can easily see what changes I did in openmrs core
Issue: https://issues.openmrs.org/browse/TRUNK-5422

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you include the ticket id in your commit message? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Reyano132** [comment]
Sorry sir, I forget to add a description  in my PR. Actually, this PR is part of my GSoC project. I made this, so my mentor can easily verify the changes in code.

**Comment by dkayiwa** [comment]
@Reyano132 did you get your mentor to look at this?

**Comment by Reyano132** [comment]
Yes sir

**Comment by gitcliff** [comment]
@Reyano132  kindly squash your commits into one and are you able to build successfully on your local IDE with mvn clean install?

**Comment by Reyano132** [comment]
@gitcliff sir, I squash my commits and yes sir, I able to build the project in my IDE with mvn clean install. It will take more time as I added an index to Person class.

**Comment by dkayiwa** [comment]
The link to the ticket does not look correct.
Can you also include the ticket id in your commit?

**Comment by Reyano132** [comment]
Sir, I change the description of PR

**Comment by dkayiwa** [comment]
Can you add a link to the ticket as required at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request closed without merging**
