### PR TITLE
TRUNK-5068: Add tests to ProgramWorkflowService

### PR DESCRIPTION
**Pull request by farAtGitHub**
## Description of what I changed
**Test classes:**
ProgramWorkflowServiceUnitTest (<-- this file is missing, it got lost while trying time and again to get rid of the formatting changes, argh)
ProgramWorkflowServiceTest

**Test data:**
ProgramAttributesDataset.xml

**Please note**
This is only a "preview" of the pull request to demonstrate
https://issues.openmrs.org/browse/TRUNK-5658
Running ProgramWorkflowServiceTest will result in
```
Tests in error: 
  ProgramWorkflowServiceTest.getPatientProgramByAttributeNameAndValue_shouldReturnPatientProgram:846 » QuerySyntax
```
since the bug described in not yet fixed.

**Please note also**
The formatting noise introduced by the constant reformatting has not yet been removed (or yes, it has about 10 times).
Actually it would make sense to let the build correct the format instead of reintroducing the poor formatting committed previously just for the convenience of the reviewer. It is really tedious and there are diff tools capable of ignoring whitespace changes.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5068

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
Unfortunately as I spend a hours fighting with recurring forced formatting
  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dilanthas** [comment]
@farAtGitHub There are lots of formatting changes in your pull request. Lots of empty lines are added. It would be easy to review if you can remove them

**Comment by farAtGitHub** [comment]
@dilanthas Have you read the "please notes"? One clearly stating that the formatting noise is **not yet** removed. There is no sense in doing it over and over again.
And are you aware that the mandatory configuration of the IDE keeps reintroducing those formatting changes?
Please explain to me in simple words how using the mandatory configuration **and** not introducing forced formatting changes is **not** a contradiction. And how it is supposed to be avoided.
And while you are at it: Please explain why you cannot use the 'Hide whitespace changes' functionality of GitHub. It is 3 mouse clicks!
And where were you when the wrong formatting was introduced? Does it now have to stay in the code for ever? Future developers struggling for ever?
Please explain!
Especially the bit about not using the 'Hide whitespace changes' functionality.

**Comment by dilanthas** [comment]
> @dilanthas Have you read the "please notes"? One clearly stating that the formatting noise is **not yet** removed. There is no sense in doing it over and over again.
> And are you aware that the mandatory configuration of the IDE keeps reintroducing those formatting changes?
> Please explain to me in simple words how using the mandatory configuration **and** not introducing forced formatting changes is **not** a contradiction. And how it is supposed to be avoided.
> And while you are at it: Please explain why you cannot use the 'Hide whitespace changes' functionality of GitHub. It is 3 mouse clicks!
> And where were you when the wrong formatting was introduced? Does it now have to stay in the code for ever? Future developers struggling for ever?
> Please explain!
> Especially the bit about not using the 'Hide whitespace changes' functionality.



> @dilanthas Have you read the "please notes"? One clearly stating that the formatting noise is **not yet** removed. There is no sense in doing it over and over again.
> And are you aware that the mandatory configuration of the IDE keeps reintroducing those formatting changes?
> Please explain to me in simple words how using the mandatory configuration **and** not introducing forced formatting changes is **not** a contradiction. And how it is supposed to be avoided.
> And while you are at it: Please explain why you cannot use the 'Hide whitespace changes' functionality of GitHub. It is 3 mouse clicks!
> And where were you when the wrong formatting was introduced? Does it now have to stay in the code for ever? Future developers struggling for ever?
> Please explain!
> Especially the bit about not using the 'Hide whitespace changes' functionality.

@farAtGitHub I have reviewed your pull request and provided my feedback according to my understanding and what i think is best . That does not mean you must make these changes in the code. If others think this is ok, then they will merge it. 

Also please go through https://wiki.openmrs.org/display/docs/Pull+Request+Tips . It says the pull request should only contain the changes relevant to the jira you are working on. The ticket that you are working on is not about formatting the unformatted code. If you are concern about the unformatted code in the project , Its better to create a separate jira issue and work on it.

IDE does not force you to format the code unless you have set the auto formatting option in the IDE when committing the code.  You can always un-tick that option and manually format the code which you have changed only.

Its not about me viewing your changes in git without the white space. Its about flooding the git history with some unwanted changes.

**Comment by farAtGitHub** [comment]
> @farAtGitHub I have reviewed your pull request and provided my feedback according to my understanding and what i think is best . That does not mean you must make these changes in the code. If others think this is ok, then they will merge it.
> 
> Also please go through https://wiki.openmrs.org/display/docs/Pull+Request+Tips . It says the pull request should only contain the changes relevant to the jira you are working on. The ticket that you are working on is not about formatting the unformatted code. If you are concern about the unformatted code in the project , Its better to create a separate jira issue and work on it.
> 
> Im not sure whats the IDE you are using but most IDE does not force you to format the code unless you have set the auto formatting option in when committing the code. You can always un-tick that option and manually format the code which you have changed only.
> 
> Its not about me viewing your changes in git without the white space. Its about flooding the git history with some unwanted changes.

I'm concerned about wasting endless time in undoing changes that are introduced by complying with the Developer How To...
`https://wiki.openmrs.org/display/docs/Developer+How-To+Setup+And+Use+Eclipse?preview=/3346087/222593504/Save1.jpg#space-menu-link-content`

Still, disabling auto-formatting during save doesn't help, neither does changing the formatter settings. 
And then there is also
```
         <plugin>
            <groupId>com.googlecode.maven-java-formatter-plugin</groupId>
            <artifactId>maven-java-formatter-plugin</artifactId>
            <executions>
               <execution>
                  <goals>
                     <goal>format</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
```
But if that has any effect I couldn't say because of Eclipse constantly formatting on save.
Bad luck.

**Pull request closed without merging**
