### PR TITLE
Trunk 4727 | Adding new birthtime column in person table.

### PR DESCRIPTION
**Pull request by chethanTw**
https://issues.openmrs.org/browse/TRUNK-4727

### CODE REVIEW

**Comment by dkayiwa** [comment]
@chethanTw can you first pull changes from upstream and then add in these changes? That way your pull request will not have this merge that i see. It will have only the changes that are for this ticket.

**Comment by dkayiwa** [comment]
@chethanTw did you see the above comment?

**Comment by chethanTw** [comment]
@dkayiwa I saw the comment and made the changes and the merge is no more existing.

**Comment by dkayiwa** [comment]
@chethanTw thanks! Do you mind squashing these commits into one?

**Comment by chethanTw** [comment]
@dkayiwa Sure. I will do that.

**Comment by chethanTw** [comment]
@dkayiwa I squashed the commits. Thanks :)

**Comment by chethanTw** [comment]
@dkayiwa I have done the suggested changes.. Should I put a new commit or squash it with existing one?

**Comment by dkayiwa** [comment]
You can squash with the existing one.

On Thu, Jun 11, 2015 at 10:25 AM, Chethan A <notifications@github.com>
wrote:

> @dkayiwa <https://github.com/dkayiwa> I have done the suggested changes..
> Should I put a new commit or squash it with existing one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1509#issuecomment-111024900>
> .
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by dkayiwa** [comment]
@chethanTw whenever you will be done with this, remember to hit the "Request Code Review" button on the JIRA ticket.

**Comment by chethanTw** [comment]
@dkayiwa Sorry for the late reply on this. I have renamed the getBirthtime() to getBirthDateTime() and created a new getter which returns just birthtime.

**Comment by alexei-grigoriev** [comment]
Java files are with wrong formatting. 'mvn package' getting them changed by formatting. Could You please check it?

**Comment by dkayiwa** [comment]
Are you referring to master? Or some other branch? I have just checked master and all seems to be well. For the 1.11.x branch, i have committed: https://github.com/openmrs/openmrs-core/commit/02e50266ba0866ffef62ad4d640b830297af5703

**Comment by alexei-grigoriev** [comment]
It was about 1.11.x. Thanks

**Pull request merged**
