### PR TITLE
TRUNK-5769:  Upgrade commons libraries

### PR DESCRIPTION
**Pull request by achilep**
## Description of what I changed

I change the version of the following dependencies :
commons-beanutils:commons-beanutils:1.9.3 --> 1.9.4

commons-io:commons-io:2.6 --> 2.7

org.apache.commons:commons-lang3:3.9 -->3.10

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5769

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Have you tried running the reference application with these changes?

**Comment by achilep** [comment]
hello @dkayiwa  I could test this one and it works without problem .

Screenshot from 2020-06-12 07-06-07

**Comment by achilep** [comment]
Screenshot from 2020-06-16 08-51-21
hello @dkayiwa @mozzy11 ,
I tested with the standalone reference application .

**Comment by dkayiwa** [comment]
@achilep what are the exact steps that you went through to test this changes with the standalone?

**Comment by achilep** [comment]
@dkayiwa ,  @mozzy11  @sherrif10 
1.I use the command mvn clean install, I obtain a war file,
2. I replace the war file of the standalone reference application by my war file which I obtained 
3.and I use the command java -jar openmrs-standalone.jar to run the standalone reference application with my war that I replaced.

**Comment by achilep** [comment]
or I'm wrong @dkayiwa

**Comment by achilep** [comment]
openmrs.war I change its name to openmrs-standalone.

**Comment by dkayiwa** [comment]
And what did you do to the existing one?

**Comment by achilep** [comment]
i delete it.

**Comment by achilep** [comment]
to test a new change I delete all the contents of tomcat / webapp folder with everything that was created during the previous test. before putting the new war file for the new test.

**Comment by achilep** [comment]
@dkayiwa 
I am mistaken ?

**Pull request merged**
