### PR TITLE
Trunk-5551 Upgrade xerces:xercesImpl

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/TRUNK-5551
 Trunk-5551 Upgraded xerces:xercesImpl 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sherrif10** [comment]
Upgradin xercers:xercesImpl to 2.12.0 encounters test failures of which i didnot encounter in the first run locally, here  are the logs . https://pastebin.com/UTdUFpDP
 Mean while am going to commit another pull request  for a diiferent version

**Comment by sherrif10** [comment]
upgrading to version 2.12.0, have unvailable vulnerbilities, this is compatible to maven development,That means we should upgrade it to  less than 2.12.0 version which are availbale and are  of which are not incompatible with maven. This link contain more info https://snyk.io/vuln/maven:xerces:xercesImpl .cc @dkayiwa ,@mozzy, @Ruhanga

**Comment by HerbertYiga** [comment]
Could you try to checkout on the upgraded version,the ci build is breaking

**Comment by sherrif10** [comment]
Could you try to checkout on the upgraded version,the ci build is breaking, what do  you mean

**Comment by sherrif10** [comment]
@herbert24. version 2.12 is not yet vulnerable, i guess thats why ci is breaking, but they are less versions that are vulnerable

**Comment by dkayiwa** [comment]
@sherrif10 are you still working on this?

**Comment by sherrif10** [comment]
Some one is working on this ticket too.

**Pull request closed without merging**
