### PR TITLE
Trunk 4947

### PR DESCRIPTION
**Pull request by mavrk**
## Related Issue

see https://issues.openmrs.org/browse/TRUNK-

## Checklist:

- [ ] My pull request only contains one single commit.
- [ ] My pull request is based on the latest master branch
  `git pull --rebase upstream master`.
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Added method
ConceptService.getConceptSourceByHL7Code(String)

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mavrk did you take a look at our pull request tips page?

**Comment by mavrk** [comment]
Yes @dkayiwa I looked at the 'pull req tips' page. I realize my errors and I will make a new pull req keeping those tips in mind. Thanks :)

**Comment by mavrk** [comment]
Hey @dkayiwa is the pull req fine now?

**Comment by dkayiwa** [comment]
@mavrk just take a look at this page and you will see several commits. We need to see only one.

**Comment by mavrk** [comment]
@dkayiwa should I go for git rebase -i ?

**Comment by dkayiwa** [comment]
https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request closed without merging**
