### PR TITLE
TRUNK-5767  migrate the MXJ to MariaDB4j

### PR DESCRIPTION
**Pull request by achilep**
## TRUNK-5767: migrate the MXJ to MariaDB4j

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5767

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sherrif10** [comment]
LGTM  cc @dkayiwa  @ibacher

**Comment by dkayiwa** [comment]
@achilep have you actually tested this?

**Comment by dkayiwa** [comment]
@achilep i mean running the real application.

**Comment by achilep** [comment]
@dkayiwa  this one is working well in my machine .
Screenshot from 2020-06-11 23-04-58
hello @sherrif10

**Comment by achilep** [comment]
hello @dkayiwa , @mozzy11 @sherrif10  i a; using the standalone reference application to test .is it ok? 
Screenshot from 2020-06-15 23-19-17

**Comment by dkayiwa** [comment]
@achilep where is the pull request that you made for the standalone to replace the embedded mysql with mariadb4j? https://github.com/openmrs/openmrs-standalone

**Comment by sherrif10** [comment]
@dkayiwa  is it fine to create a ticket  in standalone toreplace embedded mysql with mariadb4j have we yet reached there !

**Comment by dkayiwa** [comment]
Do you mean moving this ticket from trunk to standalone?

**Comment by sherrif10** [comment]
@dkayiwa  Yes please

**Comment by dkayiwa** [comment]
How about creating a new one? Because this one also has some changes that need to be made.

**Comment by sherrif10** [comment]
Sure , we can actually create a new ticket but i think it should be allocated in standalone specifically

**Comment by dkayiwa** [comment]
ok go ahead.

**Comment by sherrif10** [comment]
commit [here](https://github.com/openmrs/openmrs-standalone/pull/46)

**Comment by tendomart** [comment]
Is threre reaon to keep this one still open since @sherrif10  created this one https://github.com/openmrs/openmrs-standalone/pull/46/files ?

**Comment by sherrif10** [comment]
cc @dkayiwa , what am sure of for us to migrate to MariaDB4J we should first replace the embedded mysql with mariaDB4J  on standalone, @dkayiwa any suggestion on this to answer @tendomart question

**Comment by sherrif10** [comment]
Hey @dkayiwa @ibacher , Am kinda stuck, if we are to depend on core with this change, that means we need to first implement this in  change core such that we can depend on it in standalone since standalone is updated with latest core version, i was thinking that we should first implement this in core and later depend on core for standalone to run on mariaDBDJ,  we could actually use this as another option for dealing with replacing mysql with mariaDB4J , any suggestion

**Pull request closed without merging**
