### PR TITLE
TRUNK-2660: Validate field lengths of domain objects in management pages

### PR DESCRIPTION
**Pull request by pmuchowski**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@pmuchowski the problem happens with all lines in the controller that start with: errors.reject("concept"

I also do not think this fixes it because you already have the popNestedPath call immediately after: ValidateUtil.validate(concept, errors);

**Comment by pmuchowski** [comment]
@dkayiwa popNestedPath after ValidateUtil.validate(concept, errors) won't work because validator throws exception

**Comment by dkayiwa** [comment]
Oh i see!
So you can you pop even in the other places where exceptions are caught?

On Tue, Jan 20, 2015 at 5:30 PM, pmuchowski <notifications@github.com>
wrote:

> @dkayiwa <https://github.com/dkayiwa> popNestedPath after
> ValidateUtil.validate(concept, errors) won't work because validator throws
> exception
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1289#issuecomment-70661283>.
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by pmuchowski** [comment]
@dkayiwa can you reopen PR?

**Comment by dkayiwa** [comment]
@pmuchowski unfortunately am not able to because the was force-pushed or recreated.

**Pull request closed without merging**
