### PR TITLE
Siva Reddy | BAH-2274 | Support for Java8 DateTime in jackson

### PR DESCRIPTION
**Pull request by sivareddytw**
## Description of what I changed
jackson starting from [2.12](https://github.com/FasterXML/jackson-databind/blob/6497f1b35ee917b4095d580082ecc4c3f03088ec/src/main/java/com/fasterxml/jackson/databind/util/BeanUtil.java#L297) version onwards needs dependency of `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` to process Java 8 date/time. 

## Issue I worked on
[https://bahmni.atlassian.net/browse/BAH-2274](https://bahmni.atlassian.net/browse/BAH-2274)

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by gsluthra — APPROVED** [review]

**Comment by dkayiwa** [comment]
@sivareddytw can i look at the complete full stack trace? I just want to create a small unit test for reproducing this.

**Comment by sivareddytw** [comment]
> @sivareddytw can i look at the complete full stack trace? I just want to create a small unit test for reproducing this.

@dkayiwa thanks for reviewing. Stack Trace added [here](https://github.com/openmrs/openmrs-core/pull/4146#issuecomment-1243704085).

**Comment by dkayiwa** [comment]
@sivareddytw which version of the webservices rest module are you running?
The current webservices rest module uses the old`org.codehaus.jackson.map.ObjectMapper` for json serialisation, which i would not expect to result into that error. Are you using `com.fasterxml.jackson.databind.ObjectMapper` any where?

**Comment by sivareddytw** [comment]
> @sivareddytw which version of the webservices rest module are you running? The current webservices rest module uses the old`org.codehaus.jackson.map.ObjectMapper` for json serialisation, which i would not expect to result into that error. Are you using `com.fasterxml.jackson.databind.ObjectMapper` any where?

@dkayiwa we are not using `com.fasterxml.jackson.databind.ObjectMapper` .

**Comment by dkayiwa** [comment]
@sivareddytw do you know of how i can locally reproduce this?

**Comment by sivareddytw** [comment]
> @sivareddytw do you know of how i can locally reproduce this?

@dkayiwa we experienced this issue Appointments Display Control of Patient's clinical dashboard.
If we want, we can get into a zoom call.

**Comment by dkayiwa** [comment]
@sivareddytw do you think you can come up with a unit test to reproduce it?

**Comment by dkayiwa** [comment]
I have cherry picked to the 2.5.x branch at: https://github.com/openmrs/openmrs-core/commit/1dae8f6eb275956d81a4a19b8c354140512b34c6

**Pull request merged**
