### PR TITLE
TRUNK: Change the expected value within UserService test to the actua…

### PR DESCRIPTION
**Pull request by kdaud**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-6056

## Checklist: I completed these to help reviewers :)

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [v ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kdaud does this test fail on bamboo?

**Comment by kdaud** [comment]
I have just run a plan on Bamboo and the run failed though not sure what failed it any way, however this test is failing on github actions as per the logs at https://github.com/openmrs/openmrs-core/runs/4951767821?check_suite_focus=true#step:7:787

**Comment by kdaud** [comment]
I have just run a plan on Bamboo and the run failed though not sure what failed it any way, however this test is failing on github actions as per the logs at https://github.com/openmrs/openmrs-core/runs/4951767821?check_suite_focus=true#step:7:787

**Comment by dkayiwa** [comment]
@kdaud this is the CI plan: https://ci.openmrs.org/chain/result/viewChainResult.action?planKey=TRUNK-MASTER&buildNumber=2834

**Comment by kdaud** [comment]
@dkayiwa the plan proved [green](https://ci.openmrs.org/browse/TRUNK-MASTER-2835/log). For one reason or the other this test is failing on github actions.

**Comment by dkayiwa** [comment]
It looks like a random failure. Try run the actions again.

**Comment by kdaud** [comment]
> Try run the actions again.

It returns a build failure pointing to the actual test. https://github.com/openmrs/openmrs-core/runs/4968611006?check_suite_focus=true#step:7:786

**Comment by dkayiwa** [comment]
@kdaud have you also tried to build locally?

**Comment by kdaud** [comment]
> @kdaud have you also tried to build locally?


@dkayiwa after building the core that took a full hour, the run [fails](https://pastebin.com/B4pXnS9L) probably because of the internet connection.

**Comment by dkayiwa** [comment]
@kdaud probably because you do not have all the dependencies loaded into your local maven repository. Try again.

**Comment by kdaud** [comment]
> @kdaud probably because you do not have all the dependencies loaded into your local maven repository. Try again.

Your guessing was right!


> It looks like a random failure

The guessing is right! I have triggered a plan locally and [the test is passing the run](https://pastebin.com/TPpVSiuS)

**Comment by dkayiwa** [comment]
With or without the changes in this pull request?

**Comment by kdaud** [comment]
> With or without the changes in this pull request?

This pull request has null changes. So  its equivalent to master code base and is what have run.

**Comment by kdaud** [comment]
Will share the outcome after building the tests with the earlier suggested changes!

**Comment by kdaud** [comment]
The run fails when with the changes and cites out the test at https://pastebin.com/bFDkmA8U

**Comment by dkayiwa** [comment]
Run that guy again.

**Comment by kdaud** [comment]
> Run that guy again.

@dkayiwa with out the changes the build plan is passing and opposite when the changes are introduced. Am wondering why the random failure on github action is happening only on a specific test.

**Comment by abertnamanya** [comment]
@kdaud  Locally the UserService Dataset carries only 11 as for github they are 12, there is an extra which comes in. That's why the test is not passing. 
Please checkout https://talk.openmrs.org/t/diagnosis-support-for-conditionclinicalstatuses-recurrence-relapse-remission-resolved/35711

**Comment by kdaud** [comment]
@abertnamanya the link is redirecting to a wrong page, do you mind to check it out?

**Comment by abertnamanya** [comment]
> @abertnamanya the link is redirecting to a wrong page, do you mind to check it out?

Sorry I had shared a private message link but it was still about the same issue but please checkout the comment that I have added onto this ticket on jira

**Comment by dkayiwa** [comment]
@kdaud do you see these merge conflicts?

**Comment by kdaud** [comment]
> @kdaud do you see these merge conflicts?

On resolving the conflict I realized the suggested changes were no longer required since the expected value was matching the actual value on Github actions.

Take care.

**Pull request closed without merging**
