### PR TITLE
TRUNK-4549: Error message description while creating a user

### PR DESCRIPTION
**Pull request by Parkersungwoo**
The original ticket for this pull request can be found on LUI-82. However, all previous pull requests for this ticket are on TRUNK-4549. This pull request added two new types error messages for newly created user passwords. These error messages are for a passwords matching usernames, and passwords matching system IDs. Also included in this pull request are combined error messages giving feedback to users about many password errors.

New password matching username error message:
Screenshot (19)

New concatenated error messages:
image

## Description of what I changed

I updated the validatePassowrd() method in Openmrsutil.java to now throw a password exception at the end with a message containing all of the reasons for the invalid password.

## Issue I worked on

https://issues.openmrs.org/browse/LUI-82

## Checklist: I completed these to help reviewers :)

- [X] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [X] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [X] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [X] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you include a link to the ticket as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Parkersungwoo** [comment]
@dkayiwa  Done!

> Can you include a link to the ticket as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
Did you intentionally delete the InvalidCharactersPasswordException and ShortPasswordException classes?

**Comment by Parkersungwoo** [comment]
> Did you intentionally delete the InvalidCharactersPasswordException and ShortPasswordException classes?

Yes. This was because I believe they were relatively underutilized and my implementation of the concatenated error messages would work best with a single PasswordException class. So what I did was delete 2/3 of the existing PasswordException classes and refactor the remaining class to handle all password exception errors. Then we can concatenate a string throughout the validatePassword method and throw the single exception with the concatenated message at the end of the method.

**Comment by Parkersungwoo** [comment]
@dkayiwa  Is there anything I can help out with to get this PR approved?

**Comment by dkayiwa** [comment]
What is the reason behind changing all these exceptions from what they were to InvalidPasswordException?

**Pull request closed without merging**
