### PR TITLE
GCI-245: Redundant nullcheck of rs which is known to be null in AddCo…

### PR DESCRIPTION
**Pull request by ODORA0**
…nceptMapTypesChangeset

https://issues.openmrs.org/browse/GCI-245

### CODE REVIEW

**Comment by fanyui** [comment]
Hello @ODORA0  could you take a look at this https://wiki.openmrs.org/display/docs/Pull+Request+Tips .
you seem to have deleted some of the content of the description field while making this pull request.

**Comment by ODORA0** [comment]
@fanyui I am not sure what you mean there, could you please elaborate more? Can't find what you are saying over the link.

**Comment by fanyui** [comment]
Where the have https://issues.openmrs.org/browse/GCI-245 in your description there are supposed to be some check fields where you specify the task you completed before making this pull request. just check other pull request you will  see what am saying

**Comment by ODORA0** [comment]
Is that really neccessary because a couple of PRs I have seen too do not have that, but most importantly have ticket IDs at least.

**Comment by dkayiwa** [comment]
What exactly is accomplished in this pull request?

**Comment by ODORA0** [comment]
@dkayiwa  the lines as of the links in the ticket were not updated since they did not show the required lines for removal, so I removed what I expected as part of the redundant nullhecks for the rs variable. It seems to me the rs variable itself was removed already too.

**Comment by dkayiwa** [comment]
Did you intentionally remove all the red lines here as redundant code? https://github.com/openmrs/openmrs-core/pull/2864/files

**Comment by ODORA0** [comment]
I intentionally removed the lines within the try not the other changes.

**Comment by dkayiwa** [comment]
Is that because we did not need that functionality?

**Comment by ODORA0** [comment]
That's what I thought as I changed that.

**Comment by dkayiwa** [comment]
Why do you think that we do not need that functionality?

**Comment by ODORA0** [comment]
Probably a reference to the rs would cause errors, given the fact that the rs variable is not actually used.

**Comment by dkayiwa** [comment]
What do you understand by a variable not being used?

**Comment by ODORA0** [comment]
One that is no longer needed or is not stored in values.

**Comment by dkayiwa** [comment]
So is rs not used in the code that you have removed?

**Comment by ODORA0** [comment]
It seems to be used although what prompted me to remove those lines was the fact that referencing code to an unused variable would not be of as much required, that's what I initially thought

**Comment by dkayiwa** [comment]
Closing because this was already done here: https://github.com/openmrs/openmrs-core/commit/859cb3ba9cb074957e93e4171a723215ebb0ec97#diff-6a9b9c25c40c83eb9fbe69c93c5be32c

**Comment by dkayiwa** [comment]
@ODORA0 if you look at the above commit, you will understand what the ticket was all about. A variable declared and then attempted to be used with a meaningful value.

**Pull request closed without merging**
