### PR TITLE
Merging the first set of of gci PRs into master after resolving conflicts originally merged into gci-2014 branch

### PR DESCRIPTION
**Pull request by k-joseph**
Merging all gci-2014 commits previously merged into gci upstream branch step of reviewed gci commits into master,

### CODE REVIEW

**Comment by k-joseph** [comment]
@harsha89, this PR now includes all commits merged into https://github.com/openmrs/openmrs-core/tree/gci-2014 excepts one i had innocently reverted, https://github.com/openmrs/openmrs-core/pull/1186 i have requested @azuro to open a new PR to be directly merged into master.

**Comment by dkayiwa** [comment]
@k-joseph  @harsha89 how do i see the exact changes you wanted this pull request to have? I see many other non CGI merges listed here.

**Comment by k-joseph** [comment]
Something should be wrong with these that i had not noticed before, just not sure why these would show up here, i will close this and we shall redo this work, thanks @dkayiwa for noticing this.

How i created this PR:
- Checked out a new branch locally after updating master local branch from upstream master branch
- Pulled from upstream gci-2014 branch into my new local branch.
- Committed and created PR, 

Am glad this is still un-merged.
@harsha89, does this mean our gci-2014 mean not be worth our trust for all gci merged tasks, what's our step for those commits that were committed in this branch?
I also hope that we shall resume vising un-merged PR's tomorrow!

**Comment by harsha89** [comment]
Hi Joseph,

Shall we discuss this today and sort out things? I will catch you at IRC.

Thanks,
Harsha

On Mon, Feb 16, 2015 at 10:38 PM, k-joseph <notifications@github.com> wrote:

> Something should be wrong with these that i had not noticed before, just
> not sure why these would show up here, i will close this and we shall redo
> this work, thanks @dkayiwa <https://github.com/dkayiwa> for noticing this.
>
> How i created this PR:
>
>    - Checked out a new branch locally after updating master local branch
>    from upstream master branch
>    - Pulled from upstream gci-2014 branch into my new local branch.
>    - Committed and created PR,
>
> Am glad this is still un-merged.
> @harsha89 <https://github.com/harsha89>, does this mean our gci-2014 mean
> not be worth our trust for all gci merged tasks, what's our step for those
> commits that were committed in this branch?
> I also hope that we shall resume vising un-merged PR's tomorrow!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1340#issuecomment-74540822>.
>



-- 
*Harsha Kumara*
*Software Engineer*
*WSO2 Inc.*
*Sri Lanka.*

**Pull request closed without merging**
