### PR TITLE
TRUNK-5521:Upgrade javax Libraries

### PR DESCRIPTION
**Pull request by jwnasambu**
## Description of what I changed
I upgraded library javax API sub-libraries below 
 # javax.mail:mail … 1.4.1 -> 1.5.0-b01
 #  javax.servlet:javax.servlet-api … 3.0.1 -> 4.0.1
 #  javax.servlet:jsp-api … 2.0 -> 2.0.public_draft
 #  javax.servlet:jstl … 1.1.2 -> 1.2
 # javax.validation:validation-api … 1.0.0.GA -> 2.0.1.Final

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5521

### CODE REVIEW

**Comment by jwnasambu** [comment]
@Ruhanga, @mozzy11 , @dkayiwa  after making the PR the Travis fails to build after building successfully locally. How can I go about it?

**Comment by dkayiwa** [comment]
Did you look at the error log?

**Comment by jwnasambu** [comment]
Yes I did but am still figuring out what could be the cause because locally it builds successfully.

**Comment by mozzy11** [comment]
@jwnasambu did you take at the error logs ??
`Could not find artifact javax.servlet:jsp-api:jar:2.0.public_draft in central `

**Comment by mozzy11** [comment]
make sure you update to  the right version

**Comment by HerbertYiga** [comment]
@jwnasambu   first check for the dependency on the maven  online repository before any updates!!

**Comment by dkayiwa** [comment]
@jwnasambu are you still working on this?

**Comment by jwnasambu** [comment]
Irene is the one working on the ticket not me.

    On Monday, June 24, 2019, 11:10:32 PM GMT+3, dkayiwa <notifications@github.com> wrote:  
 
 
@jwnasambu are you still working on this?

**Pull request closed without merging**
