### PR TITLE
TRUNK-5037 Replace use of synchronized class Vector with ArrayList

### PR DESCRIPTION
**Pull request by dilekamadushan**
https://issues.openmrs.org/browse/TRUNK-5037?filter=-1
Description of what I changed
Replaced use of synchronized class Vector with ArrayList

Checklist: I completed these to help reviewers :)

[ x] My pull request only contains ONE single commit

[x ] My IDE is configured to follow the code style of this project.

[ x] I have added tests to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

[x ] I ran mvn clean package right before creating this pull request and
added all formatting changes to my commit.

[ x] All new and existing tests passed.

[ x] My pull request is based on the latest changes of the master branch.

### CODE REVIEW

**Comment by f4ww4z** [comment]
>TRUNK-5067 Add tests to MessageServiceTest, added test cases for branches, MessagePreparators in MessageServiceTest.java

is this related to the PR? Can you remove it from the description?

Try following the [PR Template format](https://github.com/openmrs/openmrs-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by dilekamadushan** [comment]
@f4ww4z I modified the description of my pull reques. Feel free to guide me on how to proceed foreward on this task. Thanks

**Comment by dilekamadushan** [comment]
@f4ww4z Feel free if any modifications needs to be done

**Comment by f4ww4z** [comment]
@dilekamadushan , you want to wait for this PR to be merged, and then wait for #2554 to be merged, before working on another issue / open PR.

**Comment by dilekamadushan** [comment]
@dkayiwa Thanks for merging and looking foreward for your support in other PR :smile:

**Comment by dilekamadushan** [comment]
@f4ww4z Thank you very much for your support in making this PR successful

**Pull request merged**
