### PR TITLE
GCI-87: Fixed unable to save complex obs

### PR DESCRIPTION
**Pull request by Vincentes**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
LGTM -- Approved as part of [GCI 2015](https://codein.withgoogle.com/dashboard/task-instances/5087982960771072/)

**Comment by maany** [comment]
I'm not a core committer either. @wluyima @dkayiwa can you take a look?

**Comment by kaweesi** [comment]
am we directly merging GCI code into core this time round! or we shall have to wait until the contest is done as we did last time or even still wire the PRs to a separate branch!

**Comment by dkayiwa** [comment]
@kaweesi i would vote for merging immediately once reviewed and found fine. This would save us from the pain of merge conflicts that usually happen when pull requests stay for long. In summary, the only reason why a pull request should stay open is when it is waiting for more changes or reviews. I hope others agree. :)

**Comment by maany** [comment]
I would agree with Daniel :+1:

**Comment by dkayiwa** [comment]
@Vincentes are you still working on this?

**Comment by Vincentes** [comment]
@dkayiwa I guess this would be the solution? I really don't know what to do besides this.

**Comment by dkayiwa** [comment]
I agree with you @lluismf :)

**Pull request closed without merging**
