### PR TITLE
Trunk 5521 upgrade javax libraries

### PR DESCRIPTION
**Pull request by Irenyak1**
## Description of what I changed
I updated the following libraries 
1.javax.mail:mail … 1.4.1 -> 1.4.7
2.javax.servlet:javax.servlet-api … 3.0.1 -> 4.0.1
3.javax.servlet:jsp-api … 2.0 -> 2.3.3
4.javax.servlet:jstl … 1.1.2 -> 1.2
5.javax.validation:validation-api … 1.0.0.GA -> 2.0.1.Final

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5521

### CODE REVIEW

**Comment by HerbertYiga** [comment]
do these upgrades pass locally??

**Comment by Irenyak1** [comment]
@dkayiwa please review this PR also if possible. Thank you very much.

**Comment by dkayiwa** [comment]
@Irenyak1 did you look at the travis failure?

**Comment by Irenyak1** [comment]
@dkayiwa  yes i did and am trying to upgrade one by one and see which one is failing.

**Comment by Irenyak1** [comment]
@dkayiwa  yes I saw them, and am working on them.

**Pull request closed without merging**
