### PR TITLE
GCI-175: Make PseudoStaticContentController Logger private static final

### PR DESCRIPTION
**Pull request by MichaelMMacLeod**
## Description of what I changed
Changed PseudoStaticContentController Logger from being `protected final` to `private static final`

## Issue I worked on

see https://issues.openmrs.org/browse/GCI-175

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by reubenvarghese1** [comment]
This looks good to me. @dkayiwa Can you please confirm and merge this? I do not have the necessary rights to do so

**Comment by dkayiwa** [comment]
@reubenvarghese1 i do not see the ticket assigned to him. Did he just forget to claim it?

**Comment by reubenvarghese1** [comment]
@MichaelMMacLeod Please assign yourself to https://issues.openmrs.org/browse/GCI-175 to this task

**Comment by MichaelMMacLeod** [comment]
Sorry about that! Here's the ticket: https://issues.openmrs.org/projects/GCI/issues/GCI-175?filter=allopenissues

**Comment by MichaelMMacLeod** [comment]
Sorry about that! Here's the ticket: https://issues.openmrs.org/browse/GCI-175

**Pull request merged**
