### PR TITLE
TRUNK-4762 Removed <c:out> tage in concept units so that superscript will be dis…

### PR DESCRIPTION
**Pull request by preethi29**
…played properly

### CODE REVIEW

**Comment by dkayiwa** [comment]
@preethi29 can you create a ticket for it such that you can have some detailed description as to why we need this? Since c:out was intentionally put to prevent xss attacks.

**Comment by preethi29** [comment]
@dkayiwa the issue that I created: https://issues.openmrs.org/browse/TRUNK-4762

**Comment by dkayiwa** [comment]
@preethi29 though this fixes the reported problem, it exposes us to XSS attacks. Can you think of something else?

**Comment by dkayiwa** [comment]
Closing because these pieces are now moved to the legacyui module.

**Pull request closed without merging**
