### PR TITLE
TRUNK-4720 search will not match on id unless it contains digits

### PR DESCRIPTION
**Pull request by blavigne13**
## Description

Previously, the code made a decision on whether the query was a name or identifier by using a regex to determine if the query contained one or more digits, then created the appropriate PatientSearchCriteria. In cases of identifiers without digits, or names with them, it was not possible to obtain the correct result. Now, both names and identifiers are searched, without attempting to categorize the query beforehand.

Behavior has also been slightly changed: An exact match is now required for identifier to produce a result. Note: this only applies to identifier; name will still match on partial search terms. This is consistent with how other "name or identifier" queries are handled (e.g.: Find Patient, Find Provider) and is presumably for performance reasons.

Code changes:
Removed local vars "name" and "identifier" since "query" is used in both cases
Removed conditional branching based upon query type
Arguments to prepareCriteria have had the following changes applied:
  "query" is now passed as both name and identifier
  "true" is now passed for both matchIdentifierExactly and searchOnNamesOrIdentifiers

## Related Issue

see https://issues.openmrs.org/browse/TRUNK-

## Checklist:

- [x] My pull request only contains one single commit.
- [x] My pull request is based on the latest master branch
  `git pull --rebase upstream master`.
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@blavigne13 can you create some unit tests for this?

**Comment by blavigne13** [comment]
@dkayiwa Will do. 

After giving it some thought, my plan is to put together a few tests to ensure that substring matches are only returned for names, and not identifiers. So far that's the only thing I've noticed that the existing tests don't cover. They could also be used for similar queries, e.g.: find patient, find provider, but I'm not sure if adding those same tests to methods unrelated to this ticket would be appropriate...

**Comment by dkayiwa** [comment]
@blavigne13 the pull request requires squashing commits into one. Did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@blavigne13 if you find it hard rectifying this, feel free to ask for help on the IRC channel. https://wiki.openmrs.org/display/IRC/Home

**Comment by dkayiwa** [comment]
@blavigne13 am closing this so that you create a new one.

**Pull request closed without merging**
