### PR TITLE
TRUNK-4813:SQLException during the initial setup

### PR DESCRIPTION
**Pull request by mnsowmya**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mnsowmya can you put space between "as" and "(" ?

**Comment by mnsowmya** [comment]
@dkayiwa changed it  as per the suggestion

**Comment by dkayiwa** [comment]
@mnsowmya i have reverted this because if will make upgrades fail. Can you fix it with the instructions at ?https://wiki.openmrs.org/display/docs/How+to+Modify+a+Bad+Changeset

**Comment by mnsowmya** [comment]
@dkayiwa yes i will

**Pull request merged**
