### PR TITLE
Adjustments on ticket TRUNK-4742

### PR DESCRIPTION
**Pull request by gitcliff**
TRUNK-4742: Fix some issue
LINK:https://issues.openmrs.org/browse/TRUNK-4742?src=confmacro
Add support for setting test database credentials externally

### CODE REVIEW

**Comment by samuelmale** [comment]
Did you see the travis failure?

**Comment by gitcliff** [comment]
yaa i have seen it and trying to compile again and do i to create another pull request after compiling again?

**Comment by samuelmale** [comment]
You don't need to create another Pull Request. Just pushing changes to the remote ref your working branch is enough.

**Comment by gitcliff** [comment]
Hello Sam, i have compiled again and the compilation was successful but haven't done any changes in the code, how can i push the compilations changes so that travis failure turns successful?

**Comment by samuelmale** [comment]
How did you do the compile? In the travis context we mean a project build ie. `mvn clean install`. Is the build successful locally?

**Comment by gitcliff** [comment]
yes its succesful locally

**Comment by samuelmale** [comment]
Did you see this? https://travis-ci.org/openmrs/openmrs-core/builds/488991716#L2423

**Pull request closed without merging**
