### PR TITLE
TRUNK-5896 : Using Annotations for VisitAttributeType

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed

1. Added Annotations based on the VisitAttributeType.hbm.xml file.
2. Made some changes in tests and removed entry from hibernate.cfg.xml file.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5896

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by LuGO0** [comment]
@gitcliff can you suggest any changes required?

**Comment by tendomart** [comment]
I think this is okk

**Comment by HerbertYiga** [comment]
thanks @LuGO0 can we add all the attributes of  VisitAttributeType , i see you only have visit_attribute_type_id. checkout the  hibernate mapping file you dropped or the (visit_attribute_type) table for comparison  on this.

**Comment by LuGO0** [comment]
Thanks @HerbertYiga will look into it, I saw some of the attributes inside the deleted files were covered by the extended base class, I will see again which attributes need to be added into this file .

**Comment by LuGO0** [comment]
@HerbertYiga I think all these attributes are covered by `BaseAttributeType` and `BaseOpenmrsMetadata`

**Comment by LuGO0** [comment]
@tendomart @HerbertYiga I am getting this unknown resource exception, am I missing something?
`org.openmrs.module.webservices.rest.web.response.UnknownResourceException: Unknown resource: v1/user
	at org.openmrs.module.webservices.rest.web.api.impl.RestServiceImpl.getResourceByName(RestServiceImpl.java:416)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:53)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:352)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)`

**Comment by LuGO0** [comment]
I am using snapshot 2.33.0 webservices.rest module

**Comment by dkayiwa** [comment]
@LuGO0 if you are running the master version of the OpenMRS platform, you need to do this for platform version 2.6 https://issues.openmrs.org/browse/RESTWS-815

**Comment by LuGO0** [comment]
> @LuGO0 if you are running the master version of the OpenMRS platform, you need to do this for platform version 2.6 https://issues.openmrs.org/browse/RESTWS-815

Okay so I should checkout platform 2.6 and then make these changes?

**Comment by dkayiwa** [comment]
> > @LuGO0 if you are running the master version of the OpenMRS platform, you need to do this for platform version 2.6 https://issues.openmrs.org/browse/RESTWS-815
> 
> Okay so I should checkout platform 2.6 and then make these changes?

How about just adding support for platform 2.6 to the module?

**Comment by LuGO0** [comment]
@dkayiwa I changed the version from 2.6.0-SNAPSHOT to 2.5.0 inside openmrs-core and it worked, should I make a similar PR to [this](https://github.com/openmrs/openmrs-module-webservices.rest/commit/49452d7f0c2eebc76659342dd8aba0fb60ee8bb6) for `2.6.*` on RESTWS project? should I create a new Ticket for that?

**Comment by dkayiwa** [comment]
> should I make a similar PR like [this](https://github.com/openmrs/openmrs-module-webservices.rest/commit/49452d7f0c2eebc76659342dd8aba0fb60ee8bb6) for `2.6.*` on RESTWS project? should I create a new Ticket for that?

Both would be awesome! 😊

**Comment by LuGO0** [comment]
Sure @dkayiwa  the PR for supporting 2.6.* is up here https://github.com/openmrs/openmrs-module-webservices.rest/pull/527/files

**Comment by dkayiwa** [comment]
> Sure @dkayiwa the PR for supporting 2.6.* is up here https://github.com/openmrs/openmrs-module-webservices.rest/pull/527/files

Awesome! 👍

**Comment by LuGO0** [comment]
@dkayiwa Tested platform 2.6.0-SNAPSHOT works with the Webservies.rest 2.33.0-SNAPSHOT.

**Comment by LuGO0** [comment]
Screenshot 2021-11-15 160229

**Comment by dkayiwa** [comment]
> Tested platform 2.6.0-SNAPSHOT works with the Webservies.rest 2.33.0-SNAPSHOT.

That is great!!! 👍

**Comment by dkayiwa** [comment]
@LuGO0 have you addressed all the comments above from various reviewers?

**Comment by LuGO0** [comment]
> @LuGO0 have you addressed all the comments above from various reviewers?

Yes @dkayiwa I have addressed @HerbertYiga comments I think those attributes dont need to added inside the VisitAttributeType, am I wrong here ?

**Pull request merged**
