### PR TITLE
Trunk 4659

### PR DESCRIPTION
**Pull request by chenjr95**
@dkayiwa

### CODE REVIEW

**Comment by chenjr95** [comment]
@dkayiwa I opened a PR to try and fix this, when I tried to change Patient.setIdentifiers and Form.formFields the api tests would fail so these were all the instances of setter functions taking in sets that I could find and fix that didn't break the api tests, could you take a look at them?

**Comment by dkayiwa** [comment]
@chenjr95 can you squash these commits into one? http://go.openmrs.org/pull-request-tips

**Comment by dkayiwa** [comment]
@chenjr95 can you squash the commits into one?

**Comment by dkayiwa** [comment]
@chenjr95 can you squash the commits into one?

**Comment by chenjr95** [comment]
@dkayiwa I followed the instructions on here: https://wiki.openmrs.org/display/docs/Pull+Request+Tips to squash the commits and this was what resulted

**Comment by chenjr95** [comment]
@dkayiwa squashed

**Comment by dkayiwa** [comment]
@chenjr95 it would be good to use a commit message describing the changes instead of just "squashed commits into one"

**Pull request merged**
