### PR TITLE
TRUNK-5845:Using isEmpty() to check whether the collection is empty o…

### PR DESCRIPTION
**Pull request by miirochristopher**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5931 

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [  ] I have **added tests** to cover my changes. 
- [x] I ran `mvn clean package` right before creating this pull request and added all formatting changes to my commit.
- [x] All new and existing **tests passed**.
- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Review by sacull — APPROVED** [review]

**Comment by sacull** [comment]
@miirochristopher Please remember to mark on the checklist in the PR description that you have taken the steps listed. Then the reviewer is sure that you have prepared this PR well.

@dkayiwa In my opinion it is good. ;)

**Comment by dkayiwa** [comment]
@miirochristopher the ticket id does not look correct.

**Comment by miirochristopher** [comment]
@dkayiwa this is the ticket ; [TRUNK-5845](https://issues.openmrs.org/browse/TRUNK-5931) perhaps I was supposed to use the TRUNK-5931 at the tail of the ticket title. Please advise.

**Comment by sacull** [comment]
@miirochristopher Please correct it in the PR description.

**Comment by miirochristopher** [comment]
Alright @sacull ; though a need a little help knowing which is the correct one. Ticket has a title TRUNK-5845 Search and fix minor errors and typos / TRUNK-5931.

**Comment by sacull** [comment]
This is your ticket: https://issues.openmrs.org/browse/TRUNK-5931 and only it should be in the description at section "Issue I worked on".

**Comment by miirochristopher** [comment]
Thanks a bunch @sacull and @dkayiwa :100:

**Comment by sacull** [comment]
image
Are you sure? ;)

**Comment by miirochristopher** [comment]
I felt it useful to correct the ticket name TRUNK-5931 to please consider the latest PR here with all the changes suggested. Thanks. https://github.com/openmrs/openmrs-core/pull/3542

**Pull request closed without merging**
