### PR TITLE
TRUNK-5018 Update locale of user while logging in

### PR DESCRIPTION
**Pull request by pushpa446**
## Related Issue

see https://issues.openmrs.org/browse/TRUNK-

## Checklist:

- [ ] My pull request only contains one single commit.
- [ ] My pull request is based on the latest master branch
  `git pull --rebase upstream master`.
- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@pushpa446 the user logs in with Context.authenticate() instead of Context.refreshAuthenticatedUser()

**Comment by pushpa446** [comment]
Hi @dkayiwa, Did you mean we should setUserLocale in Context.authenticate() instead of Context.refreshAuthenticatedUser()? 
If yes, by the time Context.authenticate() executes, database is not updated with the current user properties. 
If I'm not wrong, here we save the properties. https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/UserResource2_0.java#L49

**Comment by dkayiwa** [comment]
@pushpa446 when is Context.refreshAuthenticatedUser() called?

**Comment by pushpa446** [comment]
Hi @dkayiwa ,
right after save, here we are calling Context.refreshAuthenticatedUser()
https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/UserResource2_0.java#L50

**Comment by dkayiwa** [comment]
Should i then say that it is the ticket wording that confused me? For it says "Update locale of user while logging in" :)

**Comment by pushpa446** [comment]
Hi @dkayiwa, sorry if that confuses you. My understanding is each time a user logs in, the user properties changes. We are saving them. But as part of this, we are not updating the same into the UserContext. Suggest me the correct message :)

**Comment by dkayiwa** [comment]
@pushpa446 will that code get executed when one logs in using https://github.com/openmrs/openmrs-module-legacyui/blob/c9bb7b8ba008573568f46cb2d09ca987d309683d/omod/src/main/java/org/openmrs/web/servlet/LoginServlet.java
Or
https://github.com/openmrs/openmrs-module-referenceapplication/blob/master/omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/LoginPageController.java

**Comment by pushpa446** [comment]
@dkayiwa For this, https://github.com/openmrs/openmrs-module-legacyui/blob/c9bb7b8ba008573568f46cb2d09ca987d309683d/omod/src/main/java/org/openmrs/web/servlet/LoginServlet.java we are not sending and storing User properties no? So it is updating locale as per available info https://github.com/openmrs/openmrs-module-legacyui/blob/c9bb7b8ba008573568f46cb2d09ca987d309683d/omod/src/main/java/org/openmrs/web/servlet/LoginServlet.java#L144 here

**Comment by dkayiwa** [comment]
@pushpa446 does that mean your changes are not relevant for the above two scenarios?

**Comment by pushpa446** [comment]
Yes. In both the scenarios that you have mentioned, I think we are not modifying the UserProperties. So, we are taking the existing OpenmrsConstants.USER_PROPERTY_DEFAULT_LOCALE of User and setting the locale to the Context.

**Pull request merged**
