### PR TITLE
TRUNK-5077: Aligning ObsServiceTest with branch 2.0.x.

### PR DESCRIPTION
**Pull request by mks-d**
## Description
Second commit to align the new test case added in `ObsServiceTest` with what was pushed on all other branches (1.10.x, 1.11.x, 1.12.x and 2.0.x).
## Related Issue

https://issues.openmrs.org/browse/TRUNK-5077

## Checklist:

- [x] My pull request only contains one single commit.
- [x] My pull request is based on the latest 1.10.x branch
  `git pull --rebase upstream master`.
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mks-d** [comment]
Than you @dkayiwa !

**Comment by dkayiwa** [comment]
@mks-d are you planning to do one for 1.11.x?

**Comment by mks-d** [comment]
Yes I just did it at [#2039](https://github.com/openmrs/openmrs-core/pull/2039).
But you said you would do 1.12.x right?

**Comment by dkayiwa** [comment]
Yes i have cherry-picked to 1.12.x.
Thanks 👍

**Pull request merged**
