### PR TITLE
TRUNK-2925: Change Daemon method to take in integer id

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-2925

### CODE REVIEW

**Comment by ODORA0** [comment]
This passed locally though, @dkayiwa @mozzy11 @Ruhanga please review so i can correct it accordingly trying to go through the logs but don't get them quite well

**Comment by mozzy11** [comment]
@ODORA0  , can you take a look at these tests , and ensure you fix the error
Failed tests: 
  DaemonTest.daemonUser_shouldHaveAssociatedPerson:144 Daemon user should have an associated person
Tests in error: 
  DaemonTest.executeScheduledTask_shouldNotBeCalledFromOtherMethodsOtherThanTimerSchedulerTask:45 NullPointer
  DaemonTest.executeScheduledTask_shouldNotThrowErrorIfCalledFromATimerSchedulerTaskClass:63 » NullPointer
  DaemonTest.runInNewDaemonThread_shouldNotThrowErrorIfCalledFromADaemonThread:130 » NullPointer
  AuditableInterceptorTest.onFlushDirty_shouldNotFailWhenTheDaemonUserModifiesSomething:170 » NullPointer

**Comment by HerbertYiga** [comment]
@odorajonathan have you checked in to your CI logs?

**Comment by dkayiwa** [comment]
@ODORA0 did you see the above question?

**Comment by ODORA0** [comment]
Am gonna work on this

**Pull request closed without merging**
