### PR TITLE
TRUNK-4728 - Enables batching of inserts and updates in the JDBC driver.

### PR DESCRIPTION
**Pull request by rcrichton**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rcrichton do you mind creating a ticket for this? :)

**Comment by rcrichton** [comment]
Hi, I already have :) It's here: https://issues.openmrs.org/browse/TRUNK-4728

**Comment by dkayiwa** [comment]
@rcrichton is all well when you locally do a complete mvn clean install?

**Comment by rcrichton** [comment]
@dkayiwa I get a failed tests, however I get that on master as well:

```
Results :

Failed tests: 
  LocaleUtilityTest.getDefaultLocale_shouldNotReturnNullIfGlobalPropertyDoesNotExist:148 expected null, but was:<en_GB>

Tests run: 3053, Failures: 1, Errors: 0, Skipped: 29

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenMRS ........................................... SUCCESS [1.404s]
[INFO] openmrs-tools ..................................... SUCCESS [0.861s]
[INFO] openmrs-test ...................................... SUCCESS [0.097s]
[INFO] openmrs-api ....................................... FAILURE [1:29.290s]
[INFO] openmrs-web ....................................... SKIPPED
[INFO] openmrs-webapp .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
