### PR TITLE
GCI Contributions

### PR DESCRIPTION
**Pull request by harsha89**

### CODE REVIEW

**Comment by k-joseph** [comment]
Is this having all the gci commits that were merged into the gci branch without none missing out?

**Comment by k-joseph** [comment]
I see a total of 14 merged pull requests for gci-2014 and I hope we have more commits than just these in this PR

**Comment by harsha89** [comment]
I discarded some of them as they not make any sense such as shortening the if statements by aggregating the conditions so on. So I filter out those things. :).

**Comment by downeym** [comment]
:+1: on getting these in ASAP

**Comment by downeym** [comment]
Does this PR replace the existing GCI PR's that are already pending for openmrs-core, or is it additional?

**Comment by dkayiwa** [comment]
@harsha89 these commits look fine apart from just one question which i have put on the last commit.

**Comment by k-joseph** [comment]
Actually most of these fixes you mentioned @harsha89, i have also done in my next PR, which is about resolving conflicts of all the GCI PRs and i hope that after we merge this into gci-2014, we can re-do this to avoid more conflicts. 

 I have while working on the it considered all gci PRs and left out none. just a few minutes and you will have it for your review here

**Comment by harsha89** [comment]
@downeym this PR takes the commits from the PRs made by GCI students :). I have went through commit by commit and add to the latest master :). Some commits are ignored by myself as beacuse of some tradeoffs such as code complexity vs understandability.

**Comment by k-joseph** [comment]
After a close review of https://github.com/openmrs/openmrs-core/pull/1358 which right now has all commits for gci-2014 that have not yet been merged into master, we shall close this PR and merge pull/1358 into master instead.

thanks @harsha89 :+1:

**Comment by k-joseph** [comment]
Am now closing this PR since i have merged https://github.com/openmrs/openmrs-core/pull/1358 as mentioned before

**Pull request closed without merging**
