### PR TITLE
OMRS-131: Detailed Audit Logging (Updated)

### PR DESCRIPTION
**Pull request by wikumChamith**
## Description of what I changed

Enabled logging for several tables that were not included in the previous [PR](https://github.com/openmrs/openmrs-core/commit/2111f62acc036525fbf45b4e7b1f864503cad940)

Added @NotAudited to the `scheduler_task_config_property` table as it is similar to the `user_properties` table.

## Issue I worked on

see https://openmrs.atlassian.net/browse/OMRS-131 
## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@wikumChamith do we have corresponding tables for all these entities?

**Comment by wikumChamith** [comment]
@dkayiwa I updated the PR.

**Comment by dkayiwa** [comment]
@wikumChamith apart from `medication_dispense` which you left out for now because of errors, i still see more entities that are not audited. Can you go through them one by one and confirm that you have included them all?

**Comment by dkayiwa** [comment]
@wikumChamith i have also put the audited annotation on medication_dispense and run mvn clean install, after which i then run mvn test -Pskip-default-test -Pintegration-test, but got no test failures. What triggered the errors that you got?

**Comment by wikumChamith** [comment]
> @wikumChamith i have also put the audited annotation on medication_dispense and run mvn clean install, after which i then run mvn test -Pskip-default-test -Pintegration-test, but got no test failures. What triggered the errors that you got?

@dkayiwa `mvn clean install` passes without any errors for me too. However, the GitHub action tries to run these tests when building:  https://github.com/openmrs/openmrs-core/blob/3a7925a3484c098078db6e70f9b6f4a6cbb4e884/api/src/test/java/org/openmrs/util/databasechange/ValidateHibernateMappingsDatabaseIT.java#L32

I tried manually running it and it failed for me locally. Can we ignore that test?

**Comment by wikumChamith** [comment]
> @wikumChamith apart from `medication_dispense` which you left out for now because of errors, i still see more entities that are not audited. Can you go through them one by one and confirm that you have included them all?

@dkayiwa I created a new PR for this: https://github.com/openmrs/openmrs-core/pull/4668

**Pull request merged**
