### PR TITLE
TRUNK-4977: ImageHandler to delete trailing 0-byte files.

### PR DESCRIPTION
**Pull request by mks-d**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mks-d these changes are more than i expected!

**Comment by mks-d** [comment]
I'm sorry, some reformatting got in the way, damn it!
I'll pay even more attention to it next time.

**Comment by mks-d** [comment]
Ok bear with me... I'll update this in a few minutes...

**Comment by dkayiwa** [comment]
@mks-d do not worry. It happens to all of us once in a while. :)

**Pull request merged**
