### PR TITLE
TRUNK-5776: Upgrade liquibase-core from 3.8.9 to 3.10.0

### PR DESCRIPTION
**Pull request by achilep**
## Description of what I changed

i made the following change on liquibase-core 
org.liquibase:liquibase-core:3.8.9 --> 3.10.0

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5776

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@achilep thanks for working on this,could you try out your changes with reference application

**Comment by achilep** [comment]
thanks @HerbertYiga  I tried the new changes directly on the core by executing the jetty: run command and I installed a legacyUi module. and it worked without problem. cc @mozzy11  @sherrif10

**Comment by achilep** [comment]
OR would you like me to start the test again using the reference application? @HerbertYiga

**Comment by achilep** [comment]
is Ok i have try it with the standalone reference  application

**Comment by HerbertYiga** [comment]
@achilep  thats ok

**Comment by dkayiwa** [comment]
@achilep any reason why you upgraded to just this version but not any other?

**Comment by mozzy11** [comment]
@achilep  , we have more later versions that this , can you update to the latest version instead ??

**Comment by achilep** [comment]
@dkayiwa  and @mozzy11  thanks, I created the Ticket before they released the latest version 3.10.0 on June 11, 2020 and when I did the PR I did not know that they had already released another version. I will update the PR.

**Comment by achilep** [comment]
hello @dkayiwa i corrected it .
Screenshot from 2020-06-17 10-09-27

**Comment by dkayiwa** [comment]
Did you also update the ticket and pull request descriptions?

**Comment by mozzy11** [comment]
wel done @achilep

**Pull request merged**
