### PR TITLE
TRUNK-4256 Inconsistency between inheritedRoles and childRoles of a role

### PR DESCRIPTION
**Pull request by sumangala028**
## Description of what I changed

It will ensure that the issue about "Unique index or primary key violation" as it tries to put the relationship twice into role_role does not exist in the OpenMRS Core right now.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-4256

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by wluyima** [comment]
Looks like the summary of this ticket doesn't match the ticket

**Comment by wluyima** [comment]
I've updated it

**Comment by Ben-Waters** [comment]
Can you update the commit message to reference the jira
"TRUNK-4256 Your Message Here"

**Comment by Ben-Waters** [comment]
@sumangala028  Hey from the [PR tips page](https://wiki.openmrs.org/display/docs/Pull+Request+Tips)

Help us help you. Use a meaningful message for the pull request. **This message should tell us what the pull request is all about, and include the ticket number**. If you are not sure of what this message should be, at least use the ticket summary, as it appears in JIRA.


It looks like sometimes people miss it, but it's a good practice for keeping track of things.

**Comment by dkayiwa** [comment]
@sumangala028 are you still working on this?

**Comment by dkayiwa** [comment]
@sumangala028 ping me to reopen if you would like to continue working on this.

**Pull request closed without merging**
