### PR TITLE
Trunk 4454

### PR DESCRIPTION
**Pull request by zak905**
Ticket: TRUNK-4454
Hide 'Show N entries' on the patient dashboard under encounters since this is now configurable or let the configured number show there or when hide this when the configured number to display doesn't exceed or equal to 100
Also go through all pages where 'Show N entries' is displayed and do the same, for-example when a user searches for a patient at http://uat01.openmrs.org:8080/openmrs/admin/patients/index.htm and no or less patients are returned, hide this element. Link: https://issues.openmrs.org/browse/TRUNK-4454

### CODE REVIEW

**Comment by dkayiwa** [comment]
@zak905 can you squash these commits into one as advised at? http://go.openmrs.org/pull-request-tips

**Comment by dkayiwa** [comment]
Can you also always include at least the ticket summary in the pull request message as advised at http://go.openmrs.org/pull-request-tips?

**Comment by zak905** [comment]
Sure.

**Comment by dkayiwa** [comment]
@zak905 do you mind squashing these commits into one?

**Comment by dkayiwa** [comment]
Closing because change request was cancelled

**Pull request closed without merging**
