### PR TITLE
TRUNK-5771: Upgrade com.fasterxml.jackson.core to 2.11.0

### PR DESCRIPTION
**Pull request by achilep**
## Description of what I changed

I change the version of the following dependencies :
com.fasterxml.jackson.core:jackson-core:2.9.8 --> 2.11.0

com.fasterxml.jackson.core:jackson-annotations:2.9.8 --> 2.11.0

com.fasterxml.jackson.core:jackson-databind:2.9.10.4 --> 2.11.0

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5771

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@achilep can you now run the reference application with these changes?

**Comment by achilep** [comment]
thanks @dkayiwa

**Comment by dkayiwa** [comment]
@achilep does that mean you have done it?

**Comment by achilep** [comment]
not yet @dkayiwa .

**Comment by achilep** [comment]
sorry for the late response. I had this error"Unable to create the database. The password might be incorrect or the database is not started.

???Error executing sql: create database if not exists ? default character set utf8 - Could not create connection to database server. Attempted reconnect 3 times. Giving up."
. After 2 days of research I finally managed to solve it.
@dkayiwa  @sherrif10

**Comment by achilep** [comment]
This can go or? 
Screenshot from 2020-06-09 20-50-33

**Comment by sherrif10** [comment]
Did you add legacyui module into your server?

**Comment by achilep** [comment]
nor i did not add any legacyui @sherrif10  .  I only had to make sure that the core works normally with the new changes .

**Comment by achilep** [comment]
hello @dkayiwa  finally i succeed to test it and its working without a problem .thanks @sherrif10  and @mozzy11 
Screenshot from 2020-06-11 22-22-43

**Comment by achilep** [comment]
tested with the standalone reference application:
file:///home/guy/Pictures/Screenshot%20from%202020-06-16%2009-18-09.png
cc @dkayiwa @mozzy11

**Pull request merged**
