### PR TITLE
Trunk 5890 Privilege Domain - Switching from Hibernate Mappings to Annotations

### PR DESCRIPTION
**Pull request by abertnamanya**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5890

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by abertnamanya** [comment]
Ticket Link: https://issues.openmrs.org/browse/TRUNK-5890

**Review by tendomart — COMMENTED** [review]
@abertnamanya  before i even make any more comments .

Did you have time to look at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

1. You need a Ticket Title so that the reviewers quickly know what you're doing.
2. The link to the JIRA board should be in the descriptions section , not anywhere you want.

**Comment by abertnamanya** [comment]
> @abertnamanya before i even make any more comments .
> 
> Did you have time to look at https://wiki.openmrs.org/display/docs/Pull+Request+Tips
> 
> 1. You need a Ticket Title so that the reviewers quickly know what you're doing.
> 2. The link to the JIRA board should be in the descriptions section , not anywhere you want.

Thank you @tendomart let me work on those highlighted queries

**Comment by HerbertYiga** [comment]
@abertnamanya did you see the build failure on this?

**Pull request closed without merging**
