### PR TITLE
[GCI-142]Replaced log with logger

### PR DESCRIPTION
**Pull request by Devanshk9**
## Description of what I changed
In this issue, I resolved a problem which was indicated by sonar.
 I rename the "log" logger to comply with the format "LOG(?:GER)? in concept.java
;- https://sonar.openmrs.org/code?id=org.openmrs%3Aopenmrs&selected=org.openmrs.api%3Aopenmrs-api%3Asrc%2Fmain%2Fjava%2Forg%2Fopenmrs%2FConcept.java

## Issue I worked on
This was done under a GCI task
see https://issues.openmrs.org/browse/GCI-142

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by khush3211** [comment]
Can we use Log4j2 annotation from Lombok instead of creating logger in each java class? Same goes for Getters/Setters/Constructors etc as well.

https://projectlombok.org/api/lombok/extern/log4j/Log4j2.html

**Comment by anudeep10878** [comment]
Can we use Log4j2 annotation from Lombok instead of creating logger in each java class? Same goes for Getters/Setters/Constructors etc as well.
https://projectlombok.org/api/lombok/extern/log4j/Log4j2.html

**Comment by Devanshk9** [comment]
> Can we use Log4j2 annotation from Lombok instead of creating logger in each java class? Same goes for Getters/Setters/Constructors etc as well.
> 
> https://projectlombok.org/api/lombok/extern/log4j/Log4j2.html

Hi @f4ww4z @khush3211 I think we should not use this because of its disadvantages- https://stackoverflow.com/questions/4589184/what-are-the-risks-with-project-lombok &  https://medium.com/@vgonzalo/dont-use-lombok-672418daa819

**Comment by HerbertYiga** [comment]
you can have a better description for your ticket

**Comment by ibacher** [comment]
> Can we use Log4j2 annotation from Lombok instead of creating logger in each java class? Same goes for Getters/Setters/Constructors etc as well.
> [projectlombok.org/api/lombok/extern/log4j/Log4j2.html](https://projectlombok.org/api/lombok/extern/log4j/Log4j2.html)

Whether or not Lombok is a good idea for core, we'd first need to be able to use log4j2 🙂. See [TRUNK-5113](https://github.com/openmrs/openmrs-core/pull/3065).

**Comment by dkayiwa** [comment]
Can you make the commit message better that just `update concept`?

**Pull request closed without merging**
