### PR TITLE
TRUNK-4253  PatientService.savePatient isn't threadsafe and can allow duplicate patient identifiers

### PR DESCRIPTION
**Pull request by achilep**
# TRUNK-4253: PatientService.savePatient isn't threadsafe and can allow duplicate patient identifiers.
## Description of the changed
i have added synchronized in before the method.

### CODE REVIEW

**Comment by achilep** [comment]
I have updated it

**Comment by achilep** [comment]
Hello @jayasanka-sack

**Comment by achilep** [comment]
sir @alinmihaila99 i have added the synchronize before the method . thank you for feedback

**Comment by alinmihaila99** [comment]
The security/snyk is failing, are you up to date with the last changes in the project?

**Comment by alinmihaila99** [comment]
This should help you :)
git checkout -b tmp upstream/master
git cherry-pick (sha code of the commit)
# finally let's push off the new TRUNK-4253
git push -f origin tmp:branchYouWantToPush

**Comment by achilep** [comment]
thank you please is it ok

**Pull request closed without merging**
