### PR TITLE
TRUNK-4469 : Add validation to prevent a coded concept have itself as an answer

### PR DESCRIPTION
**Pull request by aj-jaswanth**

### CODE REVIEW

**Comment by dkayiwa** [comment]
I see lots of formatting changes. Do you mind separating the formatting from the rest of the actual changes?

**Comment by aj-jaswanth** [comment]
@dkayiwa If I don't throw an exception there, I get the exception to commit to the database. The stack trace is here as posted earlier. https://issues.openmrs.org/browse/TRUNK-4469?focusedCommentId=223596&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-223596

**Comment by dkayiwa** [comment]
@aj-jaswanth do you have a unit test to reproduce this?

**Comment by aj-jaswanth** [comment]
@dkayiwa No. I wrote the unit test only for the ConceptValidator class.

**Comment by aj-jaswanth** [comment]
It is throwing exception exactly here. https://github.com/openmrs/openmrs-core/blob/1.12.x/web/src/main/java/org/openmrs/web/controller/ConceptFormController.java#L391.

**Pull request closed without merging**
