### PR TITLE
Apptest 52

### PR DESCRIPTION
**Pull request by ern2**
This pull request accompanies JIRA ticket APPTEST-52 (https://issues.openmrs.org/browse/APPTEST-52).

The tests added in UpdateFileParserTest.java apply 65% branch coverage to UpdateFileParser.java, which as of now has no test coverage.  

I attempted to squash my commits, which is requested in the wiki page "Pull Request Tips", but could not get it to work properly.  I apologize for the messy commits, most of which are from cleaning up the master branch after committing to the wrong branches.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
What problems did you encounter trying to squash them?

**Comment by ern2** [comment]
After squashing, it would either undo all my changes, or it would not allow me to push without pulling first.  In both cases, all of the commits were not squashed into one, they still appeared as multiple commits on the branch. 

I used the "git reset --soft HEAD~x" command from the wiki page.

**Comment by robbyoconnor** [comment]
@ern2 you have to force-push after you squash your commits

**Comment by robbyoconnor** [comment]
@ern2 The reason is that you are re-writing the git history

**Comment by robbyoconnor** [comment]
@ern2  you do not need to do anything -- your changes will automatically be reflected here

**Comment by dkayiwa** [comment]
This looks messed up. Can you create a new one? 
Am also assuming you saw this: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by robbyoconnor** [comment]
You will need to force-push whenever you squash commits -- just for future knowledge.

**Comment by ern2** [comment]
Okay.  I am going to try squashing again with a force push.  I will link to a new pull request when it looks clean.  Thank you.

**Comment by ern2** [comment]
Here is the new pull request: https://github.com/openmrs/openmrs-core/pull/1762

I was able to squash into one commit without losing my changes.  Thanks for the help.

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67oik-r6&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=i9NVhJv9&invitationId=6130897025912356864








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67oik-r6&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGHe16qHy0fygAAAVRVSb2XamNTHBn-x2Xxvw_RHBhCM-_33vEVWFz_DV8tgdQlF1GcU4ExoSTolstBPWVZWHsSaCi2NMqaqFSzDUcBu4NfFPY3g0vP5EsIKNB24blE62XwVziw3X8GIWYFQwv3Xc1rpforNW5S7Q76PZCsbvO9Tv8AWcRW69ILCPHgPewK6cCS&eid=0-ini67oik-r6


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67oik-r6&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
