### PR TITLE
TRUNK-6190 Add fulfiller location in orders

### PR DESCRIPTION
**Pull request by slubwama**
## Description of what I changed
In the Order Object I have added a field fulfillerLocation. This has also lead to changes in tests are assoriated. The affacted test classes are DrugOrderTest.java, OrderTest.java, ReferralOrderTest.java, TestOrderTest.java in test cloneForRevision_shouldSetAllTheRelevantFields

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-6190

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> Write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> Execute the above command

- [ ] All new and existing **tests passed**.

  No? Could you figure out why and add the fix to your commit? It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master

### CODE REVIEW

**Comment by dkayiwa** [comment]
@slubwama this being a new feature which we do not usually back port to previous versions, what is your plan for using it? Are you planning to upgrade your sites to the next platform release in order to take advantage of this?

**Comment by slubwama** [comment]
> @slubwama This is a new feature that we do not usually backport to previous versions, What is your plan for using it? Are you planning to upgrade your sites to the next platform release in order to take advantage of this?

@dkayiwa  that depends on how fast the 2.7.x series gets released.  The reason why I had thought of backporting was to reduce the turnaround time.

**Comment by dkayiwa** [comment]
What plan do you have if 2.7 does not get released as fast as you will need?

**Comment by slubwama** [comment]
> What plan do you have if 2.7 does not get released as fast as you will need?

Backport was the plan. But since its not advised we may have to wait it out.

**Comment by dkayiwa** [comment]
Let us use [order attributes](https://issues.openmrs.org/browse/TRUNK-6027), for now.

**Comment by slubwama** [comment]
> Let us use [order attributes](https://issues.openmrs.org/browse/TRUNK-6027), for now.

@dkayiwa This is noted and followed up with the ticket and PR to ensure OrderAttributes do have REST Support before we can create fhir apis

**Comment by dkayiwa** [comment]
@slubwama are you still working on this? Or do you still need this guy?

**Comment by slubwama** [comment]
Yes. This work we had just paused it but we have an active sprint  next
week we're this come back to the top.

**Pull request closed without merging**
