### PR TITLE
TRUNK-5500:Upgrade Apache commons library from 3.6.0 to 3.9.0

### PR DESCRIPTION
**Pull request by jwnasambu**
## Description of what I changed
 I upgraded Apache commons library from 3.6.0 to 3.9.0

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5500

### CODE REVIEW

**Comment by jwnasambu** [comment]
@dkayiwa kindly review my work at your convenient time.

**Comment by mozzy11** [comment]
looks to me its ok. cc @dkayiwa

**Comment by dkayiwa** [comment]
@mozzy11 what is the name of the artifact being upgraded?

**Comment by mozzy11** [comment]
@dkayiwa  its `org.apache.commons:commons-lang3` from 3.6 -> 3.9

**Comment by dkayiwa** [comment]
Is that reflected in the ticket, pull request, and commit message?

**Comment by mozzy11** [comment]
@jwnasambu can you update your commit messages and PR description with the exact library name ?

**Pull request closed without merging**
