### PR TITLE
GCI-142: fixed minor bugs in js

### PR DESCRIPTION
**Pull request by ShobhitRathi**
## Description of what I changed
1. Add curly braces around the nested statement(s) in this "if" block **&**
2. Replace "==" with "==="

**Issue** [link](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&open=AWCS0QlUvsycEPA9_R41&resolved=false&rules=javascript%3ACurlyBraces)
Openmrs [ticket id](https://issues.openmrs.org/issues/?filter=-2)

## Issue I worked on
_OpenMRS_ [Issue page](https://issues.openmrs.org/browse/GCI-142)
_Google Code-in 2019_ [task](https://codein.withgoogle.com/dashboard/task-instances/5161208928272384/)

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by ShobhitRathi** [comment]
I was having trouble with squashing all the commits together so I closed down that PR and made a new one.

All the changes have been made now and are in a single commit. Hope I didn't miss anything now
thanks 😃

**Comment by dkayiwa** [comment]
Can you include the ticket id in your commit message as recommended at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by ShobhitRathi** [comment]
Done Added the ticket ID

**Comment by dkayiwa** [comment]
This is a jquery library which we did not write. If there are any fixes to make to it, they should happen from the jquery repository.

**Pull request closed without merging**
