### PR TITLE
Add support for module development using docker

### PR DESCRIPTION
**Pull request by corneliouzbett**
## Description of what I changed

This PR defines the local environment for module development using docker. Basically, I'm modifying the `openmrs:dev` image to be based on tomcat, download and install maven then setup OpenMRS SDK. These are necessary for:

- Downloading required modules specified in the `module.properties` file
- Build the current module

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by jwnasambu** [comment]
@corneliouzbett Kindly you forgot to include the ticket id on this PR.

**Comment by rkorytkowski** [comment]
Thanks! Code-wise it's looking good. I will be testing it tomorrow and hopefully it can be merged in.

**Comment by rkorytkowski** [comment]
When I start up openmrs-core without specifying any module.properties it fails with openmrs-core_1  | wait-for-it.sh: db:3306 is available after 5 seconds
openmrs-core_1  | Specified required modules in the /openmrs/module/source/module.properties file.
openmrs-core_1  | POM file /openmrs/module/source/pom.xml specified with the -f/--file command line argument does not exist
openmrs-core_1  | [INFO] Scanning for projects...
openmrs-core_1  | [ERROR] [ERROR] Some problems were encountered while processing the POMs:
openmrs-core_1  | [FATAL] Non-readable POM /openmrs/module/source/pom.xml: /openmrs/module/source/pom.xml (No such file or directory) @ 
openmrs-core_1  |  @ 
openmrs-core_1  | [ERROR] The build could not read 1 project -> [Help 1]
openmrs-core_1  | [ERROR]   
openmrs-core_1  | [ERROR]   The project  (/openmrs/module/source/pom.xml) has 1 error
openmrs-core_1  | [ERROR]     Non-readable POM /openmrs/module/source/pom.xml: /openmrs/module/source/pom.xml (No such file or directory)
openmrs-core_1  | [ERROR] 
openmrs-core_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
openmrs-core_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
openmrs-core_1  | [ERROR] 
openmrs-core_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
openmrs-core_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Review by rkorytkowski — CHANGES_REQUESTED** [review]
See my comment on the PR. openmrs-core fails to start if module.properties is missing.

**Comment by corneliouzbett** [comment]
> When I start up openmrs-core without specifying any module.properties it fails with
> 
> ```
> openmrs-core_1  | wait-for-it.sh: db:3306 is available after 5 seconds
> openmrs-core_1  | Specified required modules in the /openmrs/module/source/module.properties file.
> openmrs-core_1  | POM file /openmrs/module/source/pom.xml specified with the -f/--file command line argument does not exist
> openmrs-core_1  | [INFO] Scanning for projects...
> openmrs-core_1  | [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> openmrs-core_1  | [FATAL] Non-readable POM /openmrs/module/source/pom.xml: /openmrs/module/source/pom.xml (No such file or directory) @ 
> openmrs-core_1  |  @ 
> openmrs-core_1  | [ERROR] The build could not read 1 project -> [Help 1]
> openmrs-core_1  | [ERROR]   
> openmrs-core_1  | [ERROR]   The project  (/openmrs/module/source/pom.xml) has 1 error
> openmrs-core_1  | [ERROR]     Non-readable POM /openmrs/module/source/pom.xml: /openmrs/module/source/pom.xml (No such file or directory)
> openmrs-core_1  | [ERROR] 
> openmrs-core_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> openmrs-core_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> openmrs-core_1  | [ERROR] 
> openmrs-core_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
> openmrs-core_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> ```

I missed checking if the mounted module source exists before trying to build. The line below fails since the module source isn't mounted. Just pushed a fix for that.
```bash
mvn clean install -f "$MODULE_SOURCE_DIR/pom.xml" -DskipTests
find "$MODULE_SOURCE_DIR/omod/target" -name \*.omod -exec cp {} "$OMRS_MODULES_DIR" \;
```

**Comment by corneliouzbett** [comment]
Hey @rkorytkowski, did you get a chance to retest this?

**Comment by rkorytkowski** [comment]
Hey @corneliouzbett. Yes, it worked. I approve your changes. I need to do further tweaks to the setup before merging. Thank you for working on this!

**Comment by dkayiwa** [comment]
@rkorytkowski did you get a chance to do further tweaks?

**Pull request closed without merging**
