### PR TITLE
2.3.x revert

### PR DESCRIPTION
**Pull request by Ruhanga**
## Description of what I changed

a

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Ruhanga what commands did you use for this?

**Comment by Ruhanga** [comment]
I used  the following command `git revert revert_commit`

**Comment by dkayiwa** [comment]
What is `revert_commit`?

**Comment by Ruhanga** [comment]
Sorry @dkayiwa, I corrected my comment earlier to `git revert commit_to_rever` for example I this command below for the last commit in the sequence,  
`git revert 9c3a95fb93f63082711c84ce4724ab30c7b5dab1` for the last revert.

**Pull request merged**
