### PR TITLE
TRUNK-5983:Upgrade core in 2.4.x to 2.4.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by gitcliff**
link:https://issues.openmrs.org/browse/TRUNK-5983

### CODE REVIEW

**Comment by dkayiwa** [comment]
Are you trying to release again?

**Comment by gitcliff** [comment]
no am not ,,let me fix it

**Comment by dkayiwa** [comment]
Did you look at existing release branches?

**Comment by dkayiwa** [comment]
Is the commit message correct?

**Comment by gitcliff** [comment]
@dkayiwa I have made one commit ,,requesting for review

**Pull request merged**
