### PR TITLE
TRUNK-5067: Add tests to MessageServiceImpl

### PR DESCRIPTION
**Pull request by smoulem**
## Description of what I changed

TRUNK-5067 - Add tests for the various overloaded 'sendMessage'

As said above and stated in the Jira issue, I've just added tests for MessageServiceImpl; nothing else.
I think, adding beyond that here, would just paraphrase the names of the test methods.
Other changes are for configuration and dependencies.

There are dependencies to run [**Greemail**](https://greenmail-mail-test.github.io/greenmail/), to receive email messages from the test class.
And load Java beans from a xml file, to be used in the test class.

The MessageService bean, in the application/Openmrs context, was not suitable. 
I needed to create a mail Session that matches the default port used by Greenmail: 3025.
And a MessageService with a MessageSender which uses that Session.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-TRUNK-5067

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by jwnasambu** [comment]
@smoulem kindly include the description of what you changed. Beside, the link to the issue you worked on should be in the right position.

**Comment by smoulem** [comment]
> @smoulem kindly include the description of what you changed. Beside, the link to the issue you worked on should be in the right position.

No worries, will add some description if the one above isn't enough.
Will probably look at why the build fails first.
By the way, great 'Mini Community Meeting' today.

**Comment by smoulem** [comment]
> > @smoulem kindly include the description of what you changed. Beside, the link to the issue you worked on should be in the right position.
> 
> No worries, will add some description if the one above isn't enough. Will probably look at why the build fails first. By the way, great 'Mini Community Meeting' today.

How can I re-run the build on this PR to see if it passes/fails?
Thx

**Comment by dkayiwa** [comment]
@smoulem do you mind fixing the Jira link and merge conflicts?

**Comment by smoulem** [comment]
> @smoulem do you mind fixing the Jira link and merge conflicts?

@dkayiwa , that's an updated pull request which should solve the conflicts

**Pull request closed without merging**
