### PR TITLE
TRUNK-5997: Fix broken checkstyle configurations

### PR DESCRIPTION
**Pull request by xurror**
## Description of what I changed

Fix broken checkstyle configurations by updating xml definitions for checkstyle.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5997

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@xurror can you include a link to the ticket as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by bejanut** [comment]
Could you update your description in the checklist?

**Comment by xurror** [comment]
It's done.

**Comment by xurror** [comment]
> Are the changes already merged?

Still awaiting a maintainers approval and merging.

**Comment by bejanut** [comment]
> > Are the changes already merged?
> 
> Still awaiting a maintainers approval and merging.

I was suggesting that maybe you could check the boxes on the pull request to help the maintainers before merging.

**Review by BartlomiejRasztabiga — COMMENTED** [review]
I'm wondering whether we actually need all these reformatting changes apart from resolving the main issue. Also, you've checked the box that you've "added tests to cover your changes" and I don't see any :smile:

**Pull request closed without merging**
