### PR TITLE
GCI-142: Check bad code practices through Findbugs or Sonar and fix t…

### PR DESCRIPTION
**Pull request by sviho**
## Description of what I changed
My pull request fixed some small code issues. Particularly:

- "===" and "!==" should be used instead of "==" and "!=" in JS files

- String literals should not be duplicated

- Comments should not be located at the end of lines of code

- Loggers should be "private static final" and should share a naming convention: renaming the "log" logger to comply with the format "LOG(?:GER)?"

## Issue I worked on
https://issues.openmrs.org/browse/GCI-142

https://codein.withgoogle.com/dashboard/task-instances/5104606574018560/

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains ONE single commit
- [x] My IDE is configured to follow the [**code style**]
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] All new and existing **tests passed**.
- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by samuelmale** [comment]
@sviho did you just forget to put a link to yr task instance?

https://talk.openmrs.org/t/more-tips-for-making-good-pull-requests-for-gci-students/20318

**Comment by sviho** [comment]
@samuelmale I did. Thanks for the reminder!

**Comment by ykarim** [comment]
Looks good to me. @dkayiwa any comments?

**Comment by sviho** [comment]
@dkayiwa Done!
https://github.com/openmrs/openmrs-core/pull/2740
https://github.com/openmrs/openmrs-core/pull/2741
https://github.com/openmrs/openmrs-core/pull/2742

**Pull request closed without merging**
