### PR TITLE
TRUNK-5223: Add New User always throws exception of null string pointer instead of returns blank ("") character.

### PR DESCRIPTION
**Pull request by oslynn**
Ticket TRUNK-5223 issue is problem with Add New User always throws
   exception of null string pointer.

   Resolved it by revert the code back to commit
   acf93745f5ce982d762974b5a0138feed1020e39

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5223

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you fix the ticket link on the pull request?
Instead of "Resolved the ticket" for the pull request text, can you at least use the ticket title?
Did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by oslynn** [comment]
Dkayiwa,  I had looked at the link  https://wiki.openmrs.org/display/docs/Pull+Request+Tips and followed accordingly.  Forgive me and perhaps, I don't understand what you want me to do by - "Instead of "Resolved the ticket" for the pull request text, can you at least use the ticket title?"  I am not familiar with openmrs code submitting process.

**Comment by dkayiwa** [comment]
I have just edited our pull request tips page. Can you take a second look?

**Comment by oslynn** [comment]
@Daniel, who will close the pull request.  If I should close, how do I know the fix has been reviewed and merge into the master?

**Pull request merged**
