### PR TITLE
TRUNK-4644 "Correctness - Possible null pointer dereference"

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by tomaszmueller** [comment]
@rkorytkowski https://issues.openmrs.org/browse/TRUNK-4644

**Comment by dkayiwa** [comment]
@tomaszmueller can you always run mvn clean install before committing as advised at? http://go.openmrs.org/pull-request-tips

**Comment by tomaszmueller** [comment]
@dkayiwa fixed formatting issues

**Comment by tomaszmueller** [comment]
@dkayiwa updated

**Comment by tomaszmueller** [comment]
@dkayiwa changed

**Pull request merged**
