### PR TITLE
TRUNK-5846: Checking the variable type before casting

### PR DESCRIPTION
**Pull request by njiddasalifu**
Issue fix on validator classes 
TRUNK-5846: checking variable before casting in validator 
https://issues.openmrs.org/browse/TRUNK-5845
## Description of what I changed
I added a check of variable type before casting in the validator classes as per the issue demands.

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5845

### CODE REVIEW

**Comment by jwnasambu** [comment]
@njiddasalifu kindly where does information ```
`Issue fix on validator classes 
TRUNK-5846: checking variable before casting in validator 
https://issues.openmrs.org/browse/TRUNK-5845` 
```
above supposed to be? If it doesn't fall in any of the 2 categories i.e. Description of what I changed and Issue I worked on, kindly delete it or else ensure its at the correct position.

**Comment by dkayiwa** [comment]
Did you also see the maven build failure?

**Comment by njiddasalifu** [comment]
Thank you @jwnasambu and  @dkayiwa for your review and comments. 
Working to get it up.

**Review by TripleStarCodeHunter — COMMENTED** [review]
Good job @njiddasalifu 
It is usually better to keep the branch name same as the ticket name (as per the OpenMRS guidelines).
You can find more information here : https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request closed without merging**
