### PR TITLE
GCI-90: Fix three critical issues on OpenMRS sonarqube.

### PR DESCRIPTION
**Pull request by collinsgeek**
Removed inefficient use of keySet iterator instead of entrySet
Replaced inefficient new Long(long) constructor with Long.valueOf(long)

### CODE REVIEW

**Comment by collinsgeek** [comment]
Hi Sir @Ch3ck , I tried that but it doesn't work since localized.values() returns a collection of PresentationMessageMap() while allMessage.addAll() is expecting a collection of PresentationMessage. I tried making the former to work for over 3 hours and still no avail. This was the best solution in this case. At least I discard the entrSet use case here.

**Comment by Ch3ck** [comment]
Ok @collinsgeek  I see, but that's odd though since PresentationMessageMap implements PresentationMessage. It's supposed to return a PresentationMessage collection. Any ways good work with this.

@dkayiwa  @rkorytkowski  Any thoughts on this?

LGTM

**Comment by robbyoconnor** [comment]
I'm not familiar with the codebase

**Comment by Ch3ck** [comment]
Alright, any ways thanks for sticking with this @collinsgeek. But  If @dkayiwa  or @rkorytkowski  have any issues with this; you will have to fix it.

**Comment by collinsgeek** [comment]
Hi Sir, @Ch3ck @dkayiwa 

I will make the changes and submit.

**Comment by Ch3ck** [comment]
Nice work @collinsgeek  @dkayiwa I think you could merge this now. Let me go and approve this!

**Pull request merged**
