### PR TITLE
TRUNK-6242: editing the hydrate() to fetch concepts by id/Uuid/mappings by replacing ConceptService#getConcept() with  ConceptService#getConceptByReference()

### PR DESCRIPTION
**Pull request by josephbate**
## Description of what I changed

Replaced the `ConceptService#getConcept() ` with `ConceptService#getConceptByReference()`

## Issue I worked on

see https://openmrs.atlassian.net/browse/TRUNK-6242

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by josephbate** [comment]
hello @ibacher please review this pr

**Review by ibacher — APPROVED** [review]

**Comment by dkayiwa** [comment]
@ibacher is this intentionally backwards incompatible?

**Comment by ibacher** [comment]
>  is this intentionally backwards incompatible?

@dkayiwa `getConceptByReferences()` supports numeric values as strings, so this should be completely backwards compatible. See [here](https://github.com/openmrs/openmrs-core/blob/8d3e65b48ea3d41c1270c609a081b363849c8c41/api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java#L368).

**Comment by dkayiwa** [comment]
Oh i see!!! That is awesome! 😊

**Comment by josephbate** [comment]
thank you @ibacher  and @dkayiwa 
should i continue with writing the testcases?
Cc. @ibacher

**Comment by ibacher** [comment]
@josephbate Yes, please do so as a separate PR.

**Comment by josephbate** [comment]
i am Facing java.lang.UnsupportedClassVersionError when ever am trying to run a test 
 do you have any quick fix for this 
@ibacher @dkayiwa 

```
java.lang.UnsupportedClassVersionError: org/mockito/session/MockitoSessionLogger has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass([ClassLoader.java:756](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.security.SecureClassLoader.defineClass([SecureClassLoader.java:142](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.net.URLClassLoader.defineClass([URLClassLoader.java:473](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))java.lang.UnsupportedClassVersionError: org/mockito/session/MockitoSessionLogger has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass([ClassLoader.java:756](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.security.SecureClassLoader.defineClass([SecureClassLoader.java:142](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.net.URLClassLoader.defineClass([URLClassLoader.java:473](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))java.lang.UnsupportedClassVersionError: org/mockito/session/MockitoSessionLogger has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass([ClassLoader.java:756](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.security.SecureClassLoader.defineClass([SecureClassLoader.java:142](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.net.URLClassLoader.defineClass([URLClassLoader.java:473](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
```
is this to do

**Pull request merged**
