### PR TITLE
Fix for report 492

### PR DESCRIPTION
**Pull request by ThisuraThejith**
Introduced contextual encoding methods to prevent XSS attacks and delegated to OWASP Encoder.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1: <3 <3 <3 <3 Great work :100: :tada: (Can't merge -- jus like it)

**Comment by dkayiwa** [comment]
@ChamaraPhilipsuom do you mind squashing the commits into one? :)
https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by ThisuraThejith** [comment]
@dkayiwa  I will squash the commits into one and send the PR again. @ChamaraPhilipsuom is the user of this laptop. Hence the commit name has came by his name. Shall I send the PR again or just commit here again?

**Comment by dkayiwa** [comment]
@ThisuraThejith whatever you find convenient. As long as the pull request ends up with one commit. :)

**Comment by ThisuraThejith** [comment]
@dkayiwa Closed this PR and sent https://github.com/openmrs/openmrs-core/pull/1643

**Comment by ThisuraThejith** [comment]
@robbyoconnor Thank you very much lad. This PR is moved to #1643

**Comment by robbyoconnor** [comment]
In the future -- you don't need to close PRs -- if you push changes to a branch which has an open PR, changes will be reflected there...

**Comment by ThisuraThejith** [comment]
ok robby. Nice to learn these things. Will do next time. (Y)

**Pull request closed without merging**
