### PR TITLE
Updating liquibase snapshots

### PR DESCRIPTION
**Pull request by tendomart**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

@ibacher    is this your expectation

cc @dkayiwa

### CODE REVIEW

**Comment by dkayiwa** [comment]
@tendomart what is the use of these empty files?

**Comment by tendomart** [comment]
They're supposed to be for  liquibase-snapshots , but i was thinking the changes should be introduced in the next iteration

**Comment by dkayiwa** [comment]
@tendomart but they should not be empty. Did you carefully follow those instructions?

**Comment by tendomart** [comment]
I did , but let me crosscheck for clarity.

**Comment by dkayiwa** [comment]
@tendomart do we still need this pull request?

**Comment by tendomart** [comment]
Sorry this has been long since i responded .But i saw you take up a ticket related to this. 

Let me close it .But i'd like also to see how you approached this.

**Comment by tendomart** [comment]
BTW is this still in progress or post commit https://issues.openmrs.org/browse/TRUNK-6058

**Comment by dkayiwa** [comment]
The bamboo part is not yet done.

**Comment by tendomart** [comment]
Okk .

**Pull request closed without merging**
