### PR TITLE
TRUNK-6133 - Expand Listener to implement HttpSessionListener

### PR DESCRIPTION
**Pull request by mseaton**
See:  https://issues.openmrs.org/browse/TRUNK-6133

Interested in your thoughts on this PR @dkayiwa / @ibacher  / @mogoodrich

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mseaton is it supposed to be an enhancement for this? https://issues.openmrs.org/browse/TRUNK-5416

**Comment by mseaton** [comment]
> @mseaton is it supposed to be an enhancement for this? https://issues.openmrs.org/browse/TRUNK-5416

In a sense.  I'm aware of that feature in OpenMRS, the limitation of it is that it is purely an API-level feature and isn't actually tied into the session lifecycle in the servlet container (i.e. Tomcat).  It only really knows when the API has been actively logged into or logged out of, and what user did it.  There is no ability to know what session this is tied to, there is no knowledge of any data in the session or attached to the request, like the user's IP address, and there is no way to detect if the user is logged out passively (due to inactivity and session expiry by the servlet container - which for Tomcat defaults to 30 minutes), etc.  

So I think it would would be difficult/impossible to build certain features - for example, one that could accurately say how many users are currently logged in (because you wouldn't know about users who were passively logged out by the servlet container).

So it's complementary to the existing feature.  It doesn't really duplicate it.  I could see adding an HttpSessionListener implementation to core (or even just adding a method call directly in the Listener.sessionDestroyed() method that calls Context.logout() if the session has been destroyed and Context.isAuthenticated() is true.  This would then cascade to notify the UserSessionListener of the logout event.  But I left that as outside the scope of this feature.  Something to consider though.

**Comment by dkayiwa** [comment]
> I could see adding an HttpSessionListener implementation to core (or even just adding a method call directly in the Listener.sessionDestroyed() method that calls Context.logout() if the session has been destroyed and Context.isAuthenticated() is true. This would then cascade to notify the UserSessionListener of the logout event. But I left that as outside the scope of this feature. Something to consider though.

Yes i would consider adding that because it makes lots of sense! 👍

**Comment by ibacher** [comment]
Yes, this is an extremely useful feature to have, if a bit niche. As I recall, the chief difficulty replicating the 1.x "View Logged In Users" functionality was the inability to track expired sessions accurately.

**Comment by mseaton** [comment]
Cool, good to hear this is useful.  Wondering on thoughts about backporting to 2.5.x.  Thoughts on that?  @dkayiwa / @ibacher ?

**Comment by dkayiwa** [comment]
> Wondering on thoughts about backporting to 2.5.x

No objection from me. 😊

**Comment by mogoodrich** [comment]
Belated LGTM... I guess I'm always a little fearful of backporting functionality that touches "everything", no matter how benign... but we will be using this right away and hopefully in the near term testing on a large scale implementation, so we should be able to debug as need be.

**Pull request merged**
