### PR TITLE
GCI-142: Removed APIException

### PR DESCRIPTION
**Pull request by Bisht13**
## Description of what I changed
One of my changes from my PR #2780
Removing APIException
Sonar errors:-
https://goo.gl/3386fk
https://goo.gl/kLi4JP
https://goo.gl/KFE81t
https://goo.gl/1UVjLa
https://goo.gl/rR5MEx
https://goo.gl/27NHJX
https://goo.gl/vv1gza
https://goo.gl/g3AWcX
https://goo.gl/ZKkQ9U

## Issue I worked on
see https://issues.openmrs.org/browse/GCI-142
Task Instance https://codein.withgoogle.com/dashboard/task-instances/6187644498214912/

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**

- [x] My IDE is configured to follow the [**code style**]

- [x] I have **added tests** to cover my changes. 

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Why are you removing the API Exception?

**Comment by Bisht13** [comment]
Sonar pointed it out saying as it is a runtime exception it'll never run

**Comment by dkayiwa** [comment]
You need to give details of that. Or at least a link explaining so.

**Comment by Bisht13** [comment]
Should I write it in the PR itself?

**Comment by dkayiwa** [comment]
Whatever you can do to empower the reviewer with knowledge as to why you are raising this pull request. 😊

**Comment by Bisht13** [comment]
@dkayiwa alright 😊

**Comment by Bisht13** [comment]
I added the Sonar Issues in the PR itself. I hope this is sufficient 😃

**Comment by dkayiwa** [comment]
Thanks @Bisht13 👍

**Pull request merged**
