### PR TITLE
GCI-172:ModuleFilter Logger should be 'private static final'

### PR DESCRIPTION
**Pull request by Wandji69**
https://issues.openmrs.org/browse/GCI-172

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by tenas97** [comment]
@Wandji69 The task description stated that you change the variable `protected final Logger log = LoggerFactory.getLogger(getClass());` to `private static final Logger log = LoggerFactory.getLogger(ModuleFilter.class);
`. I can not see that being done in your code, you just deleted a bunch of comments. Any reason for that?

**Comment by Andu033** [comment]
@Wandji69  did you checked the travis failure?

**Comment by Wandji69** [comment]
Yes. I did that because looking at the latest changes on my branch and in
the file i release that the requested change has already been done.

**Comment by dkayiwa** [comment]
@Wandji69 am closing this because i do not see any useful change in it.

**Pull request closed without merging**
