### PR TITLE
RESTWS-658, expose isPatient via web service

### PR DESCRIPTION
**Pull request by cioan**
Hi @mseaton and @mogoodrich , here is the small change we need to make to the Person in order to expose isPatient via the web service. This is already present in the master branch but it was never merged down to 1.10.x, the version we use at Mirebalais. Thanks.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@cioan did you just forget assigning yourself to this ticket?

**Comment by cioan** [comment]
@mseaton : Can you please merge this change? Thanks.

**Comment by wluyima** [comment]
I thought this is a RESTWS ticket and not openmrs core, please re-read the ticket description https://issues.openmrs.org/browse/RESTWS-658

**Comment by mogoodrich** [comment]
@wluyima  I think this went through some design discussion, and it's really a question of backporting (part) of a previous trunk commit.

@cioan it would make sense to close this one out and comment on the original trunk ticket that added the getIsPatient saying you'd like to backport it... (I was looking at that trunk ticket last week, but don't have the ticket number handy anymore)

**Comment by cioan** [comment]
Thanks @mogoodrich . It looks like you already commented on [TRUNK-2205](https://issues.openmrs.org/browse/TRUNK-2205?focusedCommentId=237907&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-237907).
RESTWS-658 could remain open because it was re-written by Darius to address other issues with person links.

**Comment by mogoodrich** [comment]
Thanks for the link to the ticket @cioan!  Sorry, I meant we should close this pull request (because when we do backport we want the commit message to reflect TRUNK-2205, not the REST ticket... I agree that the REST ticket itself can stay open... I will close this out (and comment further on TRUNK-2205).

**Pull request closed without merging**
