### PR TITLE
TRUNK-6161: Remove dependency org.azeckoski:reflectutils

### PR DESCRIPTION
**Pull request by sibendire**
## Description of what I changed
I replaced usage of org.azeckoski.reflectutils library with standard Java reflection APIs
Sets the accessibility of each field to true to handle private fields
Returns a list of all fields found

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-6161

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by mherman22 — COMMENTED** [review]
Thanks for taking your time @sibendire and working on this. Ensure to have a description and title for this pull request and add the ticket ID you're workingon.

- Please refer to the pull request tips at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by tendomart** [comment]
Did you look into this

`Error:    ReflectTest.isCollectionField_shouldReturnTrueIfGivenFieldIsCollectionAndItsElementTypeIsGivenParameterized:153 expected: <subClassField> but was: <nonCollectionField>`

**Comment by sibendire** [comment]
@tendomart I have Refactor the test method for checking collection fields in ReflectTest.
@mherman22 Thank you your guidance I found it hard to fix the command since I had already made the PR but I believe next time will be better or If there is a way of editing its highly welcomed.

Thank you guys for your guidance.

**Comment by tendomart** [comment]
@sibendire Make the Title of the ticket similar to what you're doing in this PR.

**Comment by sibendire** [comment]
Hello @dkayiwa I fixed the changes and all checks passed now to I think needs to be merged

**Comment by jwnasambu** [comment]
@sibendire Kindly add the description of what you changed please!

**Comment by sibendire** [comment]
I  Replaced usage of org.azeckoski.reflectutils library with standard Java reflection APIs
  Sets the accessibility of each field to true to handle private fields
  Returns a list of all fields found
@jwnasambu

**Comment by sibendire** [comment]
@jwnasambu I observed that there two issue with the same ID but different tittles and descriptions for the case this PR refer to
https://issues.openmrs.org/browse/TRUNK-6161?filter=-3

**Comment by sibendire** [comment]
Thank you @jwnasambu for that correction I have changed

**Comment by jwnasambu** [comment]
@sibendire kindly have you added the description of what you changed!

**Comment by sibendire** [comment]
Thank you @jwnasambu  for your kind response.
Could guide me on how to add the description because I have added that description in JIRA.

**Comment by jwnasambu** [comment]
@sibendire kindly you need to add a description of what you changed to guide the person reviewing your work. Kindly check what I have just fixed and edit it to match what you fixed.

**Comment by jwnasambu** [comment]
@sibendire Kindly why do you have 2 PR open for one ticket? [This](https://github.com/sibendire/openmrs-core/pull/1) and [this](https://github.com/openmrs/openmrs-core/pull/4346) one?

**Comment by sibendire** [comment]
Thank you @jwnasambu for  action taken I changed the working environment after the first PR then after that I made changes which is now in this current PR . 
Now I think one needs to be closed. Is it so?

**Comment by jwnasambu** [comment]
@sibendire True!

**Comment by jwnasambu** [comment]
@sibendire after closing the PR reference it on this PR for the commend will help in review process.

**Comment by dkayiwa** [comment]
Most of this work was done by @wikumChamith at https://github.com/openmrs/openmrs-core/pull/4416

**Pull request closed without merging**
