### PR TITLE
TRUNK-5517 Upgrade commons Libraries

### PR DESCRIPTION
**Pull request by Irenyak1**
## Description of what I changed

I Upgraded library commons sub-Libraries as below     

    1. commons-fileupload:commons-fileupload … 1.3.3  to 1.4
    2. commons-io:commons-io … 2.5  to 2.6
    3. commons-validator:commons-validator … 1.4.0 to 1.6

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5517

## Checklist: I completed these to help reviewers :)

- [x ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by ODORA0** [comment]
This looks good enough

**Comment by Irenyak1** [comment]
Hello @dkayiwa  please may you review this pull request when you find time.

**Comment by dkayiwa** [comment]
Did you just forget to include the ticket id in the commit message?

**Comment by Irenyak1** [comment]
oh sure @dkayiwa I forgot. Let me fix it.

**Comment by Irenyak1** [comment]
Hello @dkayiwa  I have worked on the commit message and I have included the ticket Id. Please may you review my PR when you find time.

**Comment by dkayiwa** [comment]
Are these the latest versions available for each of the dependencies?

**Comment by Irenyak1** [comment]
@dkayiwa ,From my search, yes those are the latest versions available

**Comment by dkayiwa** [comment]
@Irenyak1 did you upgrade all the libraries mentioned on the ticket?

**Comment by Irenyak1** [comment]
@dkayiwa  As I commented on the ticket, I did not upgrade "commons-collections:commons-collections … 3.2.2 "
because it was already up to date

**Pull request merged**
