### PR TITLE
TRUNK-5065: Add tests to AdministrationServiceImpl

### PR DESCRIPTION
**Pull request by PKatGITHUB**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5065

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by teleivo** [comment]
@PKatGITHUB awesome!!!

**Comment by PKatGITHUB** [comment]
Thank you @teleivo !!!

**Comment by PKatGITHUB** [comment]
@teleivo what next :) ?

**Comment by teleivo** [comment]
@PKatGITHUB I cleaned AdministrationServiceTest up a bit so tests should be bit easier to read now.
I added one test case for `saveGlobalProperty` when saving the global property for 
`GLOBAL_PROPERTY_LOCALE_ALLOWED_LIST`

see
https://github.com/openmrs/openmrs-core/commit/dc33df6a5a49c2c60002b6e1591fe520ca0daadf

you could now add the case for

the method `saveGlobalProperty` when saving the global property for `GLOBAL_PROPERTY_DEFAULT_LOCALE` fails :)

**Comment by PKatGITHUB** [comment]
Hey @teleivo thanks for all your support :) 
I have created one more PR. Have a look at https://github.com/openmrs/openmrs-core/pull/2650

**Pull request merged**
