### PR TITLE
APPTEST-55: Add ignore unit tests in PersonNameValidatorTest.java

### PR DESCRIPTION
**Pull request by hank205**
In PersonNameValidatorTest.java,
add ignore unit tests that fail due to the bug reported in
https://issues.openmrs.org/browse/RA-543?filter=10068

### CODE REVIEW

**Comment by hank205** [comment]
URL for the JIRA ticket:
https://issues.openmrs.org/browse/APPTEST-55

**Comment by dkayiwa** [comment]
Does it include the new pull request url?

**Comment by hank205** [comment]
@dkayiwa Yes, I have updated.

**Comment by dkayiwa** [comment]
@hank205 can you put some text in the ignore annotation? Her is an example: https://github.com/openmrs/openmrs-core/blob/2.0.x/api/src/test/java/org/openmrs/module/ModuleActivatorTest.java#L23

**Comment by hank205** [comment]
@dkayiwa Sure! updated now with description for ignore annotations.

**Comment by dkayiwa** [comment]
@hank205 in the ticket description, can you mention that you have written some tests to reproduce this?

**Comment by hank205** [comment]
@dkayiwa made changes to ticket description.

**Comment by dkayiwa** [comment]
@hank205 the correct ticket should have been RA-543
Can you do it there?

**Comment by hank205** [comment]
@dkayiwa  Sure. Updated description at RA-543.

**Pull request merged**
