### PR TITLE
TRUNK-5496: Change java version from 8 to 11

### PR DESCRIPTION
**Pull request by Irenyak1**
## Description of what I changed
 I upgraded library JDK 1.8 to OpenJDK 11 

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5496

### CODE REVIEW

**Comment by Irenyak1** [comment]
@mozzy11  and @dkayiwa please review my PR when possible.

**Comment by HerbertYiga** [comment]
@Irenyak1  you are running under which operating system?

**Comment by Irenyak1** [comment]
ubuntu 18:04

**Comment by dkayiwa** [comment]
Can you include the ticket id in the commit message?

**Comment by Irenyak1** [comment]
@dkayiwa  let first run TRUNK-5499. then change to openjdk 11 and run this ticket again.

**Comment by gitcliff** [comment]
@Irenyak1 have you seen the travis failure,are you able to compile successfully on your local IDE?

**Comment by Irenyak1** [comment]
@gitcliff  even on the local machine it can not compile successfully

**Comment by gitcliff** [comment]
@Irenyak1  we need to first establish why it doesn't compile locally coz without a successfully local compilation, travis ci will fail,you can share your peastbin log here for your local compilation

**Pull request closed without merging**
