### PR TITLE
TRUNK-5770: Upgrade slf4jVersion from 1.7.28 to 1.7.30

### PR DESCRIPTION
**Pull request by achilep**
## Description of what I changed

i have change the following  dependencies version  :
org.slf4j:slf4j-api:1.7.28 --> 1.7.30
org.slf4j:jcl-over-slf4j:1.7.28 -->1.7.30
org.slf4j:log4j-over-slf4j:1.7.28 -->1.7.30
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5770

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by achilep** [comment]
thanks @dkayiwa

**Comment by achilep** [comment]
hello @dkayiwa i have update the PR . please can you reevaluate it . thanks
cc : @sherrif10 , @mozzy11

**Comment by dkayiwa** [comment]
@achilep Have you tried running the reference application with these changes?

**Comment by sherrif10** [comment]
Did you see @dkayiwa comment , you can follow this https://wiki.openmrs.org/display/docs/OpenMRS+SDK?focusedCommentId=93357844#comment-93357844

**Comment by dkayiwa** [comment]
Actually he may find it easier to just compile and just use `mvn jetty run` from the `webapp` folder of openmrs-core

**Comment by sherrif10** [comment]
ohh thanks @dkayiwa  i think its much more easier

**Comment by achilep** [comment]
thanks @dkayiwa  i was try something else much complicated . it will help me a lot

**Comment by achilep** [comment]
hello @dkayiwa   I could test this one and it works without problem.
thanks 
Screenshot from 2020-06-12 06-46-18

**Comment by sherrif10** [comment]
@achilep  are you sure thats part of testing, is it ok to share your full  successfull logs after your changes.This has not convinced me anyway .@dkayiwa any idea about this.

**Comment by achilep** [comment]
@sherrif10 I have test many parts of the application the screenshot is just one of them.

**Comment by achilep** [comment]
hello @dkayiwa and @mozzy11  
I tested with the standalone reference application .
Screenshot from 2020-06-16 07-56-56

**Pull request merged**
