### PR TITLE
[TRUNK-4549] - Improve error message description while creating a user

### PR DESCRIPTION
**Pull request by tutak**
Improved the English and Italian error messages.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@tutak on the JIRA ticket, can you attach a screenshot with the effects of your changes as advised at http://go.openmrs.org/pull-request-tips?

**Comment by tutak** [comment]
@dkayiwa I attached the screenshot.

**Comment by dkayiwa** [comment]
@tutak can you squash these commits into one?

**Comment by tutak** [comment]
@dkayiwa commits squashed.

**Comment by dkayiwa** [comment]
Closing because the author is no longer assigned to the ticket.

**Comment by SenaniDananjali** [comment]
I have took a look in this issue. How can i contribute myself in this issue ?

**Comment by dkayiwa** [comment]
@SenaniDananjali a lot has happened since the time this was closed. Therefore, it is simpler to just create a new pull request.

**Pull request closed without merging**
