### PR TITLE
Trunk 3267 : Delete any related objects here before deleting the obs

### PR DESCRIPTION
**Pull request by Tharunya**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Tharunya for the pull request, you also need to put some text, instead of just the ticket number. http://go.openmrs.org/pull-request-tips

**Comment by Tharunya** [comment]
@dkayiwa I've added Junit test having look at this https://github.com/openmrs/openmrs-core/blob/master/api/src/test/java/org/openmrs/api/ObsServiceTest.java#L1330  test case which checks if Obs is deleted from database.
Requesting you to review my pull request and suggest if any changes are required :-)

**Comment by dkayiwa** [comment]
@Tharunya can you squash these commits as advised at? http://go.openmrs.org/pull-request-tips

**Comment by Tharunya** [comment]
@dkayiwa  Sure, I've squashed the commits. Please check :)

**Comment by dkayiwa** [comment]
@Tharunya this does not seem to be the only object related to obs.
Take a look at liquibase-schema-only.xml and search for something like: referencedTableName="obs"

**Pull request closed without merging**
