### PR TITLE
TRUNK-5847: Javadoc improvement

### PR DESCRIPTION
**Pull request by sacull**
## Description of what I changed

My goal was to find broken links, typos in argument names, more arguments than in reality. My goal was not to supplement Javadoc in all classes. All the problems I found have been fixed.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5847

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sacull** [comment]
I don't know why Travis has a test error. When I run `mvn clean package` they all pass. :/

**Comment by HerbertYiga** [comment]
Possibly you could checkout this OrderServiceTest.getNewOrderNumber in your tests,according to the travis logs this is what i see (

OrderServiceTest.getNewOrderNumber_shouldAlwaysReturnUniqueOrderNumbersWhenCalledMultipleTimesWithoutSavingOrders:306 expected:<50> but was:<49>

)

**Comment by sacull** [comment]
@HerbertYiga I am surprised that this test ends 6 times successfully, and once not according to Travis. In addition, I didn't touch this test or the class that is being tested here. In this pull request, I only updated comments, nothing more. That's why I'm surprised.

**Comment by HerbertYiga** [comment]
not sure why we have a failing test here with openJDK 13,cc @dkayiwa

**Comment by dkayiwa** [comment]
I restarted the build and it failed on all. It looks like the UserServiceTest.getAllUsers_shouldNotContainsAnyDuplicateUsers test is randomly failing.

**Comment by sacull** [comment]
@dkayiwa This is both bad and good information. Good, because that means I haven't broken anything. Bad because the test should not randomly give good or bad results. I hope that we can solve this problem as a community.

**Pull request merged**
