### PR TITLE
Fixed whitespaces

### PR DESCRIPTION
**Pull request by patrickpl**
Seems, that most of the xml indents are tabs. To fix the broken
code indent I've converted the spaces into tabs.

If it is important for you to have a ticket for cleanup commits you can use this patch as a base for your cleanup. I was just looking for a pom example and I followed the pathfinder rule :)

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @patrickpl for the contribution! 😊 
Do you mind pointing me to the ticket for this? Or did you get a chance to have a look at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by patrickpl** [comment]
Is there a general ticket for clean-ups like this?

**Comment by dkayiwa** [comment]
You would have to create it yourself. 😊  https://wiki.openmrs.org/display/docs/Tickets

**Comment by patrickpl** [comment]
@dkayiwa thank you for your feedback. Since I don't want to become a developer of this project I will not setup IDs, accounts, ... Anyway my fix is just a minor clean-up and is not changing any functionality. You can reject my PR without any issues :-)

**Comment by dkayiwa** [comment]
@patrickpl do you have some time to share with us why you do not want to become a developer for this project? Could it be the long process of having to setup IDs, accounts, or anything else?
Am asking because we greatly value your contribution and would welcome feedback regarding what we should do better to make it super easy for people like you to contribute, and hence save even more lives! 😊

**Comment by patrickpl** [comment]
I'm not interested in the project from a development point of view. I prefer different technologies.

In my opinion have a strong development process can be a benefit, but by forcing people to create accounts, write tickets, etc. is not working for the people that are just passing thru and fixing things on the fly. Based on the statistics of the linux kernel this long tail is doing a significant amount of work. IMHO you should try to understand how you can proceed with the one time committers and how you can convert them into an often committer.

**Comment by dkayiwa** [comment]
@patrickpl your suggestion makes a lot of sense!
We are definitely going to look into it and make it easier for contributors who may not go through the process of creating accounts and tickets.

And to give an example of what we could do, i have created this ticket for your work: https://issues.openmrs.org/browse/TRUNK-5070
Then on the ticket, i have linked to your pull request.

Does this sound right to you? 😊

**Comment by patrickpl** [comment]
Yes, sounds good. Don't get me wrong I understand the process and the benefits (we are using a similar one in the company). It is just that for some people/work it is not optimal. Good luck!

**Comment by dkayiwa** [comment]
@patrickpl i fully understand you and completely agree! 😊

**Pull request merged**
