### PR TITLE
Added more tests.

### PR DESCRIPTION
**Pull request by Akayeshmantha**
TRUNK-5064 :- Add tests to PersonServiceImpl
https://issues.openmrs.org/browse/TRUNK-5064

My pull request is based on the latest changes of the master branch.

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit*

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
did you claim for the above ticket to show that you are working on it as recomended here https://wiki.openmrs.org/display/docs/Getting+Started+as+a+Developer

**Comment by dkayiwa** [comment]
@Akayeshmantha did you see the above comment?

**Comment by Akayeshmantha** [comment]
@dkayiwa  yes I have assigned it to my self.

**Comment by dkayiwa** [comment]
@Akayeshmantha can you take a second look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request closed without merging**
