### PR TITLE
TRUNK 5194 - Update junit to 4.12

### PR DESCRIPTION
**Pull request by mayank8318**
## Description of what I changed
Update JUNIT to 4.12 from 4.11

## Issue I worked on
see https://issues.openmrs.org/browse/TRUNK-5194

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by mayank8318** [comment]
Changed version number in `openmrs-core/pom.xml` but now the test fails.

**Comment by mayank8318** [comment]
@teleivo Sorry for that. I will do it now. Thanks :)

**Comment by mayank8318** [comment]
@teleivo Just changed it to 4.12 but the test again fails saying "fTestClass" not found...

**Comment by teleivo** [comment]
@mayank8318 great, the change/commit is correct now. did you run `mvn clean package` locally ? Did the tests run locally? What is the exact error message without 'not found...' Can you find something related to this error on the internet? Others trying to update junit might have had this error.

This issue is not only about changing the version in the pom. If something goes wrong like test failure you should try to dig a little into the cause, do some research as to why this is happening. If you then dont know how to continue, sure ask and we will try out your changes locally and see what we can do to help.

**Comment by mayank8318** [comment]
https://stackoverflow.com/questions/26192929/unable-to-run-junit-test-with-powermockrunner
Updating this now.

**Comment by mayank8318** [comment]
@teleivo Please review :)

**Comment by teleivo** [comment]
@mayank8318 awesome! can you please try with the latest powermock version from the 1.6.x range, I think its 1.6.6. please check on powermocks github page

**Comment by mayank8318** [comment]
@teleivo Please review :)

**Comment by teleivo** [comment]
@mayank8318 thank you very much 👍

**Pull request merged**
