### PR TITLE
Replaced 2.6.0-SNAPSHOT to 2.7.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by abertnamanya**
## Description of what I changed
During the release of 2.6.0-snapshot, core version has been updated to 2.7.0 in the pom file. 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by tendomart** [comment]
@abertnamanya   please include headers in the file

**Comment by abertnamanya** [comment]
Dear @dkayiwa,  Here is the PR

**Comment by tendomart** [comment]
@abertnamanya  have you addressed the issue to do with headers ?

**Comment by abertnamanya** [comment]
> @abertnamanya have you addressed the issue to do with headers ?

what headers?

**Comment by abertnamanya** [comment]
> @abertnamanya have you addressed the issue to do with headers ?

https://github.com/abertnamanya/openmrs-core/blob/7d8f54cae45303378b3c9646255b447c466dbc2b/pom.xml#L4

**Comment by dkayiwa** [comment]
@abertnamanya you need to change the version in all the pom files.

**Pull request merged**
