### PR TITLE
GCI-181:[Move this trailing comment on the previous empty line]

### PR DESCRIPTION
**Pull request by nschnitzer**
Move this trailing comment on the previous empty line.

https://issues.openmrs.org/browse/GCI-181

## Description of what I changed

Move this trailing comment on the previous empty line.

## Issue I worked on

see https://issues.openmrs.org/browse/gci-181

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by ykarim** [comment]
Hey @nschnitzer , nice work but please follow the [Contributing Guide](https://github.com/openmrs/openmrs-core/blob/master/CONTRIBUTING.md) for this repository and provide a detailed name for the commit. So the title can be "GCI-181:[Insert the ticket's name here]". Once that's fixed, you're all set.

**Comment by suthagar23** [comment]
Thanks for the efforts @nschnitzer . 
@dkayiwa  can we move to merge this PR?

**Comment by dkayiwa** [comment]
@suthagar23 the commits need to be squashed into one as advised at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by suthagar23** [comment]
ohh, Sry @dkayiwa  I forgot to notice that one. 
@nschnitzer Please squash all the commits into one commit to merge this PR. 
You can get more information from [here ](https://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one):-)

**Comment by dkayiwa** [comment]
@nschnitzer are you still working on this?

**Pull request closed without merging**
