### PR TITLE
APPTEST-54: Add new unit tests for PatientSetServiceImpl.java

### PR DESCRIPTION
**Pull request by hank205**
Added new tests in the file
/api/src/test/java/org/openmrs/api/PatientSetServiceTest.java.
Before adding these test cases, PatientSetServiceImpl.java has only
17.8% overall coverage.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@hank205 did you add the corresponding should annotations for the methods being tested as at? https://wiki.openmrs.org/display/docs/Unit+Testing+With+at-should+Annotation

**Comment by DrRacket** [comment]
@dkayiwa hi, I'm the teammate of @hank205. 
We forgot to add the @should javadoc notation. Sorry for that. We will fix this very soon.
One issue is that those old, existed test cases didn't include the @should javadoc notation should we also fix them?

**Comment by dkayiwa** [comment]
@DrRacket just do not spend your time adding for existing ones. :)

**Comment by DrRacket** [comment]
@dkayiwa hi, the annotations are added.

**Comment by dkayiwa** [comment]
@DrRacket @hank205 can you squash these commits into one?

**Comment by DrRacket** [comment]
@dkayiwa after messing up the branch, I created another pull request. https://github.com/openmrs/openmrs-core/pull/1779
Please close this one. Sorry for the inconvenience.

**Pull request closed without merging**
