### PR TITLE
[TRUNK-5268] Replace lambda expression with method reference

### PR DESCRIPTION
**Pull request by tomekdo3**
#### Issue: https://issues.openmrs.org/browse/TRUNK-5268

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you update the ticket description by explaining why this change is better than what is already in place?

**Comment by tomekdo3** [comment]
@dkayiwa I've updated it. It is aesthetic change so for some people lambda expression is more readable but for me method reference is more obvious.

**Comment by teleivo** [comment]
same changes as in PR #2511 , therefore closing this one.

**Comment by teleivo** [comment]
@tomekdo3 am sooo sorry 😭 that I now merged the change from another contributor. Thanks a lot for your effort and I hope I didnt discourage you now.

**Comment by tomekdo3** [comment]
@teleivo haha don't worry mistakes happen

**Pull request closed without merging**
