### PR TITLE
TRUNK-4684:Replace JDBC with Hibernate native query

### PR DESCRIPTION
**Pull request by lluismf**
https://issues.openmrs.org/browse/TRUNK-4684

### CODE REVIEW

**Comment by dkayiwa** [comment]
@lluismf do you mind pulling the latest changes from upstream to resolve the merge conflicts in this pull request?

**Comment by lluismf** [comment]
I've tried several times and I have to abort the rebase always. I resolved the conflicts manually but then rebase --continue fails. I'm out of ideas.

**Comment by dkayiwa** [comment]
@lluismf does it help if you just discard the changes, pull the latest from upstream, then put back the changes and create a new pull request?

**Comment by djazayeri** [comment]
If we are going to merge this, we need some serious testing to ensure that we're not regressing some behavior.

The original method was written in the ugly way it was to intentionally bypass hibernate. Does a SQLQuery in hibernate have the same effect?

**Comment by lluismf** [comment]
@Daniel ok I will try again, I think it's because of changes in license and line endings. Maybe I'll need to remove the branch, rebase master and branch again.

@Darius I ran unit tests (debugging) before and after the change, and the results were the same. I did not refactor any method that was not used in some test. And yes, SQLQuery is just a way to execute native SQL with the advantage of 1) less boiler plate and 2) parameter naming. Perhaps the original developer was not aware of this feature.

**Comment by lluismf** [comment]
Closing for now

**Pull request closed without merging**
