### PR TITLE
[TRUNK-5251] Remove final from static methods

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/TRUNK-5251

### CODE REVIEW

**Comment by dkayiwa** [comment]
final will prevent the method from being hidden by subclasses which is very good. Do you wanna get rid of this? 😊

**Comment by BartlomiejRasztabiga** [comment]
As I said in ticket description, when a static method is overridden in a subclass it can still be accessed via the super class, making a final declaration not very necessary.

**Comment by dkayiwa** [comment]
When you say "not very necessary", you mean "necessary but not so much".  Do you think we should remove final for something that is still necessary, at least to some extent? 😊

**Comment by BartlomiejRasztabiga** [comment]
Okay, I agree with you :) Leaving final keyword will be better

**Pull request closed without merging**
