### PR TITLE
TRUNK-5946: ProgramAttributeType Domain - Switching from Hibernate Mappings to Annotations

### PR DESCRIPTION
**Pull request by alinmihaila99**
## Issue I worked on
see https://issues.openmrs.org/browse/TRUNK-5946

## Checklist: I completed these to help reviewers :)
- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] All new and existing **tests passed**.
- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
Did you  get all the tests passing locally,i am seeing a failing test with jdk

**Review by Ruhanga — COMMENTED** [review]
@alinmihaila99, does everything pass locally with java 8?

**Comment by alinmihaila99** [comment]
Yes @Ruhanga, locally al was passing.

**Review by Ruhanga — APPROVED** [review]
Ok. Looks like the test failing `OrderServiceTest.getNewOrderNumber_shouldAlwaysReturnUniqueOrderNumbersWhenCalledMultipleTimesWithoutSavingOrders` does so randomly. @alinmihaila99, could you open up a ticket to cover this if one does not exist yet?

**Pull request closed without merging**
