### PR TITLE
[TRUNK-5283] compare() method can be used to compare primitives

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/TRUNK-5283

### CODE REVIEW

**Comment by dkayiwa** [comment]
The changes in the pull request look more than what the ticket requires.

**Comment by dkayiwa** [comment]
@BartlomiejRasztabiga did you see the above comment?

**Comment by BartlomiejRasztabiga** [comment]
@dkayiwa Fixed :)

**Comment by dkayiwa** [comment]
Can you claim the ticket?

**Comment by BartlomiejRasztabiga** [comment]
Sorry, done :)

**Comment by dkayiwa** [comment]
https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request merged**
