### PR TITLE
Trunk-5551 Upgrade xerces:xercesImpl

### PR DESCRIPTION
**Pull request by anshulbh9**
Trunk-5551 Upgraded xerces:xercesImpl

**Description of what I changed**
upgraded the library xerces:xercesImpl from 2.8.0 to 2.12.0
**Issue I worked on**
https://issues.openmrs.org/browse/TRUNK-5551

### CODE REVIEW

**Comment by anshulbh9** [comment]
@agamvrinos sir, the task is not assigned to anyone, i don't know about the status of existing PR.

**Comment by sherrif10** [comment]
what was the intention of removing this, was it among the PR  need
           <exclusions>
           	<exclusion>
           		<artifactId>xml-apis</artifactId>
           		<groupId>xml-apis</groupId>
           	</exclusion>
           </exclusions>

**Comment by anshulbh9** [comment]
@sherrif10 it was needed to remove the xml-apis as without this there will be a build failure and as in the official website it is Compile Dependency for xerces.

**Comment by sherrif10** [comment]
Thanks @anshulbh9  i didnot know that , thanks good work

**Pull request merged**
