### PR TITLE
TRUNK-4253 PatientService.savePatient isn't threadsafe and can allow duplicate patient identifiers

### PR DESCRIPTION
**Pull request by dilekamadushan**
https://issues.openmrs.org/browse/TRUNK-4253?filter=-1
Description of what I changed

Added synchronized blocks to enhance thread safety.
Checklist: I completed these to help reviewers :)

    [ x] My pull request only contains ONE single commit
    (the number above, next to the 'Commits' tab is 1).

    [ x] My IDE is configured to follow the code style of this project.

    [ x] I have added tests to cover my changes. (If you refactored
    existing code that was well tested you do not have to add tests)

    [ x] I ran mvn clean package right before creating this pull request and
    added all formatting changes to my commit.

    [ x] All new and existing tests passed.

    [ x] My pull request is based on the latest changes of the master branch.

### CODE REVIEW

**Comment by teleivo** [comment]
@dilekamadushan we really appreciate your efforts but I really think you are taking on to many issues, which is not helpful to you, us or others who want to contribute. You quickly open a PR from which I can see that you haven't thoroughly read the issue description. This issue is not an easy one as you can see from all the comments/attempts. It also requires you to add a test that proves your solution is correct.

I highly suggest you limit the amount of work you take on: like not more than 2, maybe best 1 issue (see https://www.atlassian.com/agile/wip-limits) until you complete it (it is merged!). PR #2536 needs a lot lot lot more thought & work for example.

**Comment by dilekamadushan** [comment]
@teleivo I will work on my previous works. Thanks

**Comment by BartlomiejRasztabiga** [comment]
Looking good, but test if you can run OpenMRS instance with these changes.

**Comment by dilekamadushan** [comment]
@BartlomiejRasztabiga Thanks I will try them. Feel free to review on #2536 too.

**Comment by dkayiwa** [comment]
@dilekamadushan did you also take a look at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dilekamadushan** [comment]
@dkayiwa Yes I followed the steps, tell me if there is anything to be changed. Thanks

**Comment by dkayiwa** [comment]
@dilekamadushan which steps on https://wiki.openmrs.org/display/docs/Pull+Request+Tips did you follow? Can you list them?

**Comment by dilekamadushan** [comment]
@dkayiwa I unassigned myself from the ticket. Thanks

**Pull request closed without merging**
