### PR TITLE
TRUNK-5304: Upgrade from 1.10.6 to 1.11.8 fails because of inconsistent changeset

### PR DESCRIPTION
**Pull request by sviho**
## Description of what I changed
I've modified bad changesets which caused ValidationError during upgrading following this <a href="https://wiki.openmrs.org/display/docs/How+to+Modify+a+Bad+Changeset">Wiki page</a>. 

I've pulled it against 1.11.x branch because master one doesn't have any changesets in liquibase-update-to-latest.xml file. It also needs to be backported to other versions after it's merged.

## Issue I worked on
JIRA: <a href="https://issues.openmrs.org/browse/TRUNK-5304">TRUNK-5304</a>

GCI: <a href="https://codein.withgoogle.com/dashboard/task-instances/4591487401590784/">Task Instance</a>

## Checklist: I completed these to help reviewers :)
- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] All new and existing **tests passed**

### CODE REVIEW

**Comment by dkayiwa** [comment]
I thought it was only two changesets that are supposed to be changed instead of four.

Can you also read about the JIRA workflow here? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by sviho** [comment]
@dkayiwa When I reproduced the error, I got four
screenshot_8

**Comment by dkayiwa** [comment]
Are you sure you got that for a brand new setup?

**Comment by sviho** [comment]
@dkayiwa I've set it up yesterday, so I think this should be fine

**Comment by dkayiwa** [comment]
How come the original report got only two failures?

**Comment by dkayiwa** [comment]
The talk thread attached to the ticket talks of only two changesets

**Comment by sviho** [comment]
Afaiu, reporter (@mogoodrich) just set an example of one of the inconsistent changesets comparing it in different versions <a href="https://talk.openmrs.org/t/cant-upgrade-from-openmrs-1-10-6-to-openmrs-1-11-8/14747">here</a>. All of the failing changesets are still parts of TRUNK-3422 changes and are caused by the same problem: replacing "View" with "Get". 

Should I remove some of my changes? If yes, which ones?

**Comment by dkayiwa** [comment]
After your changes, did you test again with a fresh install that upgrades from 1.10 to 1.11?

**Comment by sviho** [comment]
Yep, and it worked

**Comment by dkayiwa** [comment]
What do you mean by "current checksum 20181107"?

**Comment by dkayiwa** [comment]
And from here https://wiki.openmrs.org/display/docs/Pull+Request+Tips we usually do these on the master branch. For older branches, we simply back port.

**Comment by sviho** [comment]
In the comment I’ve ment to say when the change is introduced. I thought it might be useful, do I need to remove it? Okay, towards master branch this is what I thought at the beginning. I was confused because there are no changesets in the file in master branch. Afaiu now, I should add the ones I change there

**Comment by dkayiwa** [comment]
This is the file where those changes would go: https://github.com/openmrs/openmrs-core/blob/master/api/src/main/resources/liquibase-update-to-2.0.xml

**Comment by dkayiwa** [comment]
Am fine with commenting. But does that mean that the current checksum is the same for all the four changesets?

**Comment by sviho** [comment]
The values of current checksums are different for all the changesets, not sure what you’re talking about.

And yeah, thanks for directing me to the file. Haven’t checked it earlier

**Comment by dkayiwa** [comment]
What i mean is that your comment uses the same value for all the four changesets

**Comment by sviho** [comment]
Closing this PR because it isn't based on master. See a new one here: https://github.com/openmrs/openmrs-core/pull/2778

**Pull request closed without merging**
