### PR TITLE
Override "equals(Object obj)" to comply with the contract of the "compareTo(T o)" method.

### PR DESCRIPTION
**Pull request by collinsgeek**
There were no references to equals in classes as inferred here: https://ci.openmrs.org/sonar/drilldown/issues/1865?&rule=squid%3AS1210&rule_sev=CRITICAL

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Squash your commit together

**Comment by robbyoconnor** [comment]
Also you need to edit 7 more files.

**Comment by collinsgeek** [comment]
Hi Sir@robbyoconnor, these files are the only ones having this issue. I will work on another issue. and make another PR.

**Comment by robbyoconnor** [comment]
So find more issues and make PRs on those. If you need to find more issues to satisfy the requirement, so be it.

**Comment by robbyoconnor** [comment]
Also you need to squash these into one commit.

**Comment by robbyoconnor** [comment]
Amend the commit message now `git commit --amend` and then `git push origin master`

And for heavens sake **USE FEATURE BRANCHES!**

**Comment by robbyoconnor** [comment]
Also this is against the wrong branch -- so close it and do it again in a feature branch against `gci-2015` like you were told. Follow directions please.

**Comment by robbyoconnor** [comment]
Do this against `gci-2015` please.

**Comment by collinsgeek** [comment]
Hello Sir @robbyoconnor , It cannot go against gci-2015, it seems that branch has not been updated. My master branch is up to date. If I make this PR the other commits will be appear.

**Comment by robbyoconnor** [comment]
That's how we're doing it. Do it against `gci-2015` -- that branch contains the work from GCI. Don't argue.

**Comment by collinsgeek** [comment]
Alright Sir, Let me do it.

**Comment by robbyoconnor** [comment]
The way we're doing it -- we will merge it later on after the program is over.

**Pull request closed without merging**
