### PR TITLE
GCI-194: Remove unnecessary parentheses from GZIPResponseWrapper.java 

### PR DESCRIPTION
**Pull request by Shiv10**
##GCI-194: Remove unnecessary parentheses.
## Issue I worked on
I removed the parentheses from the GZIPResponseWrapper.java file.

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by jtatia** [comment]
Hi @Shiv10  . Thank you for working on this. However you need to first go through the following :- https://wiki.openmrs.org/display/docs/Pull+Request+Tips . You need to follow the steps mentioned on this wiki for coding tasks with a single instance. (Tip: You need to assign yourself this issue , and put it up for review. You also need to add the link to the issue in the PR description and link to the PR in the issue comment section ).

**Comment by Shiv10** [comment]
Hello @jtatia . Please help me in assigning this issue to myself. How can i do thay?

**Comment by dkayiwa** [comment]
The pull request should include a link for the ticket.

**Comment by suthagar23** [comment]
@Shiv10 Are you working on this PR? 
1. Please include the issue link in the PR description. I think you missed to add the URL properly.
2. Then you need to get access to OpenMRS Jira (https://issues.openmrs.org)
3. Log in to JIRA and select the respected issue. Then claim that issue for your work.
4. If you completed the work, then make it for review before submitting the PR for review.
Hope you will understand very well !!!

**Comment by dkayiwa** [comment]
@Shiv10 are you still working on this?

**Pull request closed without merging**
