### PR TITLE
TRUNCK-4742 Add support for setting test database credentials externally

### PR DESCRIPTION
**Pull request by fanyui**
## Description of what I changed
I BACKPORTED TRUNCK-4742 To branch 1.9.x and fixed some merge conflicts

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-4742

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [ x] All new and existing **tests passed**.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you squash the commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by fanyui** [comment]
Finished squashing the commits

**Comment by dkayiwa** [comment]
@fanyui can you look into the above travis failure?

**Comment by dkayiwa** [comment]
@fanyui are you still working on this?

**Comment by dkayiwa** [comment]
@fanyui ping me to reopen this when you resume working on it.

**Pull request closed without merging**
