### PR TITLE
TRUNK-5025 : Obs.setValueAsString supports more date formats and time…

### PR DESCRIPTION
**Pull request by mayank8318**
… zones.
## Description of what I changed
Add all the time formats supported by the rest framework.

## Issue I worked on
see https://issues.openmrs.org/browse/TRUNK-5025

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by mayank8318** [comment]
@wluyima  Please review :)

**Comment by dkayiwa** [comment]
@mayank8318 can you add some unit tests for your changes?

**Comment by mayank8318** [comment]
Changes : Added tests.
@dkayiwa Please review :)

**Comment by mayank8318** [comment]
@wluyima @teleivo `Context.getConceptService().getTrueConcept()` is giving error when I execute this test : 
`@Test
	public void setValueAsString_shouldSetValueAsBooleanIfDataTypeOfQuestionConceptIsBoolean() throws Exception {
		Obs obs = createObs(2);
		ConceptDatatype cdt = new ConceptDatatype();
		cdt.setHl7Abbreviation("BIT");
		cdt.setUuid(ConceptDatatype.BOOLEAN_UUID);
		obs.getConcept().setDatatype(cdt);
		obs.setValueAsString("false");
		Assert.assertEquals(obs.getValueAsBoolean(), Boolean.FALSE);
		obs.setValueAsString("true");
	}`

Error is : 
org.openmrs.api.APIException: Service not found: interface org.openmrs.api.ConceptService
	at org.openmrs.api.context.ServiceContext.getService(ServiceContext.java:648)
	at org.openmrs.api.context.ServiceContext.getConceptService(ServiceContext.java:433)
	at org.openmrs.api.context.Context.getConceptService(Context.java:379)
	at org.openmrs.Obs.setValueBoolean(Obs.java:646)
	at org.openmrs.Obs.setValueAsString(Obs.java:1097)
	at org.openmrs.ObsTest.setValueAsString_shouldSetValueAsBooleanIfDataTypeOfQuestionConceptIsBoolean(ObsTest.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by dkayiwa** [comment]
@wluyima what do you think of this?

**Pull request closed without merging**
