### PR TITLE
Trunk-5650:Add parent order group to order group

### PR DESCRIPTION
**Pull request by gitcliff**
link:https://issues.openmrs.org/browse/TRUNK-5650

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you look into these merge conflicts?

**Comment by gitcliff** [comment]
@dkayiwa i have resolved the merge conflicts

**Comment by dkayiwa** [comment]
Are these the only changes required by the ticket?

**Comment by gitcliff** [comment]
@dkayiwa  yes the changes are required by the ticket because changeset needs to be in a liquibase-update-to-2.4.xml file instead of liquibase-update-to-2.3.xml

**Comment by dkayiwa** [comment]
Did you remove this changeset from the `liquibase-update-to-2.3.xml` file?

**Comment by gitcliff** [comment]
yes @dkayiwa,  as you had earlier on requested in the comment on the ticket proceeding the merge

**Comment by dkayiwa** [comment]
@gitcliff are you sure that you did so?

**Comment by gitcliff** [comment]
@dkayiwa  i have fixed it

**Pull request merged**
