### PR TITLE
Trunk 3705:getName(Locale locale, boolean exact) simply calls getName() if exact = false

### PR DESCRIPTION
**Pull request by SandeepRaparthi1**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 did you use this https://wiki.openmrs.org/display/docs/Generate+Test+Case+Plugin to generate the unit test method name?

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 are you still working on this?

**Comment by SandeepRaparthi1** [comment]
@dkayiwa Yes I have made changes The name matches now :)

**Comment by dkayiwa** [comment]
@SandeepRaparthi1 can you please use the test case generator plugin above? That is how you will get it right.

**Pull request merged**
