### PR TITLE
TRUNK-3175: Fill javadoc for ActiveListItem class.

### PR DESCRIPTION
**Pull request by approce**
Fill javadoc for ActiveListItem.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@approce can you also always include at least the ticket summary in the pull request message as advised at http://go.openmrs.org/pull-request-tips?

**Comment by dkayiwa** [comment]
@approce the formatting does not look correct. Did you run mvn clean install before committing?

**Comment by approce** [comment]
@dkayiwa Ok, I have rerun command and it become correct formatted. Also, I have squashed commits.
You can check now.

**Comment by approce** [comment]
@dkayiwa  have fixed inaccuracies & rerun mvn clea install.

**Comment by approce** [comment]
@dkayiwa Yeap, I've fixed that to use ActivityListItem.

**Comment by dkayiwa** [comment]
In the english sentences, can you replace ActivityListItem with active list item?

**Comment by approce** [comment]
@dkayiwa yeap, I can :)

**Comment by approce** [comment]
@dkayiwa ok, have done with that.

**Comment by dkayiwa** [comment]
@approce you also need to run mvn clean install before committing such that the formatting gets correct.

**Comment by approce** [comment]
@dkayiwa corrected spelling & reruned mvn clean install.

**Pull request merged**
