### PR TITLE
Refactoring the code changes 

### PR DESCRIPTION
**Pull request by SankeerthSharmaR**
I was not working on the any existing issues.
Refactored the existing code base which has the code smells.

Did couple of refactoring for the existing classes:
1) for instance introducing explaining variable (Like magic no smell where directly take the length of /web/src to string.length()
2)And Decompose conditional if the method has more no of conditions in if statement.
3)Extract method if the method is too complex.(having large cyclomatic complexity)

Along with that:

1)Replace  conditional with polymorphism by adding extract classes where we have if else conditions and any future changes to made for that class
2)Extract Class refactoring by adding a new class and moving the method to it which are cohesive to another class
3)Move method (private static boolean isValid(Locale locale) ) to webutil java as it is used here.

### CODE REVIEW

**Comment by jwnasambu** [comment]
@SankeerthSharmaR kindly include the description of what you changed please. Besides, kindly does the ticket exist on the  the issue tracker  for this PR? if yes, kindly fix the correct link else remove the link you shared before its pointing to a wrong page.

**Comment by SankeerthSharmaR** [comment]
@jwnasambu 
I was not working on the any existing issues.
Refactored the existing code base which has the code smells and fixed few of them
And removed the link which is pointing to wrong page.

**Comment by jwnasambu** [comment]
Oh sorry you have a build failure. Kindly the error message you encountered is related to the license-maven-plugin in a Maven project. This plugin is used to enforce license headers in source code files. The error indicates that some files in the openmrs-api project do not have the expected license header.

To fix this error, you can follow these steps:

Identify the files that are causing the error. 

Open each file mentioned in the error message and ensure that it contains the correct license header. The license header is typically a comment at the top of the file that specifies the license under which the code is distributed.

If the files are missing the license header or have an incorrect one, you need to add or update the license header. The specific license requirements may vary depending on the project. You can usually find the correct license header format in the project's documentation or by examining other files in the project that have the correct license header.

Once you have updated the license headers in the problematic files, save the changes.

Rebuild the project using Maven to verify if the error has been resolved. You can do this by running the following command in the terminal or command prompt:

`mvn clean install`

This command will clean the project, recompile the code, and run the necessary Maven goals, including the license check.

If the error persists, ensure that the license-maven-plugin is properly configured in your project's pom.xml file. Check that the plugin version is correct and that the configuration specifies the expected license headers.

Save the changes to the pom.xml file and rebuild the project again.

By following these steps, you should be able to fix the error related to the missing or incorrect license headers in your Maven project.






Regenerate response

**Comment by tendomart** [comment]
And add a link to  the Ticket you're working on.

**Pull request closed without merging**
