### PR TITLE
[Google Code In 2015] Improved the README file

### PR DESCRIPTION
**Pull request by UlissesFerreira**
Fixed some grammar, improved some small stuff and reviewed the whole thing... On two words: important nitpicking.

Task from Google Code In:
"Identify typos and grammatical mistakes in README.md files (OpenMRS)"

Student: Ulisses Ferreira

### CODE REVIEW

**Comment by Ch3ck** [comment]
@UlissesFerreira  Squash all these commits into one commit; before we can proceed.

**Comment by UlissesFerreira** [comment]
Do you want me to make a new pull request? those commits were dumb I must admit but I though there was no problem when merging...

**Comment by Ch3ck** [comment]
@UlissesFerreira  Look at this: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html. Squashing the commits into one makes it easier to review. I have not even looked at the PR yet. Just do as I've recommended so we can help you better :+1:

**Comment by UlissesFerreira** [comment]
Can you tell me where is the branch? It's just I'm on the Github site, not using command line, and I can't find it... And by the way, about squashing commits, when you check the "Files changed" isn't it the same as squashing the commits? Because in there all the changes are just represented as one, the final one

**Comment by UlissesFerreira** [comment]
And forget the GCI branch, I found it!

**Comment by robbyoconnor** [comment]
Please close this and do it against `gci-2015`

**Comment by robbyoconnor** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Pull request closed without merging**
