### PR TITLE
Trunk-5450 - Java Collections functionality of memberships

### PR DESCRIPTION
**Pull request by fruether**
https://issues.openmrs.org/browse/TRUNK-5450
## Description of what I changed
This issue is a sub-ticket of: [TRUNK-5379](https://issues.openmrs.org/browse/TRUNK-5379 )which is concerned with changing size(), contains(), isEmpty() in a way that it reflects more the intuitive behaviour.  [Design nodes](https://notes.openmrs.org/2018-10-15-Design-Forum) have been created and the talk discussion appears to be here: [Talk thread](https://talk.openmrs.org/t/design-forum-2018-10-15-resolving-design-inconsistencies-in-cohort-membership-trunk-5379/20115/7)

I changed the just named methods accordingly and created test cases to verify the behaviour. 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5450

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@fruether i have just made the ticket ready for work. Can you claim it and take it through the process specified at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
Do you mind making the commit message better than simply "resolving ticket id"? In other words, from the commit message, i should tell what the commit is about, without having to first look at the ticket.

**Comment by fruether** [comment]
@dkayiwa I adapted the commit message. In the past I always did it like this. THat's why I did not do it in the first place.

**Comment by dkayiwa** [comment]
Can you have the commit message include the ticket id as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by fruether** [comment]
@dkayiwa added message and issue number

**Comment by fruether** [comment]
@dkayiwa That's because of the merge of the previous commit to the master. Let me fix this

**Comment by fruether** [comment]
@dkayiwa merge conflict is fixed now

**Comment by dkayiwa** [comment]
Can you include the pull request link on the JIRA ticket as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request merged**
