### PR TITLE
Added "synchronized" statement to methods of serviceContext in Contex…

### PR DESCRIPTION
**Pull request by HiddenGiraffe**
…t.java.

## Description of what I changed

Hi, I added "synchronized" statement to some methods in Context.java Cuz of their lazy initlialization of static ServiceContext.

## Issue I worked on

https://issues.openmrs.org/browse/GCI-241

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by HiddenGiraffe** [comment]
@dkayiwa 😊

**Comment by dkayiwa** [comment]
Did any of you try to run an instance of openmrs with this change?

**Comment by HiddenGiraffe** [comment]
Everything works fine I guess.
image

**Comment by dkayiwa** [comment]
are you just guessing?

**Comment by HiddenGiraffe** [comment]
Holy no my friend. I ran it on windows and don't see any errors.

**Comment by dkayiwa** [comment]
Can you give details on how you have run the platform with these changes? Can you also share a screenshot of any user interface page after running with your changes?

**Comment by dkayiwa** [comment]
@HiddenGiraffe are you still working on this?

**Comment by HiddenGiraffe** [comment]
No you can assign IT to other person


20.12.2017 11:24 "dkayiwa" <notifications@github.com> napisał(a):

**Pull request closed without merging**
