### PR TITLE
[GCI-142] Delete unused

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/GCI-142
Related PR: #2366

I have done "Optimize imports" with OpenMRS formatting settings. I hope it's okay :)

https://sonar.openmrs.org/sonar/drilldown/issues/1865?severity=MINOR

### CODE REVIEW

**Comment by dkayiwa** [comment]
What exactly does optimize imports mean? Or what is the value that this pull request adds?

**Comment by BartlomiejRasztabiga** [comment]
I've removed unused imports and sorted them as it is in your code style conventions.

**Comment by dkayiwa** [comment]
Removing unused imports and sorting them are two different things. I would remove unused imports in a separate pull request.
For sorting, what value does it add?

**Comment by BartlomiejRasztabiga** [comment]
I thought you would like to have your code style conventions unified

**Comment by dkayiwa** [comment]
How does sorting imports unify?

**Comment by BartlomiejRasztabiga** [comment]
I've just done like it it said here. These are your Import Layout settings
https://wiki.openmrs.org/display/docs/Developer+How-To+Setup+And+Use+IntelliJ?preview=/3346739/113017004/Screen%20Shot%202017-03-02%20at%2013.01.04.png

**Comment by dkayiwa** [comment]
Our Java conventions are here https://wiki.openmrs.org/display/docs/Java+Conventions

**Comment by BartlomiejRasztabiga** [comment]
Oh, I see. So I can delete sorting if you want :)

**Comment by BartlomiejRasztabiga** [comment]
@dkayiwa 
I've modified this so I am only deleting unusued imports

**Comment by dkayiwa** [comment]
@BartlomiejRasztabiga are you sure the commit in this pull request is about removing unused imports? 😊

**Comment by BartlomiejRasztabiga** [comment]
Oh, I had to make a mistake when I was in rush XD I will fix this after I come back home

**Comment by BartlomiejRasztabiga** [comment]
@dkayiwa Fixed! :)

**Comment by dkayiwa** [comment]
Thanks @BartlomiejRasztabiga 😊

**Pull request merged**
