### PR TITLE
[GCI-142] Delete unnecessary interface methods identifiers

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/GCI-142
Related PR: #2366

I've deleted redundant interface method indentifiers e.g. "public", "static". Because all Java interfaces methods are by default public and static. I don't know if it's right with your coding conventions so forgive me :)

### CODE REVIEW

**Comment by dkayiwa** [comment]
In principle, i fully agree with you on this. 😊 
But because it affects so many files, do you mind starting a discussion on Talk to get input from other developers?

**Comment by BartlomiejRasztabiga** [comment]
@dkayiwa Here is link for the discussion: https://talk.openmrs.org/t/openmrs-core-delete-unnecessary-interface-methods-identifiers/14514

**Comment by dkayiwa** [comment]
This has merge conflicts. But then, am still a bit reluctant to merge this because of the trade off between the value it adds and touching so many files leading to back porting merge conflicts.

**Comment by dkayiwa** [comment]
@BartlomiejRasztabiga let me hope you are fine with closing this for now. We can always reopen it after reaching a consensus on the talk thread that you started. Feel free to share objections, if any. 😊

**Pull request closed without merging**
