### PR TITLE
- Annotated BaseAttribute. See (#2672)

### PR DESCRIPTION
**Pull request by seekme94**
https://talk.openmrs.org/t/handling-jpa-annotations-for-baseattribute/17873
# TRUNK-5402: BaseAttribute should be annotated as MappedSuperclass

## Description of what I changed
back ported to 2.1.x. Replaced extends BaseChangeableOpenmrsData to extends 
BaseOpenmrsData

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5402

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the 2.1.x branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by seekme94** [comment]
@dkayiwa am I still missing something? Codacy review throws a warning on "Diff", I'm not sure what that's about.

**Comment by dkayiwa** [comment]
Does your commit message include the ticket id?

**Comment by seekme94** [comment]
> Does your commit message include the ticket id?

Yes, I edited the PR comment and included both the ticket number as well as link.

**Comment by dkayiwa** [comment]
A pull request description is different from a commit comment.

**Comment by seekme94** [comment]
> A pull request description is different from a commit comment.

Ah! Now I understand. So naive of me. On it...

**Comment by seekme94** [comment]
Will open another PR with correct commit comment.

**Pull request closed without merging**
