### PR TITLE
TRUNK-5490: DTD Config files pre version 1.5 lack tests and verification

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-5490

### CODE REVIEW

**Comment by gitcliff** [comment]
@ODORA0 have u checkout the travis ci build failure?

**Comment by ODORA0** [comment]
Could I be guided on what is not happening right here?? As far as I understood i am to write tests with reference to this [PR](https://github.com/openmrs/openmrs-core/pull/2875/files#diff-1af0dee9738803ab8cd9a932bbe52063) for the remaining config files cc @mozzy11  @dkayiwa

**Comment by sherrif10** [comment]
@ODOROA0 did you figured out the cause of travis failure

**Comment by ODORA0** [comment]
Its a null pointer and I think it is because of the verifications testxml files not merged within this pull request https://github.com/openmrs/openmrs-core/pull/2875/files and those that I haven't created for the the other versions, although I also think the test for this PR should be only 1.4 downwards if https://github.com/openmrs/openmrs-core/pull/2875/files is to be merged cc @dkayiwa @peytontanzillo

**Comment by jwnasambu** [comment]
@ODORA0 kindly include the description of what you changed.

**Pull request closed without merging**
