### PR TITLE
TRUNK-4666 Annotate entity classes

### PR DESCRIPTION
**Pull request by menuka94**
## Description of what I changed

Adding hibernate annotations to some entity classes.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-4666

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by menuka94** [comment]
I have annotated about half the number of available entity classes. Could you please take a look at the PR and tell me if I have done anything wrong?

Thank you.

**Comment by dkayiwa** [comment]
There are a number of binary files in your commit, which should not be there.

**Comment by menuka94** [comment]
@dkayiwa binaries removed :)

**Comment by dkayiwa** [comment]
squash the commits into one

**Comment by menuka94** [comment]
@dkayiwa done :)

**Comment by dkayiwa** [comment]
Delete the xml hibernate mapping files, compile and run to test if all is well.

**Comment by menuka94** [comment]
@dkayiwa the build fails in the absence of mapping files. https://issues.openmrs.org/browse/TRUNK-4666

**Comment by dkayiwa** [comment]
Closing because @menuka94 feels that the remaining work is too much to be worth it.

**Pull request closed without merging**
