### PR TITLE
[TRUNK-5276] Explicit type can be replaced with diamond syntax

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/TRUNK-5276

### CODE REVIEW

**Comment by dkayiwa** [comment]
Some merge conflicts here.

**Comment by dkayiwa** [comment]
@BartlomiejRasztabiga did you see the above comment? 😊

**Comment by BartlomiejRasztabiga** [comment]
I've updated the description :) https://issues.openmrs.org/browse/TRUNK-5273

**Comment by BartlomiejRasztabiga** [comment]
Done :)

**Pull request merged**
