### PR TITLE
[TRUNK-5271] Replace StringBuffer/StringBuilder with String in simple statements

### PR DESCRIPTION
**Pull request by tomekdo3**
#### Issue: https://issues.openmrs.org/browse/TRUNK-5271

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you add some more description to the ticket? In other words, make it convincing to someone who may not yet know why you are doing this.

**Comment by tomekdo3** [comment]
@dkayiwa I think it's all clear now. I've changed ticket and PR titles too 😊

**Comment by dkayiwa** [comment]
You need to explain a bit, in the ticket description, why performance is the same because some people know StringBuilder to be more performant than string concatenation. 😊

**Comment by tomekdo3** [comment]
@dkayiwa is that ok?

**Comment by dkayiwa** [comment]
Yes that is a better and more complete explanation! 👍

**Pull request merged**
