### PR TITLE
TRUNK 3178: Fill Problem class javadoc.

### PR DESCRIPTION
**Pull request by approce**
Fill Problem javadocs.
https://issues.openmrs.org/browse/TRUNK-3178.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@approce can you also always include at least the ticket summary in the pull request message as advised at http://go.openmrs.org/pull-request-tips?

**Comment by dkayiwa** [comment]
@approce the formatting does not look correct. Did you run mvn clean install before committing?

**Comment by approce** [comment]
@dkayiwa I will rerun command and check formatting.

**Comment by approce** [comment]
@dkayiwa  Ok, I have rerun command and it become correct formatted. Also, I have squashed commits. 
You can check now.

**Comment by approce** [comment]
@dkayiwa ok, have done and squashed commits.

**Comment by dkayiwa** [comment]
Can we put a line between method description and the param javadoc?

**Comment by approce** [comment]
@dkayiwa sure we can :)

**Pull request merged**
