### PR TITLE
Trunck 4975 Making Family name as Optional

### PR DESCRIPTION
**Pull request by fanyui**
## Description

I Removed the validation carried out on familyName
and also change the message.properties file to give a message that best resemble the error.
I also remove the tests that are carried out on the patientName when you compile the project
## Related Issue

see https://issues.openmrs.org/browse/TRUNK-4975
## Checklist:

- [ ] My pull request only contains one single commit.
- [x] My pull request is based on the latest master branch
  `git pull --rebase upstream master`.
- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@fanyui did you notice the travis failure?

**Comment by fanyui** [comment]
@dkayiwa I have not noticed an error as it builds without errors or maybe
am looking for the errors at the wrong place. I will appreciate  pointers
on how to find the said error.

**Comment by dkayiwa** [comment]
Can you squash the commits into one?

**Comment by dkayiwa** [comment]
@fanyui did you get a chance to test this out in a running web application to confirm that you can now register patients with only the given name?

**Comment by fanyui** [comment]
@dkayiwa Yes i did using the mvn jetty:run command and it worked.

**Comment by fanyui** [comment]
The  interface still has the field marked as required though it is not
really required

**Comment by dkayiwa** [comment]
@fanyui instead of removing these tests, can you instead make them test the opposite? For instance, if a test says "should fail if familyName is blank", you could make it, "should pass if familyName is blank".

**Pull request merged**
