### PR TITLE
TRUNK-5839: Add information about newer Java versions than 9

### PR DESCRIPTION
**Pull request by sacull**
## Description of what I changed

The file from the version using Spring Framework 4 includes only java to version 9. I added information about newer versions of java. Currently, they are versions up to 14.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5839

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by gitcliff** [comment]
@sacull thanks for the work on this,,could you add a ticket id to your commit 
https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by sacull** [comment]
@gitcliff Sorry, but ticket id is in three places. In the branch name, pull request name and its description. I don't know where else to put it. In the tips, I also did not find a place other than the three mentioned earlier.

**Comment by gitcliff** [comment]
hello @sacull all is well in all other places, i meant i your commit, the commit has to have the the ticket id plus the title of the ticket..

i have attached a screenshot in the description section of the ticket where this is to happen  ..Thanks

**Comment by sacull** [comment]
@gitcliff Now I understand. I think I corrected it. Can you look if it's done right now?

**Comment by gitcliff** [comment]
LGTM
cc @dkayiwa @ibacher

**Comment by sacull** [comment]
Pull request closed due to commit merge problem. Current pull request -> https://github.com/openmrs/openmrs-core/pull/3325

**Pull request closed without merging**
