### PR TITLE
Trunk-4987 Need to test the null case

### PR DESCRIPTION
**Pull request by JudeNiroshan**
Need to test the null case.
Handled the case where the sender is not mentioned, default from is using which is configured in global properties. 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-4987

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by teleivo** [comment]
@JudeNiroshan you need to remove one of your commits. you have two commits for separate issues.

**Comment by teleivo** [comment]
@JudeNiroshan please update your PR, or close it and free the issue so other people can work on it!!!

**Comment by JudeNiroshan** [comment]
@teleivo apologies for late reply. I can see there are 2 commits included in this PR which I never intended. I think it was by mistake. How do I remove the first commit in this PR? 

TRUNK-5034 Merge collapsable if statements

**Comment by dkayiwa** [comment]
@JudeNiroshan did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by teleivo** [comment]
@JudeNiroshan please rebase on latest master

**Comment by dkayiwa** [comment]
Closing because @JudeNiroshan decided to let go of the ticket.

**Pull request closed without merging**
