### PR TITLE
[TRUNK-5062]Extract private method in EncounterServiceImpl.saveEncounter

### PR DESCRIPTION
**Pull request by Kavindi183**
## Description of what I changed

 change the file-->
openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5062

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **4 commits**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you squash the commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips
Did you also look into the codacy review comments?

**Comment by dkayiwa** [comment]
@Kavindi183 are you still working on this?

**Comment by Kavindi183** [comment]
Yes, I,m going to try again to fix this issue.

**Comment by Kavindi183** [comment]
TRUNK-5062

**Pull request closed without merging**
