### PR TITLE
TRUNK-247 - Added required values constructors to java objects

### PR DESCRIPTION
**Pull request by xurror**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-247

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@xurror  thanks for working on this,have you seen the breaking Travis, checkout the travis ci to see what is breaking for this!

**Comment by xurror** [comment]
Yes. I'm getting to it in a minute. I'll ping a maintainer once it's good
for review.

**Comment by Wandji69** [comment]
@xurror some test are still failing do check the travis logs

**Comment by xurror** [comment]
@Wandji69, @HerbertYiga I still have some issues with improving coveralls coverage. Some of the classes could not be tested on their own as they serve mostly a supper classes for other classes and thus could not be tested individually. I have incorporated the feedback I read in a previous PR https://github.com/openmrs/openmrs-core/pull/3139 about this issue to the best I could but the testing side is still lagging.
If you have some suggestions on how to improve them, I'll gladly incorporate them.

**Comment by xurror** [comment]
Also, @ibacher please can you review?

**Comment by Wandji69** [comment]
@xurror I will run this on my end and see if I get any error, BTW, your issue link is not correct.

**Comment by xurror** [comment]
> @xurror I will run this on my end and see if I get any error, BTW, your issue link is not correct.

Thanks for the update.

**Pull request closed without merging**
