### PR TITLE
TRUNK-5436 Remove code in ApplicationContext.xml file

### PR DESCRIPTION
**Pull request by AkshatJain1**
## Description of what I changed

Removed property settings code in applicationContect-service.xml file because it was commented out and wasn't being used. This goes against the coding conventions.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5436

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by samuelmale** [comment]
Looks good

@dkayiwa any objections?

**Comment by dkayiwa** [comment]
Can we have the JIRA ticket taken through the workflow?
Could we also have the ticket number in the commit message?
https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by samuelmale** [comment]
Just changed the ticket status to request  code review @dkayiwa

**Comment by dkayiwa** [comment]
@samuelmale and the second point?

**Comment by AkshatJain1** [comment]
The commit message has been renamed.

Link instance: https://codein.withgoogle.com/dashboard/task-instances/5385621989228544/

**Comment by ykarim** [comment]
@samuelmale @dkayiwa Hi Samuel and Daniel, just a friendly reminder to approve students' work through the GCI dashboard once the pull request is approved. If needed, you may ask students to share the link to the GCI task instance for easy approval.

**Comment by AkshatJain1** [comment]
Hi, I cannot find this task on my GCI dashboard or the GCI task list. Can i receive credit for this issue in GCI?

**Comment by dkayiwa** [comment]
@AkshatJain1 did you get any notification about it getting closed?

**Pull request merged**
