### PR TITLE
GCI-142: Fixed bad coding practices by using Sonar

### PR DESCRIPTION
**Pull request by Bisht13**
## Description of what I changed

I fixed numerous bad code practices of the core app reported by Sonar.

I removed runtime exceptions, refactored the code to not nest more than 3 if/for/while/switch/try statements and used string variable instead of writing a particular text over and over again in the code.

## Issue I worked on

see https://issues.openmrs.org/browse/GCI-142

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**

- [x] My IDE is configured to follow the [**code style**]

- [x] I have **added tests** to cover my changes. 

- [x] I ran `mvn clean package` right before creating this pull request and added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you include the ticket id in the commit message as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Bisht13** [comment]
> Can you include the ticket id in the commit message as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Hey I did that 😃

**Comment by suthagar23** [comment]
Hey, Can you read it again : https://wiki.openmrs.org/display/docs/Pull+Request+Tips (Check your branch name)
And you need to fix the Travis-ci failure also(build failure) .

**Comment by Bisht13** [comment]
Closing this PR. New PR is #2780

**Pull request closed without merging**
