### PR TITLE
TRUNK-5759: Upgrade log4jVersion from 2.12.1 to 2.13.3

### PR DESCRIPTION
**Pull request by achilep**
##  TRUNK-5759: Upgrade log4jVersion from 2.12.1 to 2.13.3

The goal is to update the following dependencies:
org.apache.logging.log4j:log4j-core:2.12.1 -->2.13.3
org.apache.logging.log4j:log4j-slf4j-impl:2.12.1 -->2.13.3
org.apache.logging.log4j:log4j-1.2-api:2.12.1 -->2.13.3

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5759

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sherrif10** [comment]
LGTM  cc @dkayiwa  @ibacher  @mozzy11

**Comment by dkayiwa** [comment]
@achilep did you test these changes with the reference application?

**Comment by achilep** [comment]
hello @dkayiwa is working in my  computer without a problem .
Screenshot from 2020-06-11 23-16-55

**Comment by achilep** [comment]
Screenshot from 2020-06-16 00-17-24
hello @dkayiwa  @mozzy11 .

**Comment by dkayiwa** [comment]
Can you look into the merge conflicts?

**Comment by sherrif10** [comment]
Another thing @dkayiwa  is it so neccessary to share the screen shot of referenceapplication when testing

**Pull request merged**
