### PR TITLE
TRUNK-4463: Removed spaces in GP values string array

### PR DESCRIPTION
**Pull request by tharinduNA**
https://issues.openmrs.org/browse/TRUNK-4463

### CODE REVIEW

**Comment by dkayiwa** [comment]
@tharinduNA can you create a unit test for this? You can look at existing controller unit tests, for an example.

**Comment by tharinduNA** [comment]
@dkayiwa okay I will create an unit test

On Wed, Mar 4, 2015 at 3:19 PM, dkayiwa <notifications@github.com> wrote:

> @tharinduNA <https://github.com/tharinduNA> can you create a unit test
> for this? You can look at existing controller unit tests, for an example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/1391#issuecomment-77125832>.
>



-- 


Regards,
Tharindu,

   -
      - BSc Computer Engineering Undergraduate,
      Faculty of Engineering,
      University of Peradeniya,
      Sri Lanka.

**Comment by downeym** [comment]
Any luck creating that unit test, @tharinduN?

**Comment by dkayiwa** [comment]
@tharinduNA tell me to reopen if you resume working on this.

**Pull request closed without merging**
