### PR TITLE
GCI-207: Rename immed_parents in HibernateConceptDAO to match convention

### PR DESCRIPTION
**Pull request by sengsockhian**
https://issues.openmrs.org/browse/GCI-207

### CODE REVIEW

**Comment by jtatia** [comment]
Hi @sengsockhian  . Thank you for working on this. However you need to first go through the following :- https://wiki.openmrs.org/display/docs/Pull+Request+Tips . You need to follow the steps mentioned on this wiki for coding tasks with a single instance. (Tip: You need to assign yourself this issue in jira, and put it up for review ).

**Comment by jtatia** [comment]
Great work @sengsockhian . This is ready to be merged @dkayiwa

**Comment by jtatia** [comment]
@sengsockhian , do modify the description to point to the actual task link (GCI-207)

**Comment by sengsockhian** [comment]
@jtatia thank you! i modified it :)

**Comment by dkayiwa** [comment]
@sengsockhian can you cancel the duplicate ticket that you created?

**Comment by sengsockhian** [comment]
@dkayiwa i have cancelled it previously! sorry for the inconvinience

**Comment by dkayiwa** [comment]
The Resolution should have been Duplicate.

**Pull request merged**
