### PR TITLE
TRUNK-5838: Correct version validate method and add test to check that

### PR DESCRIPTION
**Pull request by sacull**
## Description of what I changed

The Spring Framework version of OpenMRS requires java version 1.8 or higher. The java version check method should therefore only allow these versions. I have corrected the regular expression checking the java version to prevent it from using versions 1.6 and 1.7. In addition, I added a test checking the correctness of operation for version 10+.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5838

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sacull** [comment]
New pull request due to commit merge problems. Old pull request -> https://github.com/openmrs/openmrs-core/pull/3314

**Comment by dkayiwa** [comment]
@sacull can you look at the merge conflicts?

**Comment by sacull** [comment]
@dkayiwa Someone broke the tests. ;)

The reason for the conflict is that PR was done as JUnit4 was in effect, now it is JUnit5 which does not support PowerMock. I will resolve this conflict as soon as I learn to mock static methods in JUnit5 without PowerMock.

**Comment by sacull** [comment]
@dkayiwa Unfortunately, I couldn't think of a way to efficiently test it without the Powermock. In the case of a regular static method, it can be done, but here the static method calls another static method internally, and without corrections at this point, it probably cannot be tested effectively, in my opinion. Unfortunately, at the moment I have no idea how to improve it, so I propose to leave the test in the version of the migration gentlemen from JUnit4 to Junit5, and I will come back to this problem in some time when I know how to do it.

**Pull request merged**
