### PR TITLE
TRUNK-5963 -Adding Order Context to Order Group

### PR DESCRIPTION
**Pull request by tendomart**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5963

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

@ibacher  do you think this is the right path according to description.?

### CODE REVIEW

**Comment by joachim-junior** [comment]
Hi @tendomart . Please Try to review your checklists. Your code seems okay. Travis build failed. Please try looking again.

**Comment by bejanut** [comment]
@tendomart Your code seem to be good, there was a problem with the Travis CI testing, maybe you can add a new commit and see if the problem persists.

**Comment by tendomart** [comment]
Ooh thanks @joachim-junior  and @bejanut  for the reviews .Iam gonna look at the Travis logs and rectify the failure .

**Comment by bejanut** [comment]
> Ooh thanks @joachim-junior and @bejanut for the reviews .Iam gonna look at the Travis logs and rectify the failure .

I glad you're back on track and I'll keep looking if the test persists to see if I could help.

**Comment by tendomart** [comment]
Screenshot from 2021-04-23 18-18-23
A Screenshot of the database  for   the new columns in **order_group** table i.e **care_setting** and  **order_type_id**

**Comment by sherrif10** [comment]
Thanks @tendomart  , there are some merge conflicts to resolve.Thanks.

**Comment by tendomart** [comment]
Everything was cleaned up the last [commit](https://github.com/openmrs/openmrs-core/pull/3647/commits/8a1abbf24b8d2d27d7e22d9a59ccb5255a018f3d) , Iam not really sure why this is still here ..

**Pull request closed without merging**
