### PR TITLE
Updated body of setter functions in 18 classes for TRUNK-4659 

### PR DESCRIPTION
**Pull request by YheCoder**
TRUNK-4659 -- Patent.setIdentifiers accepts args it shouldn't

### CODE REVIEW

**Comment by robbyoconnor** [comment]
You're not using the parameters anymore...

**Comment by YheCoder** [comment]
@robbyoconnor Could you explain a little bit more what you mean, please?

**Comment by robbyoconnor** [comment]
@YheCoder Look at your PR — you're no longer using the parameter passed into the setter...

**Comment by YheCoder** [comment]
@robbyoconnor  Thank you. Do you mean the setIdentifiers function in Patient.java or all the others also?

**Comment by robbyoconnor** [comment]
@YheCoder In *ALL* of them. You're taking in but not using the parameter... It'd be better to just initialize this and not even provide the setters at all.

**Comment by robbyoconnor** [comment]
Also you broke the tests.

**Comment by dkayiwa** [comment]
@YheCoder  Am closing this because of failing tests.

**Pull request closed without merging**
