### PR TITLE
TRUNK-4635:Changed ConceptForm.js and conceptForm.jsp

### PR DESCRIPTION
**Pull request by aashna**
https://issues.openmrs.org/browse/TRUNK-4635

### CODE REVIEW

**Comment by dkayiwa** [comment]
@aashna do you mind improving your commit message from simply saying that you changed the files? If you are not sure of what it should be, you can at least use the ticket title.

**Comment by aashna** [comment]
@dkayiwa I have updated the commit message, is it fine now?

**Comment by aashna** [comment]
Looks some problem with the code, I'll check it.

**Comment by dkayiwa** [comment]
@aashna can you squash the commits into one as advised at? http://go.openmrs.org/pull-request-tips

**Comment by dkayiwa** [comment]
Closing because the correct fix was committed at https://github.com/openmrs/openmrs-core/commit/19c7ae1b122fd575ec8ca3a59002b6617ff6c2ca

**Pull request closed without merging**
