### PR TITLE
TRUNK-5213: @OpenmrsProfile loads Spring resources conditionally based on missing module(s) 

### PR DESCRIPTION
**Pull request by mks-d**
## Description
`@OpenmrsProfile` loads Spring resources conditionally based on missing module(s)
## Related Issue

https://issues.openmrs.org/browse/TRUNK-5213

## Checklist:

- [x] My pull request only contains one single commit.
- [x] My pull request is based on the latest master branch
  `git pull --rebase upstream 1.9.x`.
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mks-d do we plan back porting this to 1.9.x? I thought we were stopping at 1.10.x

**Comment by mks-d** [comment]
I know, I got it wrong, but [AH requires Core 1.9.0](https://github.com/openmrs/openmrs-module-addresshierarchy/blob/5553a09e0fa12874169aa9ae894d099f688e0719/omod/src/main/resources/config.xml#L22)...
However perhaps this is not relevant anymore and 1.10 is enough, @mogoodrich?

**Comment by mogoodrich** [comment]
I don't see any problems with upgrading Address Hierarchy to require 1.10.x @mks-d

**Comment by mogoodrich** [comment]
Actually @mks-d to follow up, @mseaton  reminds me that one of our older implementations still runs 1.9 and uses Address Hierarchy.

That being said, we've got to upgrade at some point and can have people needing to backport 4+ versions every time.

So, if you've already done the work backporting to 1.9 or it's almost done (and there isn't a large testing burden), let's do that, but if it's going to be a pain, 1.10 is fine.

**Comment by mks-d** [comment]
@dkayiwa , can we merge this in then?

**Pull request merged**
