### PR TITLE
Adding maven.development.version and build.release.type variables to Bamboo

### PR DESCRIPTION
**Pull request by wikumChamith**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@wikumChamith can we remove the formatting changes?

**Comment by wikumChamith** [comment]
Yes. That error we got was not in the code I added.

**Comment by dkayiwa** [comment]
Do you mind explaining a bit more why the error happened only after those changed were merged?

**Comment by wikumChamith** [comment]
> Do you mind explaining a bit more why the error happened only after those changed were merged?

We are still getting that error. Here is the failure for the revert you did: https://ci.openmrs.org/browse/TRUNK-MASTER-3603/commit

**Comment by dkayiwa** [comment]
I am still trying to understand why it was not failing before our attempt. 😊

**Comment by wikumChamith** [comment]
Is it possible it did but somehow got overlooked?

**Comment by wikumChamith** [comment]
@dkayiwa, we've encountered this error before as well. For instance, here’s the same issue in @ibacher's changes on this file: https://ci.openmrs.org/browse/TRUNK-MASTER-3482

**Comment by dkayiwa** [comment]
Does the fix require all these formatting changes?

**Comment by wikumChamith** [comment]
> Does the fix require all these formatting changes?

Yes

**Comment by dkayiwa** [comment]
How do you tell so?

**Comment by wikumChamith** [comment]
> How do you tell so?

I used a YML validator to check.

**Comment by dkayiwa** [comment]
Ok let us see how this goes.

**Comment by wikumChamith** [comment]
It passed :) https://ci.openmrs.org/browse/TRUNK-MASTER-3606

**Comment by ibacher** [comment]
What's the point of adding the `maven.development.version` variable? We don't seem to actually be _using_ it since we always set the development version using this: `${DEV_IMAGE} mvn versions:set -DnextSnapshot=true -DgenerateBackupPoms=false` and we don't re-export that back to Bamboo.

Traditionally, `maven.development.version` gets passed as the second argument to [this script](https://github.com/openmrs/openmrs-contrib-bamboo/blob/master/release-prepare-perform.sh), and the use-case is to be able to specify the next SNAPSHOT version (which is not really something we do too much).

**Comment by wikumChamith** [comment]
@ibacher, is it possible to handle cases like the following when doing a release without using the `maven.development.version` variable?

- When releasing Platform 2.7.0-alpha, we want the next development version to remain Platform 2.7.0-SNAPSHOT.
- After the full release of Platform 2.7.0, we want the next development version to be Platform 2.7.1-SNAPSHOT.


cc: @rkorytkowski"

**Comment by dkayiwa** [comment]
@rkorytkowski would that be better than just setting the next development version variable in bamboo and have all that automatically done during the release task?

**Comment by ibacher** [comment]
> is it possible to handle cases like the following when doing a release without using the maven.development.version variable?

Yes. There’s a job in the RefApp for O3 that does something very similar. But my real point was that `maven.development.version` is an OpenMRS convention, not a Bamboo or Maven thing. So just adding the variable to the CI job doesn’t actually do what you want. You need to swap out the line that sets the next development version with the value of the variable.

**Pull request merged**
