### PR TITLE
EMPT-174:  Made cookies more secure.

### PR DESCRIPTION
**Pull request by jnsereko**
## Description of what I changed
 I have made cookies more secure in OpenMRS by reducing setting up an expiry date of the cookie and  setting the secure attribute to true such that an attacker can not access the cookie using Javascript

## Issue I worked on EMPT-174

see https://issues.openmrs.org/browse/RA-1875

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by isears — CHANGES_REQUESTED** [review]
Thanks @jnsereko,

Is it possible to also set the `same-site` cookie attribute to `strict` here?

**Comment by jnsereko** [comment]
Thanks @isears  for the review.
i have tried to set this `same-site` to `strict` but i have failed.  Below are alternatives i have tried.  

1.  adding the following code to the `META-INF/context.xml` file 
```    <!-- Add SameSite to the cookies --> 
    <CookieProcessor 
        sameSiteCookies="strict" /> 
```

2. adding `<comment>__SAME_SITE_STRICT__</comment>` to the `web.xml` file under the `<cookie-config>` tag
3. adding `<comment> <same-site>strict</same-site> </comment>` to the `web.xml` file under the `<cookie-config>` tag

They state that this attribute isn't present in some some earlier visions of Tomcat but i think the tomcat version used by OpenMRS supports SameSite attribute.

**Comment by sherrif10** [comment]
Hello @isears, For this case do we only have one option for setting same-site  per cookie?,is this cookie is going to be working on only headers or the entire system, was thinking that we can as well write a method that can handle each cookie though not sure if that might need more work to implement or its a duplicate idea ,Looking to see your suggestion

**Comment by isears** [comment]
> Well Done @jnsereko Hello @isears, For this case do we only have one option for setting same-site per cookie?,is this cookie is going to be working on only headers or the entire system, was thinking that we can as well write a method that can handle each cookie without changing the functionality of the already built cookies, though not sure if that might need more work to implement or its a duplicate idea ,Looking to see your suggestion

That's a good idea, especially since we're having trouble setting "Same-Site" attributes globally. From a security perspective, I'm mostly concerned about `JSESSIONID`.

**Comment by isears** [comment]
Going to close this for now because secure cookies break non-ssl implementations of OpenMRS (e.g. on private networks)

**Pull request closed without merging**
