### PR TITLE
TRUNK-248 Add tests for junit TODOs

### PR DESCRIPTION
**Pull request by MatMoore**
## Description of what I changed
I've deleted one of the testing TODOs in a private method.

The `getFormCriteria` method is used by a couple of methods in the form service that allow you to search for forms by name.

If this is only used by the legacy UI, then it's probably not worth focusing on this class. The rest of the class is not tested at the moment.

In the new UI can users specify forms dynamically? If it is, I can write a test that reflects the way the functionality is being used.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-248

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by teleivo** [comment]
@MatMoore I dont know. @dkayiwa do you know more about where this class is used? And what we should do with it?

**Comment by dkayiwa** [comment]
@MatMoore @teleivo for platform service methods, you can not know which modules are using them  because module authors are not required to host them under the openmrs github organisation. Besides, modules are not required to be open source. 😊

**Comment by MatMoore** [comment]
Thanks @dkayiwa, that makes sense. In that case I'll try and write a unit test based on the current implementation 🙂

**Comment by teleivo** [comment]
@MatMoore I am closing this PR for now since we have many PRs open and it becomes messy for us reviewers :) Please fell free to reopen the PR when you have added the tests. Thank you very much for your contribution!

**Comment by MatMoore** [comment]
@teleivo no problem 🙂 

@dkayiwa I had another look at this today, and I think the behavior is tested, but the test is at the service level, and it only covers the case where the parameter is passed in and actually matches a form field.

https://github.com/openmrs/openmrs-core/blob/master/api/src/test/java/org/openmrs/api/FormServiceTest.java#L296

There isn't a test case for the form DAO itself, but I don't think there's value in creating one that duplicates what's tested at the service level. I'm not very familiar with Java/OpenMRS conventions for testing though - what do you think?

I could expand the FormServiceTest to cover a few more cases, if that would be useful?

**Comment by teleivo** [comment]
I think we mainly test via the service layer. Adding some more cases to the
existing tests that are not yet covered is useful :)

Am 17.04.2017 20:24 schrieb "Mat" <notifications@github.com>:

**Pull request closed without merging**
