### PR TITLE
TRUNK-5546:Upgrade org.mockito:mockito-core

### PR DESCRIPTION
**Pull request by lufafa123**
## Description of what I changed
I Upgraded library org.mockito:mockito-core from 1.10.19 to 3.1.0

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5546

### CODE REVIEW

**Comment by lufafa123** [comment]
@dkayiwa  kindly review my pull request

**Comment by gitcliff** [comment]
@lufafa123  have you seen the travis failure?
u can also go through this https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by lufafa123** [comment]
@gitcliff my work was focused o updating the library to the current release.

**Comment by gitcliff** [comment]
true @lufafa123 but u need to  fix the travis ci error, did u get a BUILD SUCCESSFUL when u run mvn clean install on your pc ?

**Comment by mozzy11** [comment]
looks ok @lufafa123

**Comment by dkayiwa** [comment]
@mozzy11 looks ok to you with the travis build failure?

**Comment by mozzy11** [comment]
@dkayiwa i think , the Travis failure wasnt there innitially. Probably he changed to another version from the one he had upgraded to before  .

**Pull request closed without merging**
