### PR TITLE
Trunk 6225: Excessive calls to DB on some endpoints when `layout.name.template` GP not set

### PR DESCRIPTION
**Pull request by Lemmynjash**
## Description of what I changed

I cached the deserialized NameTemplate instance and deserialize it again when the global property value changes. This way, unnecessary SELECT statements for retrieving the global property value can be avoided for each queue entry retrieval. I overrode the globalPropertyChanged method to update the deserialized NameTemplate instance only when the layout.name.template global property changes. It updates the cached instance and the last known global property value accordingly.

## Issue I am currently working on

see https://openmrs.atlassian.net/browse/TRUNK-6225

## Checklist: I completed these to help reviewers :)

- [X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [X] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [X] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by chibongho** [comment]
@Lemmynjash looks reasonable, but I'll defer to @dkayiwa as I don't know this code base that well. 

One of the maven tests failed with an NullPointerException. Can you fix it?

**Comment by dkayiwa** [comment]
@Lemmynjash did you put this in draft because you are still finishing up some things before you are ready for review?

**Comment by Lemmynjash** [comment]
Yes, I put this in draft because I am still working on finishing up the issue. I am following up on the reproduce provided by @chibongho  and seeing if the solution provided fixes the issue mentioned.

**Comment by chibongho** [comment]
Hi @Lemmynjash, any update on this? Let me know if I can help.

**Comment by ibacher** [comment]
One thing I'll note here is that the `SELECT` statement from the ticket is generated from the call `Context.getAdministrationService().getGlobalProperty(OpenmrsConstants.GLOBAL_PROPERTY_LAYOUT_NAME_TEMPLATE)`, so fixing this issue will require not running that command at every instance. The API we have for this is a `GlobalPropertyListener`, and interface that can be registered and then will receive updates to any global properties it opts into. So a solution to this (in addition to caching the parsed XML in memory) would be to setup a kind of "holder" class that would load this property, register itself as a listener and then it only needs to change the value if the GP changes.

That's at least a vague outline of how to approach this.

**Comment by dkayiwa** [comment]
Fixed at https://github.com/openmrs/openmrs-core/commit/e878c6389843cb052b4d158afac2582112312939

**Pull request closed without merging**
