### PR TITLE
[TRUNK-5246] Thread-safety: corrected lazy initialization of static field

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/TRUNK-5246

I've corrected lazy initialization of two static fields so they can be accesses from any thread.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@BartlomiejRasztabiga do we need both synchronized and volatile? Or just one of the two?

**Comment by BartlomiejRasztabiga** [comment]
@dkayiwa I've seen examples of Singleton where both volatile and synchronized block were used. I think it just prevents the instance field from having different values for different threads.

**Comment by dkayiwa** [comment]
For the sake of just the reported problem, wouldn't one be enough?

**Comment by BartlomiejRasztabiga** [comment]
I think we can leave just the synchronized blocks

**Pull request merged**
