### PR TITLE
TRUNK-6012: Change the max age limit of 120 years to 140 years in openmrs-core

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**
https://issues.openmrs.org/browse/TRUNK-6012

## Description of what I changed
Change the max age limit of 120 years to 140 years in openmrs-core

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-6012

### CODE REVIEW

**Comment by Ndacyayisenga-droid** [comment]
Hey @dkayiwa  @ibacher  need some code reviews here
cc @gracepotma

**Comment by gracepotma** [comment]
Looks good to me but I'm just saying that as a Product Manager. Over to @dkayiwa to review :)

**Comment by dkayiwa** [comment]
@Ndacyayisenga-droid take a second look at this: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Ndacyayisenga-droid** [comment]
> @Ndacyayisenga-droid take a second look at this: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Hey @dkayiwa  does it look fine now...... if not who could I be doing that is not right!

**Comment by tendomart** [comment]
@dkayiwa  anything more to do here ?

**Pull request merged**
