### PR TITLE
MP4 

### PR DESCRIPTION
**Pull request by hirschf2**
Getting tests from changes we made in MP4

### CODE REVIEW

**Comment by dkayiwa** [comment]
@hirschf2 did you take a look at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@hirschf2 can you squash these commits into one?

**Comment by dkayiwa** [comment]
@hirschf2 are you still working on this?

**Comment by downeym** [comment]
What is MP4?
Is this related to an active OpenMRS issue at https://issues.openmrs.org/?

**Comment by hirschf2** [comment]
No I apologize, the pull request was an accident I made prematurely in the week.

**Pull request closed without merging**
