### PR TITLE
APPTEST-53: Added tests for ModuleFactory in new test class ModuleFactoryTest

### PR DESCRIPTION
**Pull request by tjtunnell**
https://issues.openmrs.org/browse/APPTEST-53

As clarification, these are new tests.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@tjtunnell this pull request looks messed up. Can you take a look at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by tjtunnell** [comment]
Yeah, I messed this up.  I'll get this fixed up soon.  I'll reply back once I get it.

**Comment by tjtunnell** [comment]
I have fixed the issues from earlier.

**Comment by tjtunnell** [comment]
Closed because I didn't follow naming branch name conventions.

**Pull request closed without merging**
