### PR TITLE
Added information about SQL Injection prevention

### PR DESCRIPTION
**Pull request by Davidepaalte**
It's still necessary to implement the functionality.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Instead of this, can you just create a ticket? https://wiki.openmrs.org/display/docs/Tickets

**Comment by Davidepaalte** [comment]
I don't have access to the platform.
If you may, can you open one yourself?

PS: the SQLi vulnerability isn't just here, every time simple statements are being used with arguments, a PreparedStatement should be used instead. There are many situations like this in this code.

**Comment by dkayiwa** [comment]
Do you mean access to JIRA?

**Comment by Davidepaalte** [comment]
Yes, I can't create new tickets or comment existing ones.
I tried to comment on this ticket https://issues.openmrs.org/browse/TRUNK-5244 as it's the same situation happening in many different places.

**Pull request closed without merging**
