### PR TITLE
CSRF: Switch property for org.owasp.csrfguard.Enabled from true to false

### PR DESCRIPTION
**Pull request by kdaud**
## Checklist: I completed these to help reviewers :)

- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kdaud Why are you turning this off?

**Comment by sherrif10** [comment]
@dkayiwa  Thought there is a defined global property for changing this variable when we encounter qa server errors.

**Comment by dkayiwa** [comment]
@sherrif10 why do you want to turn it off in the first place?

**Comment by dkayiwa** [comment]
@sherrif10 can you share the full error log having that message via pastebin.com?

**Comment by sherrif10** [comment]
> @sherrif10 can you share the full error log having that message via pastebin.com?

This is happening when we try to run any single workflow locally. The sever returns that error. Forexample cd qaframework-bdd-tests> npm run refApp2Forms> run. the server hangs with the error above.

**Comment by dkayiwa** [comment]
Can you share the full error log via pastebin.com?

**Comment by kdaud** [comment]
> @kdaud Why are you turning this off?


@dkayiwa now that our qa server is sniping on the latest platform SNAPSHOT, we need to have this property changed to false to prevent CSRF token caching within the browser when during the token transmission to the client.

**Comment by dkayiwa** [comment]
@kdaud what did you base on to confirm that the failure is caused by token caching? Do you have any logs to share?

**Comment by sherrif10** [comment]
@dkayiwa here are the logs https://pastebin.com/yt8kx05Y

**Comment by kdaud** [comment]
> @kdaud what did you base on to confirm that the failure is caused by token caching? Do you have any logs to share?


This is observed from the client side not server side, so what I can share for now is the UX when running the test locally.
Screenshot from 2022-01-26 16-43-00

**Comment by kdaud** [comment]
@dkayiwa unfortunately we seem not have this property set globally directly via the server at https://qa-refapp.openmrs.org/openmrs/login.htm#/list and since we are running our server against the latest platform SNAPSHOT then we may need to have it set within the module. Unless otherwise :-1: 

FWIW we can have this tested out and see how it goes though we need to first fix the failing test within the module to have this merged your in favor of my opinion.  Soon will share the fix to the failing test.

**Comment by dkayiwa** [comment]
@kdaud we do not have to change this property because we need the CSRF functionality. We only need to figure out how to make the tests pass with it. Does it make sense?

**Comment by kdaud** [comment]
> @kdaud we do not have to change this property because we need the CSRF functionality. We only need to figure out how to make the tests pass with it. Does it make sense?

It makes sense. 

@sherrif10 mentioned of sharing a fix to the failure and my eyes are open to see how the fix would look like.

Meanwhile @dkayiwa as of now my guessing is on how OpenMRSfilter class is playing around with the HTTP request made by the client. I think instead of conditioning the method to [get request url ](https://github.com/openmrs/openmrs-core/blob/40e464b97fdbb19d44ae5f1ecc1a04a956f62c6b/web/src/main/java/org/openmrs/web/filter/OpenmrsFilter.java#L99)  may need to get parameter of owasp-csrftoken in case is not null.

**Review by LuGO0 — APPROVED** [review]

**Comment by LuGO0** [comment]
https://issues.openmrs.org/browse/TRUNK-6053
^^ I faced similar Issue here which was resolved by temporarily switching off the flag.

**Comment by dkayiwa** [comment]
@LuGO0 that was fixed here: https://github.com/openmrs/openmrs-core/commit/40e464b97fdbb19d44ae5f1ecc1a04a956f62c6b

So you should be good even when that property is not disabled.

**Comment by LuGO0** [comment]
> So you should be good even when that property is not disabled.

updated the Issue.

**Comment by dkayiwa** [comment]
Feel free to do so.

**Pull request closed without merging**
