### PR TITLE
removed security bug in startupFilter.java by whitelisting user input

### PR DESCRIPTION
**Pull request by mohammed-alfatih**
## Related Issue

see https://issues.openmrs.org/browse/TRUNK-

## Checklist:

- [x] My pull request only contains one single commit.
- [ ] My pull request is based on the latest master branch
  `git pull --rebase upstream master`.
- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mohammed-alfatih do we have a ticket for this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by mohammed-alfatih** [comment]
@dkayiwa I believe we don't. how would one get a ticket?

**Comment by dkayiwa** [comment]
@mohammed-alfatih is this helpful? https://wiki.openmrs.org/display/docs/Tickets

**Comment by dkayiwa** [comment]
@mohammed-alfatih did you get to create this ticket?

**Comment by dkayiwa** [comment]
@mohammed-alfatih any response to the above? :)

**Comment by dkayiwa** [comment]
@mohammed-alfatih ping me to reopen when you get back to this. :)

**Pull request closed without merging**
