### PR TITLE
[TRUNK-5280] Redundant default parameter value assignment in annotations

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/TRUNK-5280

### CODE REVIEW

**Comment by dkayiwa** [comment]
What happens if the default value is changed?

**Comment by BartlomiejRasztabiga** [comment]
I know it would break down, but there are cases where it probably won't be changed, like a length of column (255).

**Comment by dkayiwa** [comment]
And isn't the original more readable? In other words, not having to look for default value to know the length, to know if a transaction is read only, etc

**Comment by BartlomiejRasztabiga** [comment]
You are right, closing 😊

**Pull request closed without merging**
