### PR TITLE
Prevent SNAPSHOT versions from being uploaded

### PR DESCRIPTION
**Pull request by joshim5**
In response to an introductory ticket posted on OpenMRS Issues.

https://issues.openmrs.org/browse/MOD-8

### CODE REVIEW

**Comment by dkayiwa** [comment]
@joshim5 did you notice that there is a unit test which fails in ModuleUtilTest?

**Comment by joshim5** [comment]
@dkayiwa Yes -- This is because the OpenMRS unit tests test the uploading of SNAPSHOT versions. Seeing as we no longer allow SNAPSHOT versions, should these unit tests be changed?

**Comment by dkayiwa** [comment]
@joshim5 the changes should be in https://github.com/openmrs/openmrs-contrib-modulus

**Comment by maywuy** [comment]
if we were to fix this issue, should we make changes to the unit test?

**Pull request closed without merging**
