### PR TITLE
TRUNK-5914:  openmrs-core tests currently failing

### PR DESCRIPTION
**Pull request by achilep**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5914

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by achilep** [comment]
@teleivo  from this suggestion : https://talk.openmrs.org/t/openmrs-core-tests-currently-failing/29784/6?u=achilep

**Comment by achilep** [comment]
thanks @teleivo

**Comment by dkayiwa** [comment]
How about putting a TODO in the test that fails? Just in case we forget fixing this and it shows up again when we do not remember.

**Comment by achilep** [comment]
yes @dkayiwa , good suggestion .

**Comment by achilep** [comment]
```
This test fails because the expiration date  for alert_id=“2” in HibernateAlertDAOTestDataSet.xml has passed. TODO
Make sure the current date is still behind the expiration date.
```
@dkayiwa  what about this TODO ?

**Comment by sherrif10** [comment]
Thanks @achilep  @teleivo  @dkayiwa  does that mean that each year will need to fix this test to the current year for test to pass?

**Comment by teleivo** [comment]
@sherrif10 J commented a suggestion on the ticket that introduced the test for an adjustment so that does not happen again. So there is work to do.

**Pull request merged**
