### PR TITLE
TRUNK-5231  Added tests to check for start/length values passed in g…

### PR DESCRIPTION
**Pull request by Ekirapapaul**
…etpatients(...)

## Description of what I changed

I added test cases to check for the patients returned if start and length values are passed to getPatients() method

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5231

## Checklist: I completed these to help reviewers :)

- [x ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Ekirapapaul the ticket url that you included above is not complete.

**Comment by Ekirapapaul** [comment]
@dkayiwa apologies for that. I have updated it

**Comment by dkayiwa** [comment]
Did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Ekirapapaul** [comment]
Yes i have done those. However when i do `mvn clean package` even on a clean master branch i get this
```
Tests run: 55, Failures: 2, Errors: 0, Skipped: 4, Time elapsed: 0.593 sec <<< FAILURE! - in org.openmrs.api.AdministrationServiceTest
getAllGlobalProperties_shouldReturnAllGlobalPropertiesInTheDatabase(org.openmrs.api.AdministrationServiceTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: expected:<21> but was:<25>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.openmrs.api.AdministrationServiceTest.getAllGlobalProperties_shouldReturnAllGlobalPropertiesInTheDatabase(AdministrationServiceTest.java:449)

purgeGlobalProperty_shouldDeleteGlobalPropertyFromDatabase(org.openmrs.api.AdministrationServiceTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: expected:<21> but was:<25>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.openmrs.api.AdministrationServiceTest.purgeGlobalProperty_shouldDeleteGlobalPropertyFromDatabase(AdministrationServiceTest.java:514)

```

Its worth noting that i haven’t touched on anything to do with those tests

**Comment by dkayiwa** [comment]
Can you post this on openmrs talk?

**Comment by Ekirapapaul** [comment]
Thamks @dkayiwa . Will do that.

**Pull request closed without merging**
