### PR TITLE
Added test as per TRUNK-4867

### PR DESCRIPTION
**Pull request by hirschf2**
Added test that throws exception if a deathdate is set for a patient before their birthdate.

### CODE REVIEW

**Comment by hirschf2** [comment]
This test should fail until the bug is patched, hence the API exception.

**Comment by sunbiz** [comment]
@hirschf2 you should include the fix in this PR for validating death date here - https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/validator/PersonValidator.java

**Comment by dkayiwa** [comment]
@hirschf2 did you see the comment from @sunbiz?

**Comment by dkayiwa** [comment]
@hirschf2 i can reopen if anyone commits a fix that makes this test pass.

**Pull request closed without merging**
