### PR TITLE
Trunk 4813

### PR DESCRIPTION
**Pull request by mnsowmya**

### CODE REVIEW

**Comment by mnsowmya** [comment]
@dkayiwa In the link they mentioned to add both new check sum as well the previous old one

**Comment by dkayiwa** [comment]
@mnsowmya shouldn't  you be adding only for the previous one?

**Comment by mnsowmya** [comment]
@dkayiwa will there be any problem if i mention both can you tell me what would be the problem.i am not sure about this

**Comment by dkayiwa** [comment]
@mnsowmya we generally do not include those that are not yet released. Does this make sense?

**Comment by mnsowmya** [comment]
@dkayiwa ok

**Pull request merged**
