### PR TITLE
Trunk 4608 - Add ability to stop all the modules at one click option

### PR DESCRIPTION
**Pull request by ivange94**
https://issues.openmrs.org/browse/TRUNK-4608.

Successfully implemented a stop all button to stop all started modules

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ivange94 can you squash the commits into one?

**Comment by dkayiwa** [comment]
@ivange94 what do you mean by it does not work as expected?

**Comment by ivange94** [comment]
When i click, Stop All, nothing happens, the page reloads but the modules are still running

**Comment by dkayiwa** [comment]
Add another call for WebModuleUtil.stopModule() just as it is done in ModuleListController

**Comment by dkayiwa** [comment]
@ivange94 also ensure that you refresh the context only once for all modules instead of separately for each module. :)

**Comment by ivange94** [comment]
this pull request has commits that are not mine. i don't really know how they got there, so i will just close this one and create another

**Pull request closed without merging**
