### PR TITLE
[TRUNK-5279] Access modifier could be private

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
Issue: https://issues.openmrs.org/browse/TRUNK-5279

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you see the codacy-bot comments?

**Comment by BartlomiejRasztabiga** [comment]
Yes, working on it 😊

**Comment by dkayiwa** [comment]
@BartlomiejRasztabiga do we still need this? 😊

**Comment by BartlomiejRasztabiga** [comment]
I will fix that after I do GCI task :)

**Comment by teleivo** [comment]
@BartlomiejRasztabiga I don't think we should make these changes as these would most probably break modules code: for example Allergy.setPatient() was public which means you dont know who is using it just because its not referenced in openmrs-core (longer explanation here https://issues.openmrs.org/browse/TRUNK-5279).

@dkayiwa @wluyima what do you think?

**Comment by BartlomiejRasztabiga** [comment]
Okay, I didn't think about other code from outside of openmrs-core. I think i will just close the PR. Thanks for explanation :)

**Comment by dkayiwa** [comment]
@teleivo i fully agree! 👍

**Pull request closed without merging**
