### PR TITLE
Fixing bug that showing database stack traces when user input fields too long - TRUNK-4539

### PR DESCRIPTION
**Pull request by MatthiasZerau**
- extended UserValidator class to validate inner Person instance as well
- extended and fixed unit tests w.r.t. this change

### CODE REVIEW

**Comment by MatthiasZerau** [comment]
@dkayiwa please review, added the missing @should annotation, tanks for the notice

**Comment by MatthiasZerau** [comment]
Local build of openmrs-core works without any failure. NameSupportTest passes in Eclipse as well as with Maven build.

**Comment by dkayiwa** [comment]
@MatthiasZerau we encourage squashing commits into one as per http://go.openmrs.org/pull-request-tips

**Comment by dkayiwa** [comment]
Yes something must be wrong with our testing framework that makes this fail only on travis. Or it could be exposing a bug in our code some where, that is only exposed by travis. :)

**Comment by MatthiasZerau** [comment]
Squashed my 2 commits into one, renamed the helper method in the test.

**Comment by dkayiwa** [comment]
@MatthiasZerau will this fix it for all cases affected by TRUNK-4539? :)

**Comment by MatthiasZerau** [comment]
No only for the User domain objects, but better than nothing I think.

**Comment by dkayiwa** [comment]
@MatthiasZerau i agree! :)

**Pull request merged**
