### PR TITLE
Trunk 5825: Improving Polish translation

### PR DESCRIPTION
**Pull request by sacull**
## Description of what I changed

Improving Polish translation in a file api/src/main/messages_pl.properties. Currently, most phrases are in English.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5825

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by jwnasambu** [comment]
Kindly attach the PR to the ticket you have worked on and change its status to code review.

**Comment by sacull** [comment]
> Kindly attach the PR to the ticket you have worked on and change its status to code review.

Please write what the abbreviation PR means.

Status changed to "code review".

**Comment by sacull** [comment]
@jwnasambu I found what the abbreviation PR means -> PR = pull request. So the question is now out of date. Have a nice day. ;)

**Comment by sacull** [comment]
Pull request closed due to commit merge problem.

**Comment by sacull** [comment]
Current pull request -> https://github.com/openmrs/openmrs-core/pull/3323

**Pull request closed without merging**
