### PR TITLE
TRUNK-2736: Changed the InitializationFilter in that when an error oc…

### PR DESCRIPTION
**Pull request by IamMujuziMoses**
https://issues.openmrs.org/browse/TRUNK-2736

### CODE REVIEW

**Comment by gitcliff** [comment]
@IamMujuziMoses  have u seen the travis ci build failure ?

**Comment by HerbertYiga** [comment]
add a ticket description for this!!

**Comment by IamMujuziMoses** [comment]
@gitcliff what does the travic ci build failure mean, what did i do wrong?

**Comment by gitcliff** [comment]
@IamMujuziMoses  are building successful after running "mvn clean install" on your pc?....if not kindly share the build failure logs here https://pastebin.com/

**Comment by dkayiwa** [comment]
@IamMujuziMoses are you still working on this?

**Comment by IamMujuziMoses** [comment]
@dkayiwa  yes am still on it

**Comment by dkayiwa** [comment]
@IamMujuziMoses when do you plan to finish this?

**Comment by IamMujuziMoses** [comment]
I am so sorry for the delay, I tried running the mvn clean install but this kept on happening

Screenshot (7)

**Comment by IamMujuziMoses** [comment]
So @dkayiwa please help me close this PR and i will try out another task. Thank you. God Bless

**Pull request closed without merging**
