### PR TITLE
TRUNK-5851: Simplify the Reflect class code

### PR DESCRIPTION
**Pull request by BartlomiejRasztabiga**
## Description of what I changed
Simplified Reflect.getInheritedFields method by using Collection.removeIf

## Issue I worked on
see https://issues.openmrs.org/browse/TRUNK-5851

## Checklist: I completed these to help reviewers :)
- [X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [X] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [X] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [X] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sacull** [comment]
@BartlomiejRasztabiga Are you sure there is a test that checks if the change you have made is working as it should?

**Comment by BartlomiejRasztabiga** [comment]
@sacull It's being tested here: https://github.com/openmrs/openmrs-core/blob/134a1c8fc03ef484b1533a0c3c06a8d2b6c33270/api/src/test/java/org/openmrs/util/ReflectTest.java#L130

**Comment by HerbertYiga** [comment]
> Are you sure there is a test that checks if the change you have made is working as it should?

i find the test class for that here,https://github.com/openmrs/openmrs-core/blob/134a1c8fc03ef484b1533a0c3c06a8d2b6c33270/api/src/test/java/org/openmrs/util/ReflectTest.java#L130   @sacull  dou you think this is good to be merged

**Comment by gracepotma** [comment]
@sacull would you mind checking if this can be merged? Would be nice to wrap this up as well :)

**Pull request merged**
