### PR TITLE
GCI-205 Rename auth_role in UserServiceImpl to match our convention

### PR DESCRIPTION
**Pull request by JyothsnaAshok**
## Description of what I changed

The auth_role variable on line https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java#L569 and this line https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java#L601 should be renamed to authRole to match our naming conventions on this page. https://wiki.openmrs.org/display/docs/Java+Conventions#JavaConventions-NamingConventions

## Issue I worked on

see https://issues.openmrs.org/browse/GCI-205

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by suthagar23** [comment]
Thanks for effort @JyothsnaAshok.
Code work is completed but you missed to complete some steps before creating PR. Please read[ PR guidelines](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) again :-)
Hint: Check your issue status and update everything in your PR description!

**Comment by JyothsnaAshok** [comment]
@suthagar22 Do I need to leave a request for review on JIRA too?

**Comment by suthagar23** [comment]
@JyothsnaAshok YES and Don't forget to mark **X** in your PR description.

**Comment by JyothsnaAshok** [comment]
@suthagar23  What's X?

**Comment by suthagar23** [comment]
@JyothsnaAshok  Completed !! Thanks for the effort. @dkayiwa  Can we move to merge this PR?

**Pull request merged**
