### PR TITLE
ERR-821 - Retrieve Location Name during login taking longer time

### PR DESCRIPTION
**Pull request by vikashgupta2000**
Please make the same changes in 1.10.x branch.

### CODE REVIEW

**Comment by vikashgupta2000** [comment]
Please make the same changes in 1.10.x

**Comment by dkayiwa** [comment]
@vikashgupta2000 your pull request has merge conflicts. Can you pull the latest changes form upstream and try again?

**Comment by dkayiwa** [comment]
@vikashgupta2000 i also see that the ticket you are working on is not ready for work. It needs assessment. We encourage you to work on only those tickets which are ready for work.

**Comment by dkayiwa** [comment]
@vikashgupta2000 remind me to reopen this after you deal with the above.

**Comment by vikashgupta2000** [comment]
@dkayiwa Ticket #TRUNK-4692 is created.

**Comment by dkayiwa** [comment]
@vikashgupta2000 am not able to reopen this pull request. did you force-push?

**Pull request closed without merging**
