### PR TITLE
TRUNK-5528:Upgrade org.apache.lucene sub Libraries

### PR DESCRIPTION
**Pull request by jwnasambu**
## Description of what I changed

I upgraded library org.apache.lucene sub Libraries 

1. org.apache.lucene:lucene-queries … 4.10.4 -> 8.1.0
2.  org.apache.lucene:lucene-queryparser … 4.10.4 -> 8.1.0

## Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5528

### CODE REVIEW

**Comment by jwnasambu** [comment]
@dkayiwa  and @mozzy11 I have updated with  the current release version but still failing to build locally and after making the PR.

**Comment by dkayiwa** [comment]
Does version 5.0.0 work fine?

**Comment by jwnasambu** [comment]
dkayiwa version 5.0.0 fails to build locally and this is the error log https://hastebin.com/ozibizewob.sql

**Comment by sherrif10** [comment]
@jwnasambu  did you  try the version specified by @dkayiwa  ?

**Comment by sherrif10** [comment]
Hey @jwnasambu how fur with this try different versions from 4 to 8 and before you shift to another try building and watch the results

**Comment by jwnasambu** [comment]
@sherrif10 kindly have a look at the the comment I left on this link https://issues.openmrs.org/browse/TRUNK-5528

**Comment by dkayiwa** [comment]
@jwnasambu did you try sharing the travis build failure on talk?

**Comment by jwnasambu** [comment]
I have just created a post on talk on this link Travis CI failure after upgrading lucene sub Libraries

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Travis CI failure after upgrading lucene sub Libraries

Hello friends, can someone advice me on how to go about this issue https://issues.openmrs.org/browse/TRUNK-5528?...
 |

 |

 |




    On Monday, February 3, 2020, 12:57:22 AM GMT+3, dkayiwa <notifications@github.com> wrote:  
 
 
@jwnasambu did you try sharing the travis build failure on talk?

**Pull request closed without merging**
