### PR TITLE
TRUNK-4813, TRUNK-4869, TRUNK-4868

### PR DESCRIPTION
**Pull request by rasient**
TRUNK-4869 add death date validation

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rasient can you squash these commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by rasient** [comment]
@dkayiwa I did the steps written down there, can you please check recheck it?

**Comment by dkayiwa** [comment]
@rasient on this page i still see three commits that need to be squashed into one.

**Comment by rasient** [comment]
@dkayiwa now the last commit is ok?

**Comment by dkayiwa** [comment]
@rasient just take a look at this page and you will see that it has multiple commits/merges, etc

**Comment by dkayiwa** [comment]
@rasient if you find it hard to resolve this, feel free to ask for help on IRC https://wiki.openmrs.org/display/IRC/Home

**Comment by dkayiwa** [comment]
@rasient can you create a separate pull request for each ticket? Am assuming you saw this: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request closed without merging**
