### PR TITLE
Trunk 5497

### PR DESCRIPTION
**Pull request by reagan-meant**
Trunk-5497 Upgrade MySQL version From 5.7 to 8.0
https://issues.openmrs.org/browse/TRUNK-5497
## Description of what I changed
Updated the mysql-connector-java from 5.1.45 to 8.0.16, mysql-connector-mxj from 5.0.11 to 5.0.12 and mysql-connector-mxj-db-files from 5.0.11 to 5.0.12
## Checklist: I completed these to help reviewers :)
- [ ] My pull request only contains **two commits**
- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.(YES)

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@reagan-meant   have you seen the failing ci build?

**Comment by reagan-meant** [comment]
Any ideas of how I  should go about this?

**Comment by mozzy11** [comment]
Thank you so much fortrying on this @reagan-meant . Now you should alway squas your commits into one as advised here https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by mozzy11** [comment]
About your travis failure , you seem to be missing a licenece header in this file 
[WARNING] Missing header in: /home/travis/build/openmrs/openmrs-core/pom.xml

**Pull request closed without merging**
