### PR TITLE
TRUNK-5535:Upgrade org.codehaus Libraries

### PR DESCRIPTION
**Pull request by jwnasambu**
## Description of what I changed
I upgraded org.codehaus.sonar-plugins.java:sonar-jacoco-listeners  from version 3.1 -> 5.14.0.18788

## Issue I worked on

https://issues.openmrs.org/browse/TRUNK-5535

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sherrif10** [comment]
Thanks for working on this however,Am not sure about that upgrade, i will try testing on my machine locally

**Comment by achilep** [comment]
hello @jwnasambu the ticket requires an upgrade to 3 dependencies but your PR only has one.

> Upgrade library org.codehaus. sub Libraries below
>     org.codehaus.jackson:jackson-core-asl … 1.9.13 -> 1.9.13-atlassian-2
>     org.codehaus.jackson:jackson-mapper-asl … 1.9.13 -> 1.9.13-atlassian-2
>     org.codehaus.sonar-plugins.java:sonar-jacoco-listeners … 3.1 -> 3.2

**Comment by jwnasambu** [comment]
@achilep  you are right.  I did so because of 2 reasons:
1. Basing on https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mapper-asl and https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-core-asl the latest release versions for both libraries is 1.9.13. 
2. version  1.9.13-atlassian-2  is  a beta releases  which is still under development and by shifting to that version may not solve or fix the challenges we are solving i.e. backward compatibility , data leakage e.t.c.

**Comment by achilep** [comment]
it's true what you say. but concerning sonar-jacoco-listeners you are not confounding the https://mvnrepository.com/artifact/org.sonarsource.java/sonar-jacoco-listeners/5.14.0.18788  with https://mvnrepository.com/artifact/org.codehaus.sonar-plugins.java/sonar-jacoco-listeners/3.2 .

**Comment by jwnasambu** [comment]
@achilep You are right! the ticket description requires me to upgrade from 3.1 -> 3. 2 but I choose to got for  5.14.0.18788 because its the latest  release.

**Comment by achilep** [comment]
hello @jwnasambu are you still working on this PR ?

**Comment by jwnasambu** [comment]
@achilep thanks for reaching out on this! the ticket is under code review state and just waiting for your comment if you can help me review. I gave my reasons why I only upgraded one sub-library above and why I upgraded org.codehaus.sonar-plugins.java:sonar-jacoco-listeners from version 3.1 -> 5.14.0.18788.  Feel free to leave your comment

**Comment by jwnasambu** [comment]
@teleivo I initially  upgraded to 3.2 as per this PR https://github.com/openmrs/openmrs-core/pull/2942 but was advised use the latest version that is why you are seeing 5.14.0.18788.

**Comment by teleivo** [comment]
@jwnasambu can you please provide a link to where this version is. I checked maven central and 3.2 was the latest which is why dependabot chose it

**Pull request closed without merging**
