### PR TITLE
TRUNK-4345: Non ASCII characters do not display correctly in spanish

### PR DESCRIPTION
**Pull request by BhavanaRamasayam**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@BhavanaRamasayam can you squash these commits into one as advised at http://go.openmrs.org/pull-request-tips

**Comment by BhavanaRamasayam** [comment]
@dkayiwa There is only one commit now. I have closed all the previous ones .Please do check :)

**Comment by dkayiwa** [comment]
@BhavanaRamasayam i still see two commits which are not yet squashed.

**Comment by BhavanaRamasayam** [comment]
@dkayiwa I have referenced this pull request from the previous pull request .That's the reason the second commit message shows up. But if you can check the commit tab, there is only one commit. Please do check :)

**Comment by dkayiwa** [comment]
@BhavanaRamasayam can you close one of the pull requests?

**Comment by BhavanaRamasayam** [comment]
@dkayiwa I already closed the previous pull request :)

**Comment by dkayiwa** [comment]
@BhavanaRamasayam can you do a new pull request that shows only one commit instead of two?

**Pull request closed without merging**
