### PR TITLE
MM-860: Implemented anti-csrf tokens for OpenMRS protection against CSRF attacks

### PR DESCRIPTION
**Pull request by jnsereko**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by jnsereko** [comment]
Hello Devs 
i have tried to create an implementation that tries to prevent a malicious use from accessing an OpenMRS instance through Cross-Site request forgery.   

I can still login through CSRF so this hasn't worked yet.
I think i might be loosing track so i have sent a PR before writing tests to give me a go ahead.

My intention is to send a cookie and verify the cookie from the login page or JavaScript.  However, when i run my local instance, the cookie inst created yet.  Maybe am looking it from a wrong position.  

Thanks.   
@isears @sherrif10 @ibacher @mozzy11 @HerbertYiga  and everyone else

**Comment by ibacher** [comment]
Yeah... I'm not sure you can just drop a `WebSecurityConfigurerAdapter` class in there and have it actually do anything. By default OMRS loads the Spring configuration from the `openmrs-servlet.xml` file in the Web project. You might need to add the necessary configuration to the XML file instead of using Spring annotations.

**Comment by jnsereko** [comment]
OOhh..!
thanks @ibacher 
I definitely didn't know where configurations are loaded from in OMRS.  Am going to leave all the annotations and the classes i have created, first add the XML-based configuration and run my local instance to see if i get any cookie.

However, I think OpenMRS uses the Ui-framework for its REST services.  Is there a way we can validate the configure the UI framework  to forbid requests without this cookie or token

**Comment by dkayiwa** [comment]
@jnsereko did you see these merge conflicts?

**Comment by jnsereko** [comment]
Thank you @dkayiwa, I had not recognised the Conflict.
However, I had decided to pend this issue until GSoC 2021 ends because I faced an error `unable to access org.springframework.security.AuthenticationManager class.`  and all bean creation failed after adding the listeners and the repositories to the` openmrs-servlet-context.xml ` file as @ibacher had advised me.

**Comment by jwnasambu** [comment]
@jnsereko kindly update your branch to fix the merge conflicts.

**Comment by jwnasambu** [comment]
@jnsereko kindly update your branch to fix the merge conflicts.

**Comment by jnsereko** [comment]
closing this because implementation was done already

**Pull request closed without merging**
