### PR TITLE
TRUNK-5767: Switch core from mxj to mariaDB4j

### PR DESCRIPTION
**Pull request by kdaud**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5767

## Checklist: I completed these to help reviewers :)

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kdaud did you test this?

**Comment by kdaud** [comment]
Yes!

What have done is to build the core with the changes after a successful build plan have got the `openmrs.war` file and tested it with my local server and the refapp is running well without any issue.

**Comment by dkayiwa** [comment]
Take a look at this: https://wiki.openmrs.org/display/docs/OpenMRS+Standalone

Sorry for the ticket not being properly written. But our goal is for this to replace the OpenMRS Standalone in-memory mysql with mariadb. So for this to be fully done, one should be able to run the standalone with an embedded mariadb.

**Comment by dkayiwa** [comment]
@kdaud how did you run the OpenMRS Standalone?

**Comment by kdaud** [comment]
> @kdaud how did you run the OpenMRS Standalone?

Haven't done this at the moment.

What I did was to test the openmrs.war file with the changes on a local server generated by sdk .

**Pull request closed without merging**
