### PR TITLE
TRUNK-5550: Upgrade org.slf4j Libraries

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-5550

### CODE REVIEW

**Comment by mozzy11** [comment]
thanks @ODORA0  for the work ? it looks quite good.

**Comment by mozzy11** [comment]
cc @dkayiwa

**Comment by dkayiwa** [comment]
A beta versions is not a full release. We depend only on full releases.

**Comment by ODORA0** [comment]
OK!! I think that should have been changed in the ticket description as well @mozzy11, I'll have that changed non the less

**Comment by ODORA0** [comment]
@dkayiwa @mozzy11  I don't really get the error message here, when it says `[WARNING] The POM for org.slf4j:slf4j-api:jar:1.8.0 is missing, no dependency information available`

**Comment by mozzy11** [comment]
@ODORA0 , yes you can look for the latest full release of that lib from their website

**Comment by mozzy11** [comment]
@ODORA0 , yes you can look for the latest full release of that lib from their website

The error arises because you used a library version that doent exist. google out the latest full released version

**Comment by ODORA0** [comment]
So according to https://www.slf4j.org/news.html and some various google resources show the tool is still in it's beta release stages, I had to check this as well https://mvnrepository.com/artifact/org.slf4j/slf4j-api to clarify. Maybe unless of-course we are shifting to 1.7.26 rather than the 1.8.x series I think that would do.

**Comment by mozzy11** [comment]
@ODORA0 have you confirmed that  1.7.0 is the latest Full version??

**Comment by ODORA0** [comment]
The latest full version 1.7.26 gave a coveralls failure when I pushed the changes, the 1.8.x series is in the beta stages so not really sure now

**Comment by mozzy11** [comment]
then youwould probablygo with **1.7.26** , you may ignore the coveralls failure

**Comment by dkayiwa** [comment]
Yes i agree going with 1.7.26 👍

**Pull request merged**
