### PR TITLE
TRUNK-5362:Issue with method in EncounterService causing extreme slowness

### PR DESCRIPTION
**Pull request by suubi-joshua**
## Description of what I changed
I Used batch fetching: Instead of retrieving encounters for each patient individually.  Hoping  improve performance. I used the getEncountersByPatientId method of the EncounterService, passing in a list of patient IDs instead of retrieving encounters for each patient individually.

I tried to retrieve a list of all patients with the given identifier using the getPatients method of the PatientService then extract the patient IDs from the list and pass them to the getEncountersByPatientId method of the EncounterService to retrieve all encounters associated with those patients in a single query.

It is a try to make the method faster 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5362

## Checklist: I completed these to help reviewers :)

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by jona42-ui — COMMENTED** [review]
Your approach of using batch fetching by passing a list of patient IDs to the getEncountersByPatientId method instead of retrieving encounters for each patient individually is a good optimization technique to improve performance in addition to using the getPatients method of the PatientService to retrieve a list of patients with the given identifier and then extracting the patient IDs, you're reducing the number of database queries even further.

However, it's always a good practice to perform thorough testing to ensure that the performance improvements are significant and that the changes do not introduce any new issues or bugs.

Can you provide the tests results  especially you ca collect and analyze performance metrics such as response time, throughput, and error rate.

**Comment by suubi-joshua** [comment]
> Your approach of using batch fetching by passing a list of patient IDs to the getEncountersByPatientId method instead of retrieving encounters for each patient individually is a good optimization technique to improve performance in addition to using the getPatients method of the PatientService to retrieve a list of patients with the given identifier and then extracting the patient IDs, you're reducing the number of database queries even further.
> 
> However, it's always a good practice to perform thorough testing to ensure that the performance improvements are significant and that the changes do not introduce any new issues or bugs.
> 
> Can you provide the tests results especially you ca collect and analyze performance metrics such as response time, throughput, and error rate.

Exactly okay still working on the testing beat to see if the slowness is reduced.

**Comment by sjmckee** [comment]
I don't believe your PR fixes the issue. Here's the old method in HibernatePatientDAO.java that only queried patients by identifier. This was removed in sometime after OpenMRS 1.7 I believe. The best option may be to put it back. The current method searches across all aspects of the patient (patient identifiers, person names, person attributes) instead of just identifiers as the method name suggests, and this is what makes it extremely slow.  So basically, the issue is with the patient search itself and not building a list of encounter from the patient search.  Also, please refer to the conversation on the previous PR (https://github.com/openmrs/openmrs-core/pull/4052).

`public List<Patient> getPatientsByIdentifier(String name, String identifier,
	List<PatientIdentifierType> identifierTypes, boolean matchIdentifierExactly) throws DAOException {
		
	Criteria criteria = sessionFactory.getCurrentSession().createCriteria(Patient.class);
	criteria = new PatientSearchCriteria(sessionFactory, criteria).prepareCriteria(name, identifier, identifierTypes,
	        matchIdentifierExactly);
	// restricting the search to the max search results value
	criteria.setFirstResult(0);
	criteria.setMaxResults(HibernatePersonDAO.getMaximumSearchResults());
		
	return criteria.list();
}`

**Comment by suubi-joshua** [comment]
> I don't believe your PR fixes the issue. Here's the old method in HibernatePatientDAO.java that only queried patients by identifier. This was removed in sometime after OpenMRS 1.7 I believe. The best option may be to put it back. The current method searches across all aspects of the patient (patient identifiers, person names, person attributes) instead of just identifiers as the method name suggests, and this is what makes it extremely slow. So basically, the issue is with the patient search itself and not building a list of encounter from the patient search. Also, please refer to the conversation on the previous PR (#4052).
> 
> ```
> public List<Patient> getPatientsByIdentifier(String name, String identifier,
> 	List<PatientIdentifierType> identifierTypes, boolean matchIdentifierExactly) throws DAOException {
> 		
> 	Criteria criteria = sessionFactory.getCurrentSession().createCriteria(Patient.class);
> 	criteria = new PatientSearchCriteria(sessionFactory, criteria).prepareCriteria(name, identifier, identifierTypes,
> 	        matchIdentifierExactly);
> 	// restricting the search to the max search results value
> 	criteria.setFirstResult(0);
> 	criteria.setMaxResults(HibernatePersonDAO.getMaximumSearchResults());
> 		
> 	return criteria.list();
> }
> ```

Okay 
My question is what was the reason of removing the method in the HibernatePatientDAO.java.

**Comment by sjmckee** [comment]
That's a very valid question and one I've been curious about since it was removed.  We may need to dig through the ticketing system to find the exact reasoning.  I do know OpenMRS 1.17 was the last time the method stated above existed.

**Comment by jwnasambu** [comment]
@suubi-joshua Kindly fix the conflicting files please!

**Comment by suubi-joshua** [comment]
> @suubi-joshua Kindly fix the conflicting files please!

I have worked on the conflicts

**Comment by jona42-ui** [comment]
The rebase was not a nice one , you pulled in other commits. Look into this @suubi-joshua

**Comment by jona42-ui** [comment]
Reverting could help
git rebase -i HEAD~N
Then pick, drop or edit to maintain a target commit

**Comment by suubi-joshua** [comment]
> The rebase was not a nice one , you pulled in other commits. Look into this @suubi-joshua

Yaaaa sure let me work on that

**Comment by jwnasambu** [comment]
@suubi-joshua oh sorry! for the many conflicting files. The reason why you are having many changes from different contributors reflected in your PR is because the branch you are pushing your changes on is wrong. Kindly your changes are supposed to be on 2.x. Branch

**Comment by suubi-joshua** [comment]
> @suubi-joshua oh sorry! for the many conflicting files. The reason why you are having many changes from different contributors reflected in your PR is because the branch you are pushing your changes on is wrong. Kindly your changes are supposed to be on 2.x. Branch

Thanks @jwnasambu 
That would explain alot. Thanks

**Comment by suubi-joshua** [comment]
I am creating a more cleaner PR.

**Comment by suubi-joshua** [comment]
The new PR:  https://github.com/openmrs/openmrs-core/pull/4303

**Pull request closed without merging**
