### PR TITLE
TRUNK-5818 Enable module devs to write Junit 4 & 5 tests

### PR DESCRIPTION
**Pull request by achilep**
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5818

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by achilep** [comment]
Hello @teleivo to solve this  https://github.com/openmrs/openmrs-module-webservices.rest/pull/445 I have to remove `<scope>test</scope>`  , how do you find the  the rest of dependencies that I deleted .

**Comment by teleivo** [comment]
are you sure its the scope? these are test dependencies and should be of scope test
I am unsure about the other deletions. On the one hand its more consistent with what we currently do. On the other hand I think what we currently do with test dependencies is wrong. I need some more time to think about this.

**Comment by achilep** [comment]
@teleivo I also read that the test scope is not transitive https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

**Comment by teleivo** [comment]
> @teleivo I also read that the test scope is not transitive https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

thanks for pointing to this  resource :) so what you are saying is that if we use test scope, this leads to openmrs-test not propagating the dependency to web services? and if you remove the test scope it should by default be a compile scope of openmrs-test and thus 

> compile
This is the default scope, used if none is specified. Compile dependencies are available in all classpaths of a project. Furthermore, those dependencies are propagated to dependent projects.

so only then its propagated. Correct?

And since modules declare openmrs-test as dependency with scope test it is not included in their production jar / omod.

I just want us to fully understand how it currently works. I still think its wrong but I will post a longer thread on talk about my theory.

I you acknowledge my deduction above I think I am ok with merging this as its consistent with what we currently have.

**Comment by achilep** [comment]
@teleivo I think that what we are doing is correct. I look at previous version of openmrs core api, i notice that there is not  `<scope>test</scope>` with junit 4  And the test dependencies are only include in the test pom file .
https://github.com/openmrs/openmrs-core/blob/9c87e0a8f4719e7db1b291a8ed41878906e19e8b/pom.xml#L463
https://github.com/openmrs/openmrs-core/blob/31fa025f2bb0e71208c17a0b5745e4eb9eeef14b/pom.xml#L461

**Pull request merged**
