### PR TITLE
Trunk-5331:Cohort membership should not require a startDate

### PR DESCRIPTION
**Pull request by gitcliff**
link:https://issues.openmrs.org/browse/TRUNK-5331
CohortMembership should not require a startDate

1-dropped the not-null constraint on CohortMembership.startDate
2-removed Java logic that defaults CohortMembership.startDate to new Date(), and instead default it to null.
3-Cohort.intersect should behave in a way that makes sense if you give it {Patient 123, startDate Jan 1} and {Patient 123, startDate Feb 15}.
I would be satisfied if the output is either a cohort with {Patient 123, startDate Feb 15}, or else a cohort with {Patient 123, startDate null}.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
You have  some conflicting files on this

**Comment by gitcliff** [comment]
let me look into it

**Comment by mozzy11** [comment]
@gitcliff  , have you seen the merge comflcts ??

**Comment by gitcliff** [comment]
i have fixed it

**Comment by ibacher** [comment]
@gitcliff Would you be able to update this PR to run against 2.4?

**Pull request closed without merging**
